WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
ALTER SESSION SET CURRENT_SCHEMA = APP_OWNER;

DECLARE
    v_existing_columns NUMBER;
    v_existing_constraints NUMBER;
    v_invalid_rows NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_existing_columns
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = 'APP_OWNER'
      AND ((TABLE_NAME = 'REFUND_REQUEST' AND COLUMN_NAME IN ('APPLIED_POLICY_ID','APPLIED_SERVICE_FEE'))
        OR (TABLE_NAME = 'REFUND_ITEM' AND COLUMN_NAME = 'REFUND_BASE_AMOUNT'));
    IF v_existing_columns > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Refund workflow columns already exist');
    END IF;

    SELECT COUNT(*) INTO v_existing_constraints
    FROM ALL_CONSTRAINTS
    WHERE OWNER = 'APP_OWNER'
      AND CONSTRAINT_NAME IN (
          'FK_REFUND_APPLIED_POLICY', 'CHK_REFUND_APPLIED_FEE',
          'CHK_REFUND_ACTUAL_POSITIVE', 'CHK_REFUND_STATE_COMBO',
          'CHK_REFUND_BASE_AMOUNT', 'CHK_REFUND_POLICY_DEADLINE');
    IF v_existing_constraints > 0 THEN
        RAISE_APPLICATION_ERROR(-20006, 'Refund workflow constraints already exist');
    END IF;

    SELECT COUNT(*) INTO v_invalid_rows
    FROM APP_OWNER.REFUND_REQUEST;
    IF v_invalid_rows > 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Existing refund requests require an explicit snapshot backfill');
    END IF;

    SELECT COUNT(*) INTO v_invalid_rows
    FROM APP_OWNER.REFUND_ITEM;
    IF v_invalid_rows > 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'Existing refund items require an explicit base-amount backfill');
    END IF;

    SELECT COUNT(*) INTO v_invalid_rows
    FROM APP_OWNER.REFUND_REQUEST
    WHERE NOT (
        (APPROVE_STATUS = 'PENDING' AND REFUND_STATUS = 'PENDING') OR
        (APPROVE_STATUS = 'APPROVED' AND REFUND_STATUS IN ('PROCESSING','COMPLETED','FAILED')) OR
        (APPROVE_STATUS = 'REJECTED' AND REFUND_STATUS = 'FAILED'))
       OR (ACTUAL_REFUND IS NOT NULL AND ACTUAL_REFUND <= 0);
    IF v_invalid_rows > 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Existing refund rows violate new constraints');
    END IF;

    SELECT COUNT(*) INTO v_invalid_rows
    FROM APP_OWNER.REFUND_POLICY
    WHERE REFUND_DEADLINE_HOUR < 0;
    IF v_invalid_rows > 0 THEN
        RAISE_APPLICATION_ERROR(-20005, 'Existing refund policies have negative deadlines');
    END IF;
END;
/

ALTER TABLE E_TICKET DROP CONSTRAINT CHK_ETICKET_STATUS;
ALTER TABLE E_TICKET ADD CONSTRAINT CHK_ETICKET_STATUS
    CHECK (TICKET_STATUS IN ('UNUSED','REFUNDING','USED','REFUNDED','EXCHANGED'));

ALTER TABLE REFUND_REQUEST ADD (
    APPLIED_POLICY_ID NUMBER(19),
    APPLIED_SERVICE_FEE NUMBER(10,2) DEFAULT 0 NOT NULL
);
ALTER TABLE REFUND_ITEM ADD (
    REFUND_BASE_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL
);

ALTER TABLE REFUND_REQUEST ADD CONSTRAINT FK_REFUND_APPLIED_POLICY
    FOREIGN KEY (APPLIED_POLICY_ID) REFERENCES REFUND_POLICY(POLICY_ID);
CREATE INDEX IDX_REFUND_APPLIED_POLICY ON REFUND_REQUEST(APPLIED_POLICY_ID);
ALTER TABLE REFUND_REQUEST ADD CONSTRAINT CHK_REFUND_APPLIED_FEE
    CHECK (APPLIED_SERVICE_FEE >= 0);
ALTER TABLE REFUND_REQUEST ADD CONSTRAINT CHK_REFUND_ACTUAL_POSITIVE
    CHECK (ACTUAL_REFUND IS NULL OR ACTUAL_REFUND > 0);
ALTER TABLE REFUND_REQUEST ADD CONSTRAINT CHK_REFUND_STATE_COMBO CHECK (
    (APPROVE_STATUS = 'PENDING' AND REFUND_STATUS = 'PENDING') OR
    (APPROVE_STATUS = 'APPROVED' AND REFUND_STATUS IN ('PROCESSING','COMPLETED','FAILED')) OR
    (APPROVE_STATUS = 'REJECTED' AND REFUND_STATUS = 'FAILED')
);
ALTER TABLE REFUND_ITEM ADD CONSTRAINT CHK_REFUND_BASE_AMOUNT
    CHECK (REFUND_BASE_AMOUNT >= 0);
ALTER TABLE REFUND_POLICY ADD CONSTRAINT CHK_REFUND_POLICY_DEADLINE
    CHECK (REFUND_DEADLINE_HOUR >= 0);

COMMENT ON COLUMN REFUND_REQUEST.APPLIED_POLICY_ID IS '申请时命中的退票策略ID';
COMMENT ON COLUMN REFUND_REQUEST.APPLIED_SERVICE_FEE IS '申请时固定服务费快照';
COMMENT ON COLUMN REFUND_ITEM.REFUND_BASE_AMOUNT IS '优惠分摊后的逐项退款基数';

SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, NULLABLE
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'APP_OWNER'
  AND ((TABLE_NAME = 'REFUND_REQUEST' AND COLUMN_NAME IN ('APPLIED_POLICY_ID','APPLIED_SERVICE_FEE'))
    OR (TABLE_NAME = 'REFUND_ITEM' AND COLUMN_NAME = 'REFUND_BASE_AMOUNT'))
ORDER BY TABLE_NAME, COLUMN_NAME;

SELECT CONSTRAINT_NAME, STATUS
FROM ALL_CONSTRAINTS
WHERE OWNER = 'APP_OWNER'
  AND CONSTRAINT_NAME IN (
      'CHK_ETICKET_STATUS','FK_REFUND_APPLIED_POLICY','CHK_REFUND_APPLIED_FEE',
      'CHK_REFUND_ACTUAL_POSITIVE','CHK_REFUND_STATE_COMBO',
      'CHK_REFUND_BASE_AMOUNT','CHK_REFUND_POLICY_DEADLINE')
ORDER BY CONSTRAINT_NAME;

SELECT INDEX_NAME, STATUS
FROM ALL_INDEXES
WHERE OWNER = 'APP_OWNER' AND INDEX_NAME = 'IDX_REFUND_APPLIED_POLICY';
