/*票务订单模块修改*/

SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

/*T_ORDER*/

ALTER TABLE T_ORDER DROP CONSTRAINT CHK_T_ORDER_ACTUAL;

ALTER TABLE T_ORDER DROP COLUMN ACTUAL_AMOUNT;

COMMENT ON COLUMN T_ORDER.ORDER_TYPE IS
    'NORMAL普通 SPLIT拆单 MERGE合单 EXCHANGE改签子订单';


/*E_TICKET*/

DROP INDEX IDX_ETICKET_SESSION_STATUS;

DROP INDEX IDX_ETICKET_SESSION;

ALTER TABLE E_TICKET DROP CONSTRAINT FK_ETICKET_SESSION;

ALTER TABLE E_TICKET DROP COLUMN SESSION_ID;


/*REFUND_REQUEST*/

ALTER TABLE REFUND_REQUEST DROP CONSTRAINT CHK_REFUND_FEE;

ALTER TABLE REFUND_REQUEST DROP COLUMN REFUND_FEE;


/*EXCHANGE_ITEM*/

--删除旧索引
DROP INDEX IDX_EXCHANGE_ITEM_SEAT;
DROP INDEX IDX_EXCHANGE_ITEM_PRICE;

--删除旧外键
ALTER TABLE EXCHANGE_ITEM DROP CONSTRAINT FK_EXCHANGE_ITEM_NEW_SEAT;
ALTER TABLE EXCHANGE_ITEM DROP CONSTRAINT FK_EXCHANGE_ITEM_NEW_PRICE;

--删除旧约束
ALTER TABLE EXCHANGE_ITEM DROP CONSTRAINT CHK_NEW_UNIT_PRICE;

--删除旧列
ALTER TABLE EXCHANGE_ITEM DROP COLUMN NEW_UNIT_PRICE;
ALTER TABLE EXCHANGE_ITEM DROP COLUMN NEW_PRICE_STRATEGY_ID;
ALTER TABLE EXCHANGE_ITEM DROP COLUMN NEW_SEAT_ID;

--添加新列
ALTER TABLE EXCHANGE_ITEM ADD (
    NEW_ORDER_ITEM_ID NUMBER(19) NOT NULL
);

--添加外键
ALTER TABLE EXCHANGE_ITEM
    ADD CONSTRAINT FK_EXCHANGE_ITEM_NEW_ORDER
    FOREIGN KEY (NEW_ORDER_ITEM_ID)
    REFERENCES ORDER_ITEM(ORDER_ITEM_ID);

--添加索引
CREATE INDEX IDX_EXCHANGE_ITEM_NEW_ITEM
    ON EXCHANGE_ITEM(NEW_ORDER_ITEM_ID);

--添加列注释
COMMENT ON COLUMN EXCHANGE_ITEM.NEW_ORDER_ITEM_ID IS '改签后新订单明细ID';


/*更新注释*/

COMMENT ON COLUMN EXCHANGE_REQUEST.ORDER_ID IS
    '关联原订单ID；改签完成后生成改签子订单，子订单 PARENT_ORDER_ID 指向该原订单';
