-- =====================================================================
-- 时间统一规范：存量 Schema 从“会话时区时间(CURRENT_TIMESTAMP)”切到 UTC
-- ---------------------------------------------------------------------
-- 目标：库中所有 TIMESTAMP 均存 UTC，API 输出统一带 Z。
-- 执行条件：
--   1) 使用 DEPLOY_USER（或具备 APP_OWNER DDL 权限的账号）执行；
--   2) 与后端“UTC 序列化”代码一起发布。
-- 注意：历史演示数据为 +08 本地与 UTC 混合，需另行折算/重置后重新生成，
--       本脚本只负责把 Schema 默认值/触发器改为 UTC。
-- =====================================================================

-- 1) 所有 TIMESTAMP 默认值由 CURRENT_TIMESTAMP 改为 UTC
-- （all_tab_columns.data_default 是 LONG，无法在 SQL 中函数比较，故用静态清单）
ALTER TABLE APP_OWNER.CATEGORY MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.DYNAMIC_PRICING_RULE MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.EXCHANGE_ITEM MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.EXCHANGE_POLICY MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.EXCHANGE_REQUEST MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.E_TICKET MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.MARKETING_CONTENT MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.OPERATION_LOG MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.ORDER_ITEM MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.ORG_STRUCTURE MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.PAYMENT MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.PERMISSION MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.PRICE_STRATEGY MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.PURCHASE_LIMIT MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.REFUND_ITEM MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.REFUND_POLICY MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.REFUND_REQUEST MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.ROLE MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.SEAT MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.SEAT_LOCK MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), LOCK_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.SEAT_MAP MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.SEAT_RESERVATION MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), RESERVE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.SEAT_RULE MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.SEAT_RULE_SCOPE MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.SEAT_SECTION MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.SHOW MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.SHOW_SESSION MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.SYS_USER MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.TAG MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.T_ORDER MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), EXPIRE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.T_ORDER_EVENT_OUTBOX MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.USER_BLACKLIST MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), START_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.USER_REAL_NAME MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.USER_SESSION MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), LOGIN_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));
ALTER TABLE APP_OWNER.VENUE MODIFY (CREATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP), UPDATE_TIME DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP));

-- 2) 触发器内 CURRENT_TIMESTAMP 赋值统一改为 UTC
BEGIN
    FOR trg IN (
        SELECT trigger_name
        FROM all_triggers
        WHERE owner = 'APP_OWNER'
          AND status = 'ENABLED'
    ) LOOP
        DECLARE
            v_ddl CLOB;
        BEGIN
            v_ddl := DBMS_METADATA.GET_DDL('TRIGGER', trg.trigger_name, 'APP_OWNER');
            IF v_ddl LIKE '%CURRENT_TIMESTAMP%' THEN
                v_ddl := REPLACE(v_ddl, 'CURRENT_TIMESTAMP', 'SYS_EXTRACT_UTC(SYSTIMESTAMP)');
                EXECUTE IMMEDIATE v_ddl;
            END IF;
        EXCEPTION
            WHEN OTHERS THEN
                NULL; -- 单个触发器重建失败不中断，需人工核对日志
        END;
    END LOOP;
END;
/

-- 3) 提示：执行后建议抽查
-- SELECT trigger_name, status FROM all_triggers WHERE owner='APP_OWNER' ORDER BY 1;
