-- 用于添加新的复合索引

CREATE INDEX IDX_SHOW_SESSION_SHOW_STATUS 
ON SHOW_SESSION (SHOW_ID, SESSION_STATUS, START_TIME);

CREATE INDEX IDX_SHOW_SESSION_SALE_TIME 
ON SHOW_SESSION (SALE_START_TIME, SALE_END_TIME, SESSION_STATUS);
