SET SQLBLANKLINES ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

-- 正式环境仅允许 DEPLOY_USER 修改 APP_OWNER；个人演练仅允许修改自己的 Schema。
DECLARE
    v_session_user VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER'));
    v_owner        VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'));
BEGIN
    IF v_session_user = 'DEPLOY_USER' THEN
        EXECUTE IMMEDIATE 'ALTER SESSION SET CURRENT_SCHEMA = APP_OWNER';
    ELSIF v_session_user <> v_owner OR v_owner = 'APP_OWNER' THEN
        RAISE_APPLICATION_ERROR(-20200, 'Unsupported migration owner');
    END IF;
END;
/

-- 对已存在对象先做 fail-closed 元数据校验，允许完整脚本安全重复执行。
DECLARE
    v_owner VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'));
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM ALL_TABLES
    WHERE OWNER = v_owner AND TABLE_NAME = 'T_ORDER';
    IF v_count <> 1 THEN
        RAISE_APPLICATION_ERROR(-20201, 'T_ORDER is missing');
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = v_owner
      AND TABLE_NAME = 'T_ORDER'
      AND COLUMN_NAME = 'IDEMPOTENCY_KEY';
    IF v_count = 1 THEN
        SELECT COUNT(*) INTO v_count
        FROM ALL_TAB_COLUMNS
        WHERE OWNER = v_owner
          AND TABLE_NAME = 'T_ORDER'
          AND COLUMN_NAME = 'IDEMPOTENCY_KEY'
          AND DATA_TYPE = 'VARCHAR2'
          AND CHAR_LENGTH = 64
          AND CHAR_USED = 'C'
          AND NULLABLE = 'Y';
        IF v_count <> 1 THEN
            RAISE_APPLICATION_ERROR(-20202, 'IDEMPOTENCY_KEY has an unexpected definition');
        END IF;
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = v_owner
      AND TABLE_NAME = 'T_ORDER'
      AND COLUMN_NAME = 'IDEMPOTENCY_REQUEST_HASH';
    IF v_count = 1 THEN
        SELECT COUNT(*) INTO v_count
        FROM ALL_TAB_COLUMNS
        WHERE OWNER = v_owner
          AND TABLE_NAME = 'T_ORDER'
          AND COLUMN_NAME = 'IDEMPOTENCY_REQUEST_HASH'
          AND DATA_TYPE = 'CHAR'
          AND CHAR_LENGTH = 64
          AND CHAR_USED = 'C'
          AND NULLABLE = 'Y';
        IF v_count <> 1 THEN
            RAISE_APPLICATION_ERROR(-20203, 'IDEMPOTENCY_REQUEST_HASH has an unexpected definition');
        END IF;
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM ALL_CONSTRAINTS
    WHERE OWNER = v_owner
      AND TABLE_NAME = 'T_ORDER'
      AND CONSTRAINT_NAME IN (
          'CHK_T_ORDER_IDEMPOTENCY_PAIR',
          'UK_T_ORDER_USER_IDEMPOTENCY');
    IF v_count NOT IN (0, 1, 2) THEN
        RAISE_APPLICATION_ERROR(-20204, 'Idempotency constraint metadata is ambiguous');
    END IF;
END;
/

DECLARE
    v_owner VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'));
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = v_owner
      AND TABLE_NAME = 'T_ORDER'
      AND COLUMN_NAME = 'IDEMPOTENCY_KEY';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE T_ORDER ADD (IDEMPOTENCY_KEY VARCHAR2(64 CHAR))';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = v_owner
      AND TABLE_NAME = 'T_ORDER'
      AND COLUMN_NAME = 'IDEMPOTENCY_REQUEST_HASH';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE T_ORDER ADD (IDEMPOTENCY_REQUEST_HASH CHAR(64 CHAR))';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM ALL_CONSTRAINTS
    WHERE OWNER = v_owner
      AND TABLE_NAME = 'T_ORDER'
      AND CONSTRAINT_NAME = 'CHK_T_ORDER_IDEMPOTENCY_PAIR';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            ALTER TABLE T_ORDER ADD CONSTRAINT CHK_T_ORDER_IDEMPOTENCY_PAIR CHECK (
                (IDEMPOTENCY_KEY IS NULL AND IDEMPOTENCY_REQUEST_HASH IS NULL) OR
                (IDEMPOTENCY_KEY IS NOT NULL AND IDEMPOTENCY_REQUEST_HASH IS NOT NULL)) ENABLE VALIDATE]';
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM ALL_CONSTRAINTS
    WHERE OWNER = v_owner
      AND TABLE_NAME = 'T_ORDER'
      AND CONSTRAINT_NAME = 'UK_T_ORDER_USER_IDEMPOTENCY';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            ALTER TABLE T_ORDER ADD CONSTRAINT UK_T_ORDER_USER_IDEMPOTENCY
            UNIQUE (USER_ID, IDEMPOTENCY_KEY) ENABLE VALIDATE]';
    END IF;

    EXECUTE IMMEDIATE
        'COMMENT ON COLUMN T_ORDER.IDEMPOTENCY_KEY IS ''普通订单创建幂等键（同一用户内唯一）''';
    EXECUTE IMMEDIATE
        'COMMENT ON COLUMN T_ORDER.IDEMPOTENCY_REQUEST_HASH IS ''普通订单创建请求的 SHA-256 摘要''';
END;
/

-- 终态断言：既验证首次迁移，也验证重复执行没有漂移。
DECLARE
    v_owner      VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'));
    v_count      NUMBER;
    v_definition VARCHAR2(4000);
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = v_owner
      AND TABLE_NAME = 'T_ORDER'
      AND ((COLUMN_NAME = 'IDEMPOTENCY_KEY'
            AND DATA_TYPE = 'VARCHAR2' AND CHAR_LENGTH = 64 AND CHAR_USED = 'C' AND NULLABLE = 'Y')
        OR (COLUMN_NAME = 'IDEMPOTENCY_REQUEST_HASH'
            AND DATA_TYPE = 'CHAR' AND CHAR_LENGTH = 64 AND CHAR_USED = 'C' AND NULLABLE = 'Y'));
    IF v_count <> 2 THEN
        RAISE_APPLICATION_ERROR(-20210, 'Order idempotency columns verification failed');
    END IF;

    SELECT REGEXP_REPLACE(UPPER(REPLACE(SEARCH_CONDITION_VC, '"', '')), '[[:space:]]', '')
      INTO v_definition
    FROM ALL_CONSTRAINTS
    WHERE OWNER = v_owner
      AND TABLE_NAME = 'T_ORDER'
      AND CONSTRAINT_NAME = 'CHK_T_ORDER_IDEMPOTENCY_PAIR'
      AND CONSTRAINT_TYPE = 'C';
    IF v_definition <>
       '(IDEMPOTENCY_KEYISNULLANDIDEMPOTENCY_REQUEST_HASHISNULL)OR(IDEMPOTENCY_KEYISNOTNULLANDIDEMPOTENCY_REQUEST_HASHISNOTNULL)' THEN
        RAISE_APPLICATION_ERROR(-20211, 'Idempotency pair constraint verification failed');
    END IF;

    SELECT COUNT(*) INTO v_count
    FROM ALL_CONSTRAINTS c
    WHERE c.OWNER = v_owner
      AND c.TABLE_NAME = 'T_ORDER'
      AND c.CONSTRAINT_NAME = 'UK_T_ORDER_USER_IDEMPOTENCY'
      AND c.CONSTRAINT_TYPE = 'U'
      AND (SELECT COUNT(*)
           FROM ALL_CONS_COLUMNS cc
           WHERE cc.OWNER = c.OWNER
             AND cc.TABLE_NAME = c.TABLE_NAME
             AND cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME) = 2
      AND EXISTS (
          SELECT 1 FROM ALL_CONS_COLUMNS cc
          WHERE cc.OWNER = c.OWNER
            AND cc.TABLE_NAME = c.TABLE_NAME
            AND cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME
            AND cc.POSITION = 1
            AND cc.COLUMN_NAME = 'USER_ID')
      AND EXISTS (
          SELECT 1 FROM ALL_CONS_COLUMNS cc
          WHERE cc.OWNER = c.OWNER
            AND cc.TABLE_NAME = c.TABLE_NAME
            AND cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME
            AND cc.POSITION = 2
            AND cc.COLUMN_NAME = 'IDEMPOTENCY_KEY');
    IF v_count <> 1 THEN
        RAISE_APPLICATION_ERROR(-20212, 'Idempotency uniqueness verification failed');
    END IF;
END;
/

SELECT SYS_CONTEXT('USERENV', 'SESSION_USER') AS SESSION_USER,
       SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS CURRENT_SCHEMA
FROM DUAL;
