-- =====================================================================
-- 触发器显式重建：CREATE_TIME / UPDATE_TIME 等时间赋值改为 UTC
-- 执行：DEPLOY_USER 运行。
-- =====================================================================
CREATE OR REPLACE TRIGGER TRG_BIU_CATEGORY
BEFORE INSERT OR UPDATE ON CATEGORY
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.CATEGORY_ID IS NULL THEN
        SELECT SEQ_CATEGORY.NEXTVAL INTO :NEW.CATEGORY_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_MARKETING_CONTENT
BEFORE INSERT OR UPDATE ON MARKETING_CONTENT
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.CONTENT_ID IS NULL THEN
        SELECT SEQ_MARKETING_CONTENT.NEXTVAL INTO :NEW.CONTENT_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_OPERATION_LOG
BEFORE INSERT OR UPDATE ON OPERATION_LOG
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.LOG_ID IS NULL THEN
        SELECT SEQ_OPERATION_LOG.NEXTVAL INTO :NEW.LOG_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_ORG_STRUCTURE
BEFORE INSERT OR UPDATE ON ORG_STRUCTURE
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.ORG_ID IS NULL THEN
        SELECT SEQ_ORG_STRUCTURE.NEXTVAL INTO :NEW.ORG_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_PERMISSION
BEFORE INSERT OR UPDATE ON PERMISSION
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.PERMISSION_ID IS NULL THEN
        SELECT SEQ_PERMISSION.NEXTVAL INTO :NEW.PERMISSION_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_PRICE_STRATEGY
BEFORE INSERT OR UPDATE ON PRICE_STRATEGY
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.PRICE_STRATEGY_ID IS NULL THEN
        SELECT SEQ_PRICE_STRATEGY.NEXTVAL INTO :NEW.PRICE_STRATEGY_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_PURCHASE_LIMIT
BEFORE INSERT OR UPDATE ON PURCHASE_LIMIT
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.LIMIT_ID IS NULL THEN
        SELECT SEQ_PURCHASE_LIMIT.NEXTVAL INTO :NEW.LIMIT_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_ROLE
BEFORE INSERT OR UPDATE ON ROLE
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.ROLE_ID IS NULL THEN
        SELECT SEQ_ROLE.NEXTVAL INTO :NEW.ROLE_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_SHOW
BEFORE INSERT OR UPDATE ON SHOW
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.SHOW_ID IS NULL THEN
        SELECT SEQ_SHOW.NEXTVAL INTO :NEW.SHOW_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_SHOW_SESSION
BEFORE INSERT OR UPDATE ON SHOW_SESSION
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.SESSION_ID IS NULL THEN
        SELECT SEQ_SHOW_SESSION.NEXTVAL INTO :NEW.SESSION_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_SYS_USER
BEFORE INSERT OR UPDATE ON SYS_USER
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.USER_ID IS NULL THEN
        SELECT SEQ_SYS_USER.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_TAG
BEFORE INSERT OR UPDATE ON TAG
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.TAG_ID IS NULL THEN
        SELECT SEQ_TAG.NEXTVAL INTO :NEW.TAG_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_USER_BLACKLIST
BEFORE INSERT OR UPDATE ON USER_BLACKLIST
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.BLACKLIST_ID IS NULL THEN
        SELECT SEQ_USER_BLACKLIST.NEXTVAL INTO :NEW.BLACKLIST_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_USER_REAL_NAME
BEFORE INSERT OR UPDATE ON USER_REAL_NAME
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.REAL_NAME_ID IS NULL THEN
        SELECT SEQ_USER_REAL_NAME.NEXTVAL INTO :NEW.REAL_NAME_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_USER_SESSION
BEFORE INSERT OR UPDATE ON USER_SESSION
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.USER_SESSION_ID IS NULL THEN
        SELECT SEQ_USER_SESSION.NEXTVAL INTO :NEW.USER_SESSION_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BIU_VENUE
BEFORE INSERT OR UPDATE ON VENUE
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.VENUE_ID IS NULL THEN
        SELECT SEQ_VENUE.NEXTVAL INTO :NEW.VENUE_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_EXCHANGE_ITEM
BEFORE INSERT ON EXCHANGE_ITEM
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_EXCHANGE_POLICY
BEFORE INSERT ON EXCHANGE_POLICY
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_EXCHANGE_REQUEST
BEFORE INSERT ON EXCHANGE_REQUEST
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_E_TICKET
BEFORE INSERT ON E_TICKET
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_ORDER_ITEM
BEFORE INSERT ON ORDER_ITEM
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_PAYMENT
BEFORE INSERT ON PAYMENT
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_REFUND_ITEM
BEFORE INSERT ON REFUND_ITEM
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_REFUND_POLICY
BEFORE INSERT ON REFUND_POLICY
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_REFUND_REQUEST
BEFORE INSERT ON REFUND_REQUEST
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_ROLE_PERMISSION
BEFORE INSERT ON ROLE_PERMISSION
FOR EACH ROW
BEGIN
    IF :NEW.ROLE_PERM_ID IS NULL THEN
        SELECT SEQ_ROLE_PERMISSION.NEXTVAL INTO :NEW.ROLE_PERM_ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SEAT
BEFORE INSERT ON SEAT
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SEAT_LOCK
BEFORE INSERT ON SEAT_LOCK
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SEAT_MAP
BEFORE INSERT ON SEAT_MAP
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SEAT_RESERVATION
BEFORE INSERT ON SEAT_RESERVATION
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SEAT_RULE
BEFORE INSERT ON SEAT_RULE
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SEAT_RULE_SCOPE
BEFORE INSERT ON SEAT_RULE_SCOPE
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SEAT_SECTION
BEFORE INSERT ON SEAT_SECTION
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SHOW_TAG
BEFORE INSERT ON SHOW_TAG
FOR EACH ROW
BEGIN
    IF :NEW.SHOW_TAG_ID IS NULL THEN
        SELECT SEQ_SHOW_TAG.NEXTVAL INTO :NEW.SHOW_TAG_ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_T_ORDER
BEFORE INSERT ON T_ORDER
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_USER_ROLE
BEFORE INSERT ON USER_ROLE
FOR EACH ROW
BEGIN
    IF :NEW.USER_ROLE_ID IS NULL THEN
        SELECT SEQ_USER_ROLE.NEXTVAL INTO :NEW.USER_ROLE_ID FROM DUAL;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_ETICKET_UPDATE
BEFORE UPDATE ON E_TICKET
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_EXCHANGE_ITEM_UPDATE
BEFORE UPDATE ON EXCHANGE_ITEM
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_EXCHANGE_POLICY_UPDATE
BEFORE UPDATE ON EXCHANGE_POLICY
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_EXCHANGE_REQUEST_UPDATE
BEFORE UPDATE ON EXCHANGE_REQUEST
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_ORDER_ITEM_UPDATE
BEFORE UPDATE ON ORDER_ITEM
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_PAYMENT_UPDATE
BEFORE UPDATE ON PAYMENT
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_REFUND_ITEM_UPDATE
BEFORE UPDATE ON REFUND_ITEM
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_REFUND_POLICY_UPDATE
BEFORE UPDATE ON REFUND_POLICY
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_REFUND_REQUEST_UPDATE
BEFORE UPDATE ON REFUND_REQUEST
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_LOCK_UPDATE
BEFORE UPDATE ON SEAT_LOCK
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_MAP_UPDATE
BEFORE UPDATE ON SEAT_MAP
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_RESERVATION_UPDATE
BEFORE UPDATE ON SEAT_RESERVATION
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_RULE_SCOPE_UPDATE
BEFORE UPDATE ON SEAT_RULE_SCOPE
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_RULE_UPDATE
BEFORE UPDATE ON SEAT_RULE
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_SECTION_UPDATE
BEFORE UPDATE ON SEAT_SECTION
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_UPDATE
BEFORE UPDATE ON SEAT
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/

CREATE OR REPLACE TRIGGER TRG_T_ORDER_UPDATE
BEFORE UPDATE ON T_ORDER
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=SYS_EXTRACT_UTC(SYSTIMESTAMP);
END;
/
