SET SQLBLANKLINES ON

/*==============================================================*/
/*  票务系统 — 完整DDL脚本（合并版）                                */
/*                                                              */
/*  来源文件:                                                    */
/*    - user_permission_ddl.sql   用户与权限模块                   */
/*    - Show Session Module_ddl.sql   演出与场次模块                */
/*    - DDL.sql   座位图与选座模块                                  */
/*    - order_ticket_module_ddl.sql   订单与票务模块                */
/*                                                              */
/*  主要修复:                                                    */
/*    1. 移除 Show Session Module 中 SEAT_MAP / SEAT_SECTION      */
/*       的重复定义，统一使用 DDL.sql 中的标准定义                    */
/*    2. 所有外键引用 "USER" 的已改为 "SYS_USER"                    */
/*    3. DDL.sql 中被注释的外键约束已取消注释                         */
/*    4. 合并重复索引名称                                          */
/*    5. SESSION 表重命名为 SHOW_SESSION（避免Oracle保留字冲突）       */
/*    6. 补全 DDL.sql 表缺失的 BEFORE UPDATE 触发器（7张表）            */
/*    7. 为所有 IDENTITY 表创建统一 BEFORE INSERT 触发器（17张表）       */
/*                                                              */
/*  执行顺序: 按表依赖关系从底层到上层排列，确保外键引用的表先创建      */
/*==============================================================*/


/*==============================================================*/
/* 第一部分：用户与权限模块                                        */
/*==============================================================*/

-- 1-1. 组织机构表
CREATE TABLE ORG_STRUCTURE (
    ORG_ID       NUMBER(19) NOT NULL,
    PARENT_ID    NUMBER(19),
    ORG_CODE     VARCHAR2(50 CHAR) NOT NULL,
    ORG_NAME     VARCHAR2(100 CHAR) NOT NULL,
    ORG_TYPE     VARCHAR2(20 CHAR) DEFAULT 'DEPT' NOT NULL,
    SORT_ORDER   NUMBER(5) DEFAULT 0 NOT NULL,
    STATUS       NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY    VARCHAR2(50 CHAR),
    UPDATE_BY    VARCHAR2(50 CHAR),
    CONSTRAINT PK_ORG_STRUCTURE PRIMARY KEY (ORG_ID),
    CONSTRAINT UK_ORG_STRUCTURE_CODE UNIQUE (ORG_CODE),
    CONSTRAINT FK_ORG_STRUCTURE_PARENT FOREIGN KEY (PARENT_ID)
        REFERENCES ORG_STRUCTURE (ORG_ID),
    CONSTRAINT CK_ORG_STRUCTURE_TYPE CHECK (ORG_TYPE IN ('COMPANY', 'DEPT', 'TEAM', 'OTHER')),
    CONSTRAINT CK_ORG_STRUCTURE_STATUS CHECK (STATUS IN (0, 1))
);

CREATE INDEX IDX_ORG_PARENT ON ORG_STRUCTURE (PARENT_ID);

CREATE SEQUENCE SEQ_ORG_STRUCTURE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_ORG_STRUCTURE
BEFORE INSERT OR UPDATE ON ORG_STRUCTURE
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.ORG_ID IS NULL THEN
        SELECT SEQ_ORG_STRUCTURE.NEXTVAL INTO :NEW.ORG_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- 1-2. 系统用户表（原 USER 表重命名为 SYS_USER，避免Oracle保留字冲突）
CREATE TABLE SYS_USER (
    USER_ID        NUMBER(19) NOT NULL,
    USER_NAME      VARCHAR2(50 CHAR) NOT NULL,
    PASSWORD_HASH  VARCHAR2(255 CHAR) NOT NULL,
    NICKNAME       VARCHAR2(50 CHAR),
    PHONE          VARCHAR2(20 CHAR) NOT NULL,
    EMAIL          VARCHAR2(100 CHAR),
    ORG_ID         NUMBER(19),
    USER_TYPE      VARCHAR2(20 CHAR) DEFAULT 'NORMAL' NOT NULL,
    STATUS         NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_SYS_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UK_SYS_USER_NAME UNIQUE (USER_NAME),
    CONSTRAINT UK_SYS_USER_PHONE UNIQUE (PHONE),
    CONSTRAINT UK_SYS_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_SYS_USER_ORG FOREIGN KEY (ORG_ID)
        REFERENCES ORG_STRUCTURE (ORG_ID),
    CONSTRAINT CK_SYS_USER_TYPE CHECK (USER_TYPE IN ('NORMAL', 'MEMBER', 'VIP')),
    CONSTRAINT CK_SYS_USER_STATUS CHECK (STATUS IN (0, 1, 2))
);

CREATE INDEX IDX_SYS_USER_ORG ON SYS_USER (ORG_ID);
CREATE INDEX IDX_SYS_USER_TYPE ON SYS_USER (USER_TYPE);

CREATE SEQUENCE SEQ_SYS_USER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_SYS_USER
BEFORE INSERT OR UPDATE ON SYS_USER
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.USER_ID IS NULL THEN
        SELECT SEQ_SYS_USER.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- 1-3. 角色表
CREATE TABLE ROLE (
    ROLE_ID      NUMBER(19) NOT NULL,
    ROLE_CODE    VARCHAR2(50 CHAR) NOT NULL,
    ROLE_NAME    VARCHAR2(50 CHAR) NOT NULL,
    ROLE_DESC    VARCHAR2(200 CHAR),
    STATUS       NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY    VARCHAR2(50 CHAR),
    UPDATE_BY    VARCHAR2(50 CHAR),
    CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_ID),
    CONSTRAINT UK_ROLE_CODE UNIQUE (ROLE_CODE),
    CONSTRAINT UK_ROLE_NAME UNIQUE (ROLE_NAME),
    CONSTRAINT CK_ROLE_STATUS CHECK (STATUS IN (0, 1))
);

CREATE SEQUENCE SEQ_ROLE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_ROLE
BEFORE INSERT OR UPDATE ON ROLE
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.ROLE_ID IS NULL THEN
        SELECT SEQ_ROLE.NEXTVAL INTO :NEW.ROLE_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- 1-4. 权限表
CREATE TABLE PERMISSION (
    PERMISSION_ID  NUMBER(19) NOT NULL,
    PERM_CODE      VARCHAR2(100 CHAR) NOT NULL,
    PERM_NAME      VARCHAR2(50 CHAR) NOT NULL,
    RESOURCE_TYPE  VARCHAR2(20 CHAR) NOT NULL,
    PARENT_ID      NUMBER(19),
    SORT_ORDER     NUMBER(5) DEFAULT 0 NOT NULL,
    STATUS         NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_PERMISSION PRIMARY KEY (PERMISSION_ID),
    CONSTRAINT UK_PERMISSION_CODE UNIQUE (PERM_CODE),
    CONSTRAINT FK_PERMISSION_PARENT FOREIGN KEY (PARENT_ID)
        REFERENCES PERMISSION (PERMISSION_ID),
    CONSTRAINT CK_PERMISSION_TYPE CHECK (RESOURCE_TYPE IN ('MENU', 'BUTTON', 'API', 'DATA')),
    CONSTRAINT CK_PERMISSION_STATUS CHECK (STATUS IN (0, 1))
);

CREATE INDEX IDX_PERMISSION_PARENT ON PERMISSION (PARENT_ID);

CREATE SEQUENCE SEQ_PERMISSION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_PERMISSION
BEFORE INSERT OR UPDATE ON PERMISSION
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.PERMISSION_ID IS NULL THEN
        SELECT SEQ_PERMISSION.NEXTVAL INTO :NEW.PERMISSION_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- 1-5. 用户角色关联表
CREATE TABLE USER_ROLE (
    USER_ROLE_ID  NUMBER(19) NOT NULL,
    USER_ID       NUMBER(19) NOT NULL,
    ROLE_ID       NUMBER(19) NOT NULL,
    CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ROLE_ID),
    CONSTRAINT UK_USER_ROLE UNIQUE (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER (USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE (ROLE_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_USER_ROLE_ROLE ON USER_ROLE (ROLE_ID);

CREATE SEQUENCE SEQ_USER_ROLE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BI_USER_ROLE
BEFORE INSERT ON USER_ROLE
FOR EACH ROW
BEGIN
    IF :NEW.USER_ROLE_ID IS NULL THEN
        SELECT SEQ_USER_ROLE.NEXTVAL INTO :NEW.USER_ROLE_ID FROM DUAL;
    END IF;
END;
/

-- 1-6. 角色权限关联表
CREATE TABLE ROLE_PERMISSION (
    ROLE_PERM_ID   NUMBER(19) NOT NULL,
    ROLE_ID        NUMBER(19) NOT NULL,
    PERMISSION_ID  NUMBER(19) NOT NULL,
    CONSTRAINT PK_ROLE_PERMISSION PRIMARY KEY (ROLE_PERM_ID),
    CONSTRAINT UK_ROLE_PERMISSION UNIQUE (ROLE_ID, PERMISSION_ID),
    CONSTRAINT FK_RP_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE (ROLE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RP_PERMISSION FOREIGN KEY (PERMISSION_ID)
        REFERENCES PERMISSION (PERMISSION_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_RP_PERMISSION ON ROLE_PERMISSION (PERMISSION_ID);

CREATE SEQUENCE SEQ_ROLE_PERMISSION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BI_ROLE_PERMISSION
BEFORE INSERT ON ROLE_PERMISSION
FOR EACH ROW
BEGIN
    IF :NEW.ROLE_PERM_ID IS NULL THEN
        SELECT SEQ_ROLE_PERMISSION.NEXTVAL INTO :NEW.ROLE_PERM_ID FROM DUAL;
    END IF;
END;
/


/*==============================================================*/
/* 第二部分：演出与场次模块（基础表）                                */
/*==============================================================*/

-- 2-1. 演出分类表（需先于SHOW创建，因SHOW引用CATEGORY）
CREATE TABLE CATEGORY (
    CATEGORY_ID    NUMBER(19) NOT NULL,
    CATEGORY_NAME  VARCHAR2(50 CHAR) NOT NULL,
    PARENT_ID      NUMBER(19),
    SORT_ORDER     NUMBER(5) DEFAULT 0 NOT NULL,
    STATUS         NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT UK_CATEGORY_NAME UNIQUE (CATEGORY_NAME),
    CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENT_ID)
        REFERENCES CATEGORY (CATEGORY_ID),
    CONSTRAINT CK_CATEGORY_STATUS CHECK (STATUS IN (0, 1))
);

CREATE INDEX IDX_CATEGORY_PARENT ON CATEGORY (PARENT_ID);

CREATE SEQUENCE SEQ_CATEGORY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_CATEGORY
BEFORE INSERT OR UPDATE ON CATEGORY
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.CATEGORY_ID IS NULL THEN
        SELECT SEQ_CATEGORY.NEXTVAL INTO :NEW.CATEGORY_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- 2-2. 标签表
CREATE TABLE TAG (
    TAG_ID         NUMBER(19) NOT NULL,
    TAG_NAME       VARCHAR2(50 CHAR) NOT NULL,
    COLOR          VARCHAR2(20 CHAR),
    STATUS         NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_TAG PRIMARY KEY (TAG_ID),
    CONSTRAINT UK_TAG_NAME UNIQUE (TAG_NAME),
    CONSTRAINT CK_TAG_STATUS CHECK (STATUS IN (0, 1))
);

CREATE SEQUENCE SEQ_TAG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_TAG
BEFORE INSERT OR UPDATE ON TAG
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.TAG_ID IS NULL THEN
        SELECT SEQ_TAG.NEXTVAL INTO :NEW.TAG_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- 2-3. 演出主表
CREATE TABLE SHOW (
    SHOW_ID        NUMBER(19) NOT NULL,
    SHOW_NAME      VARCHAR2(200 CHAR) NOT NULL,
    CATEGORY_ID    NUMBER(19) NOT NULL,
    DESCRIPTION    VARCHAR2(2000 CHAR),
    DURATION_MINUTES NUMBER(5),
    POSTER_URL     VARCHAR2(500 CHAR),
    STATUS         VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    AUDIT_STATUS   VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    AUDIT_BY       VARCHAR2(50 CHAR),
    AUDIT_TIME     TIMESTAMP(6),
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_SHOW PRIMARY KEY (SHOW_ID),
    CONSTRAINT FK_SHOW_CATEGORY FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORY (CATEGORY_ID),
    CONSTRAINT CK_SHOW_STATUS CHECK (STATUS IN ('DRAFT', 'PUBLISHED', 'UNPUBLISHED')),
    CONSTRAINT CK_SHOW_AUDIT CHECK (AUDIT_STATUS IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX IDX_SHOW_CATEGORY ON SHOW (CATEGORY_ID);
CREATE INDEX IDX_SHOW_STATUS ON SHOW (STATUS);
CREATE INDEX IDX_SHOW_AUDIT ON SHOW (AUDIT_STATUS);

CREATE SEQUENCE SEQ_SHOW START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_SHOW
BEFORE INSERT OR UPDATE ON SHOW
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.SHOW_ID IS NULL THEN
        SELECT SEQ_SHOW.NEXTVAL INTO :NEW.SHOW_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- 2-4. 演出标签关联表
CREATE TABLE SHOW_TAG (
    SHOW_TAG_ID    NUMBER(19) NOT NULL,
    SHOW_ID        NUMBER(19) NOT NULL,
    TAG_ID         NUMBER(19) NOT NULL,
    CONSTRAINT PK_SHOW_TAG PRIMARY KEY (SHOW_TAG_ID),
    CONSTRAINT UK_SHOW_TAG UNIQUE (SHOW_ID, TAG_ID),
    CONSTRAINT FK_SHOW_TAG_SHOW FOREIGN KEY (SHOW_ID)
        REFERENCES SHOW (SHOW_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SHOW_TAG_TAG FOREIGN KEY (TAG_ID)
        REFERENCES TAG (TAG_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_SHOW_TAG_TAG ON SHOW_TAG (TAG_ID);

CREATE SEQUENCE SEQ_SHOW_TAG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BI_SHOW_TAG
BEFORE INSERT ON SHOW_TAG
FOR EACH ROW
BEGIN
    IF :NEW.SHOW_TAG_ID IS NULL THEN
        SELECT SEQ_SHOW_TAG.NEXTVAL INTO :NEW.SHOW_TAG_ID FROM DUAL;
    END IF;
END;
/

-- 2-5. 场馆表
CREATE TABLE VENUE (
    VENUE_ID       NUMBER(19) NOT NULL,
    VENUE_NAME     VARCHAR2(100 CHAR) NOT NULL,
    ADDRESS        VARCHAR2(200 CHAR),
    CONTACT_PHONE  VARCHAR2(20 CHAR),
    STATUS         VARCHAR2(20 CHAR) DEFAULT 'ENABLED' NOT NULL,
    REMARK         VARCHAR2(255 CHAR),
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_VENUE PRIMARY KEY (VENUE_ID),
    CONSTRAINT UK_VENUE_NAME UNIQUE (VENUE_NAME),
    CONSTRAINT CK_VENUE_STATUS CHECK (STATUS IN ('ENABLED', 'DISABLED'))
);

CREATE SEQUENCE SEQ_VENUE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_VENUE
BEFORE INSERT OR UPDATE ON VENUE
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.VENUE_ID IS NULL THEN
        SELECT SEQ_VENUE.NEXTVAL INTO :NEW.VENUE_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/


/*==============================================================*/
/* 第三部分：座位图与选座模块（DDL.sql 标准定义）                     */
/*==============================================================*/

-- 3-1. 座位主图表（DDL.sql 标准定义，包含 MAP_CODE / MAP_VERSION / IS_DEFAULT 等完整字段）
CREATE TABLE SEAT_MAP (
    SEAT_MAP_ID     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    VENUE_ID        NUMBER(19) NOT NULL,
    MAP_CODE        VARCHAR2(50 CHAR) NOT NULL,
    MAP_NAME        VARCHAR2(100 CHAR) NOT NULL,
    MAP_VERSION     VARCHAR2(20 CHAR) DEFAULT 'V1' NOT NULL,
    IS_DEFAULT      CHAR(1) DEFAULT 'N' NOT NULL,
    MAP_WIDTH       NUMBER(10,2),
    MAP_HEIGHT      NUMBER(10,2),
    MAP_STATUS      VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    REMARK          VARCHAR2(255 CHAR),
    CREATE_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY       VARCHAR2(50 CHAR),
    UPDATE_BY       VARCHAR2(50 CHAR),

    CONSTRAINT PK_SEAT_MAP PRIMARY KEY (SEAT_MAP_ID),
    CONSTRAINT UK_SEAT_MAP_VENUE_CODE UNIQUE (VENUE_ID, MAP_CODE),
    CONSTRAINT FK_SEAT_MAP_VENUE FOREIGN KEY (VENUE_ID) REFERENCES VENUE(VENUE_ID),
    CONSTRAINT CK_SEAT_MAP_DEFAULT CHECK (IS_DEFAULT IN ('Y', 'N')),
    CONSTRAINT CK_SEAT_MAP_STATUS CHECK (MAP_STATUS IN ('DRAFT', 'ENABLED', 'DISABLED')),
    CONSTRAINT CK_SEAT_MAP_SIZE CHECK ( (MAP_WIDTH IS NULL OR MAP_WIDTH > 0) AND (MAP_HEIGHT IS NULL OR MAP_HEIGHT > 0))
);

-- 同一场馆只能有一张默认座位图
CREATE UNIQUE INDEX UK_SEAT_MAP_DEFAULT ON SEAT_MAP(VENUE_ID, CASE WHEN IS_DEFAULT='Y' THEN 1 END);

-- 3-2. 座位分区表（DDL.sql 标准定义，包含 SECTION_TYPE / SECTION_COLOR / FLOOR_NO / IS_SELLABLE 等完整字段）
CREATE TABLE SEAT_SECTION (
    SEAT_SECTION_ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    SEAT_MAP_ID     NUMBER(19) NOT NULL,
    SECTION_CODE    VARCHAR2(30 CHAR) NOT NULL,
    SECTION_NAME    VARCHAR2(100 CHAR) NOT NULL,
    SECTION_TYPE    VARCHAR2(20 CHAR) DEFAULT 'NORMAL' NOT NULL,
    SECTION_COLOR   VARCHAR2(20 CHAR),
    FLOOR_NO        VARCHAR2(20 CHAR),
    IS_SELLABLE     CHAR(1) DEFAULT 'Y' NOT NULL,
    DISPLAY_ORDER   NUMBER(5) DEFAULT 0 NOT NULL,
    REMARK          VARCHAR2(255 CHAR),
    CREATE_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY       VARCHAR2(50 CHAR),
    UPDATE_BY       VARCHAR2(50 CHAR),

    CONSTRAINT PK_SEAT_SECTION PRIMARY KEY (SEAT_SECTION_ID),
    CONSTRAINT FK_SEAT_SECTION_MAP FOREIGN KEY (SEAT_MAP_ID) REFERENCES SEAT_MAP(SEAT_MAP_ID),
    CONSTRAINT UK_SEAT_SECTION_MAP_CODE UNIQUE (SEAT_MAP_ID, SECTION_CODE),
    CONSTRAINT CK_SEAT_SECTION_TYPE CHECK (SECTION_TYPE IN ('NORMAL', 'VIP', 'ACCESSIBLE', 'STANDING')),
    CONSTRAINT CK_SEAT_SECTION_SELLABLE CHECK (IS_SELLABLE IN ('Y', 'N')),
    CONSTRAINT CK_SEAT_SECTION_DISPLAY_ORDER CHECK (DISPLAY_ORDER >= 0)
);

-- 3-3. 具体座位表
CREATE TABLE SEAT (
    SEAT_ID          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    SEAT_SECTION_ID  NUMBER(19) NOT NULL,
    ROW_CODE         VARCHAR2(20 CHAR) NOT NULL,
    SEAT_NO          VARCHAR2(20 CHAR) NOT NULL,
    ROW_INDEX        NUMBER(5) NOT NULL,
    COL_INDEX        NUMBER(5) NOT NULL,
    X_COORD          NUMBER(10,2) DEFAULT 0 NOT NULL,
    Y_COORD          NUMBER(10,2) DEFAULT 0 NOT NULL,
    SEAT_TYPE        VARCHAR2(20 CHAR) DEFAULT 'NORMAL' NOT NULL,
    SEAT_STATUS      VARCHAR2(20 CHAR) DEFAULT 'ENABLED' NOT NULL,
    IS_AISLE_SIDE    CHAR(1) DEFAULT 'N' NOT NULL,
    IS_SELLABLE      CHAR(1) DEFAULT 'Y' NOT NULL,
    REMARK           VARCHAR2(255 CHAR),
    CREATE_TIME      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY        VARCHAR2(50 CHAR),
    UPDATE_BY        VARCHAR2(50 CHAR),

    CONSTRAINT PK_SEAT PRIMARY KEY (SEAT_ID),
    CONSTRAINT FK_SEAT_SECTION FOREIGN KEY (SEAT_SECTION_ID) REFERENCES SEAT_SECTION(SEAT_SECTION_ID),
    CONSTRAINT UK_SEAT_ROW_NO UNIQUE (SEAT_SECTION_ID, ROW_CODE, SEAT_NO),
    CONSTRAINT UK_SEAT_POSITION UNIQUE (SEAT_SECTION_ID, ROW_INDEX, COL_INDEX),
    CONSTRAINT CK_SEAT_TYPE CHECK (SEAT_TYPE IN ('NORMAL', 'COUPLE', 'ACCESSIBLE', 'COMPANION')),
    CONSTRAINT CK_SEAT_STATUS CHECK (SEAT_STATUS IN ('ENABLED', 'DISABLED', 'MAINTENANCE')),
    CONSTRAINT CK_SEAT_AISLE_SIDE CHECK (IS_AISLE_SIDE IN ('Y', 'N')),
    CONSTRAINT CK_SEAT_SELLABLE CHECK (IS_SELLABLE IN ('Y', 'N')),
    CONSTRAINT CK_SEAT_INDEX CHECK (ROW_INDEX >= 0 AND COL_INDEX >= 0)
);


/*==============================================================*/
/* 第四部分：场次与票价模块                                        */
/*==============================================================*/

-- 4-1. 场次表
CREATE TABLE SHOW_SESSION (
    SESSION_ID      NUMBER(19) NOT NULL,
    SHOW_ID         NUMBER(19) NOT NULL,
    SEAT_MAP_ID     NUMBER(19) NOT NULL,
    START_TIME      TIMESTAMP(6) NOT NULL,
    END_TIME        TIMESTAMP(6) NOT NULL,
    SALE_START_TIME TIMESTAMP(6) NOT NULL,
    SALE_END_TIME   TIMESTAMP(6) NOT NULL,
    SESSION_STATUS  VARCHAR2(20 CHAR) DEFAULT 'UPCOMING' NOT NULL,
    CREATE_TIME     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY       VARCHAR2(50 CHAR),
    UPDATE_BY       VARCHAR2(50 CHAR),
    CONSTRAINT PK_SHOW_SESSION PRIMARY KEY (SESSION_ID),
    CONSTRAINT FK_SHOW_SESSION_SHOW FOREIGN KEY (SHOW_ID)
        REFERENCES SHOW (SHOW_ID),
    CONSTRAINT FK_SHOW_SESSION_SEAT_MAP FOREIGN KEY (SEAT_MAP_ID)
        REFERENCES SEAT_MAP (SEAT_MAP_ID),
    CONSTRAINT CK_SHOW_SESSION_STATUS CHECK (SESSION_STATUS IN ('UPCOMING', 'PRESALE', 'ONSALE', 'SOLD_OUT', 'ENDED')),
    CONSTRAINT CK_SHOW_SESSION_TIME CHECK (START_TIME < END_TIME AND SALE_START_TIME < SALE_END_TIME)
);

CREATE INDEX IDX_SHOW_SESSION_SHOW ON SHOW_SESSION (SHOW_ID);
CREATE INDEX IDX_SHOW_SESSION_SEAT_MAP ON SHOW_SESSION (SEAT_MAP_ID);
CREATE INDEX IDX_SHOW_SESSION_STATUS ON SHOW_SESSION (SESSION_STATUS);
CREATE INDEX IDX_SHOW_SESSION_START ON SHOW_SESSION (START_TIME);

CREATE SEQUENCE SEQ_SHOW_SESSION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_SHOW_SESSION
BEFORE INSERT OR UPDATE ON SHOW_SESSION
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.SESSION_ID IS NULL THEN
        SELECT SEQ_SHOW_SESSION.NEXTVAL INTO :NEW.SESSION_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- 4-2. 票价策略表
CREATE TABLE PRICE_STRATEGY (
    PRICE_STRATEGY_ID NUMBER(19) NOT NULL,
    SESSION_ID        NUMBER(19) NOT NULL,
    SEAT_SECTION_ID   NUMBER(19) NOT NULL,
    STRATEGY_NAME     VARCHAR2(100 CHAR) NOT NULL,
    PRICE_TYPE        VARCHAR2(20 CHAR) DEFAULT 'STANDARD' NOT NULL,
    PRICE             NUMBER(10,2) NOT NULL,
    SALE_START_TIME   TIMESTAMP(6) NOT NULL,
    SALE_END_TIME     TIMESTAMP(6) NOT NULL,
    PRIORITY          NUMBER(5) DEFAULT 0 NOT NULL,
    QUOTA             NUMBER(10),
    STATUS            VARCHAR2(20 CHAR) DEFAULT 'ENABLED' NOT NULL,
    CREATE_TIME       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY         VARCHAR2(50 CHAR),
    UPDATE_BY         VARCHAR2(50 CHAR),
    CONSTRAINT PK_PRICE_STRATEGY PRIMARY KEY (PRICE_STRATEGY_ID),
    CONSTRAINT FK_PRICE_SESSION FOREIGN KEY (SESSION_ID)
        REFERENCES SHOW_SESSION (SESSION_ID),
    CONSTRAINT FK_PRICE_SEAT_SECTION FOREIGN KEY (SEAT_SECTION_ID)
        REFERENCES SEAT_SECTION (SEAT_SECTION_ID),
    CONSTRAINT CK_PRICE_TYPE CHECK (PRICE_TYPE IN ('EARLY_BIRD', 'PRESALE', 'STANDARD', 'VIP', 'MEMBER')),
    CONSTRAINT CK_PRICE_STATUS CHECK (STATUS IN ('ENABLED', 'DISABLED')),
    CONSTRAINT CK_PRICE_VALUE CHECK (PRICE >= 0)
);

CREATE INDEX IDX_PRICE_SESSION ON PRICE_STRATEGY (SESSION_ID);
CREATE INDEX IDX_PRICE_SECTION ON PRICE_STRATEGY (SEAT_SECTION_ID);

CREATE SEQUENCE SEQ_PRICE_STRATEGY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_PRICE_STRATEGY
BEFORE INSERT OR UPDATE ON PRICE_STRATEGY
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.PRICE_STRATEGY_ID IS NULL THEN
        SELECT SEQ_PRICE_STRATEGY.NEXTVAL INTO :NEW.PRICE_STRATEGY_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- 4-3. 限购规则表
CREATE TABLE PURCHASE_LIMIT (
    LIMIT_ID        NUMBER(19) NOT NULL,
    LIMIT_NAME      VARCHAR2(100 CHAR) NOT NULL,
    SHOW_ID         NUMBER(19),
    SESSION_ID      NUMBER(19),
    CHANNEL         VARCHAR2(20 CHAR),
    USER_TYPE       VARCHAR2(20 CHAR),
    MAX_BUY_COUNT   NUMBER(5) NOT NULL,
    LIMIT_TYPE      VARCHAR2(20 CHAR) DEFAULT 'TICKET' NOT NULL,
    START_TIME      TIMESTAMP(6),
    END_TIME        TIMESTAMP(6),
    STATUS          VARCHAR2(20 CHAR) DEFAULT 'ENABLED' NOT NULL,
    CREATE_TIME     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY       VARCHAR2(50 CHAR),
    UPDATE_BY       VARCHAR2(50 CHAR),
    CONSTRAINT PK_PURCHASE_LIMIT PRIMARY KEY (LIMIT_ID),
    CONSTRAINT FK_LIMIT_SHOW FOREIGN KEY (SHOW_ID)
        REFERENCES SHOW (SHOW_ID),
    CONSTRAINT FK_LIMIT_SESSION FOREIGN KEY (SESSION_ID)
        REFERENCES SHOW_SESSION (SESSION_ID),
    CONSTRAINT CK_LIMIT_CHANNEL CHECK (CHANNEL IN ('WEB', 'APP', 'MINI_PROGRAM')),
    CONSTRAINT CK_LIMIT_USER_TYPE CHECK (USER_TYPE IN ('NORMAL', 'MEMBER', 'VIP')),
    CONSTRAINT CK_LIMIT_TYPE CHECK (LIMIT_TYPE IN ('TICKET', 'ORDER')),
    CONSTRAINT CK_LIMIT_STATUS CHECK (STATUS IN ('ENABLED', 'DISABLED'))
);

CREATE INDEX IDX_LIMIT_SHOW ON PURCHASE_LIMIT (SHOW_ID);
CREATE INDEX IDX_LIMIT_SESSION ON PURCHASE_LIMIT (SESSION_ID);

CREATE SEQUENCE SEQ_PURCHASE_LIMIT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_PURCHASE_LIMIT
BEFORE INSERT OR UPDATE ON PURCHASE_LIMIT
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.LIMIT_ID IS NULL THEN
        SELECT SEQ_PURCHASE_LIMIT.NEXTVAL INTO :NEW.LIMIT_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- 4-4. 营销内容表
CREATE TABLE MARKETING_CONTENT (
    CONTENT_ID     NUMBER(19) NOT NULL,
    SHOW_ID        NUMBER(19) NOT NULL,
    CONTENT_TYPE   VARCHAR2(20 CHAR) DEFAULT 'NOTICE' NOT NULL,
    TITLE          VARCHAR2(200 CHAR) NOT NULL,
    CONTENT_TEXT   CLOB,
    IMAGE_URL      VARCHAR2(500 CHAR),
    SORT_ORDER     NUMBER(5) DEFAULT 0 NOT NULL,
    STATUS         VARCHAR2(20 CHAR) DEFAULT 'ENABLED' NOT NULL,
    PUBLISH_TIME   TIMESTAMP(6),
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_MARKETING_CONTENT PRIMARY KEY (CONTENT_ID),
    CONSTRAINT FK_MARKETING_SHOW FOREIGN KEY (SHOW_ID)
        REFERENCES SHOW (SHOW_ID),
    CONSTRAINT CK_MARKETING_TYPE CHECK (CONTENT_TYPE IN ('NOTICE', 'AD', 'PROMOTION')),
    CONSTRAINT CK_MARKETING_STATUS CHECK (STATUS IN ('ENABLED', 'DISABLED'))
);

CREATE INDEX IDX_MARKETING_SHOW ON MARKETING_CONTENT (SHOW_ID);
CREATE INDEX IDX_MARKETING_STATUS ON MARKETING_CONTENT (STATUS);

CREATE SEQUENCE SEQ_MARKETING_CONTENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_MARKETING_CONTENT
BEFORE INSERT OR UPDATE ON MARKETING_CONTENT
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.CONTENT_ID IS NULL THEN
        SELECT SEQ_MARKETING_CONTENT.NEXTVAL INTO :NEW.CONTENT_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/


/*==============================================================*/
/* 第五部分：用户安全与审计模块                                    */
/*==============================================================*/

-- 5-1. 用户黑名单表
CREATE TABLE USER_BLACKLIST (
    BLACKLIST_ID  NUMBER(19) NOT NULL,
    USER_ID       NUMBER(19) NOT NULL,
    SHOW_ID       NUMBER(19),
    RISK_TYPE     VARCHAR2(30 CHAR) NOT NULL,
    RISK_SCORE    NUMBER(5) DEFAULT 0 NOT NULL,
    START_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    END_TIME      TIMESTAMP(6),
    IS_PERMANENT  NUMBER(1) DEFAULT 0 NOT NULL,
    REASON        VARCHAR2(200 CHAR),
    STATUS        NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY     VARCHAR2(50 CHAR),
    UPDATE_BY     VARCHAR2(50 CHAR),
    CONSTRAINT PK_USER_BLACKLIST PRIMARY KEY (BLACKLIST_ID),
    CONSTRAINT FK_BLACKLIST_USER FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER (USER_ID),
    CONSTRAINT FK_BLACKLIST_SHOW FOREIGN KEY (SHOW_ID)
        REFERENCES SHOW (SHOW_ID),
    CONSTRAINT CK_BLACKLIST_RISK_SCORE CHECK (RISK_SCORE BETWEEN 0 AND 100),
    CONSTRAINT CK_BLACKLIST_PERMANENT CHECK (IS_PERMANENT IN (0, 1)),
    CONSTRAINT CK_BLACKLIST_STATUS CHECK (STATUS IN (0, 1)),
    CONSTRAINT CK_BLACKLIST_TIME CHECK (END_TIME IS NULL OR END_TIME >= START_TIME)
);

CREATE INDEX IDX_BLACKLIST_USER ON USER_BLACKLIST (USER_ID);
CREATE INDEX IDX_BLACKLIST_SHOW ON USER_BLACKLIST (SHOW_ID);
CREATE INDEX IDX_BLACKLIST_STATUS ON USER_BLACKLIST (STATUS);

CREATE SEQUENCE SEQ_USER_BLACKLIST START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_USER_BLACKLIST
BEFORE INSERT OR UPDATE ON USER_BLACKLIST
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.BLACKLIST_ID IS NULL THEN
        SELECT SEQ_USER_BLACKLIST.NEXTVAL INTO :NEW.BLACKLIST_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- 5-2. 用户实名信息表
CREATE TABLE USER_REAL_NAME (
    REAL_NAME_ID  NUMBER(19) NOT NULL,
    USER_ID       NUMBER(19) NOT NULL,
    REAL_NAME     VARCHAR2(50 CHAR) NOT NULL,
    ID_CARD_NO    VARCHAR2(255 CHAR) NOT NULL,
    IS_DEFAULT    NUMBER(1) DEFAULT 0 NOT NULL,
    IS_VERIFIED   NUMBER(1) DEFAULT 0 NOT NULL,
    CREATE_TIME   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY     VARCHAR2(50 CHAR),
    UPDATE_BY     VARCHAR2(50 CHAR),
    CONSTRAINT PK_USER_REAL_NAME PRIMARY KEY (REAL_NAME_ID),
    CONSTRAINT FK_REAL_NAME_USER FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER (USER_ID),
    CONSTRAINT CK_REAL_NAME_DEFAULT CHECK (IS_DEFAULT IN (0, 1)),
    CONSTRAINT CK_REAL_NAME_VERIFIED CHECK (IS_VERIFIED IN (0, 1))
);

CREATE INDEX IDX_REAL_NAME_USER ON USER_REAL_NAME (USER_ID);
CREATE UNIQUE INDEX UK_REAL_NAME_DEFAULT
    ON USER_REAL_NAME (CASE WHEN IS_DEFAULT = 1 THEN USER_ID END);

CREATE SEQUENCE SEQ_USER_REAL_NAME START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_USER_REAL_NAME
BEFORE INSERT OR UPDATE ON USER_REAL_NAME
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.REAL_NAME_ID IS NULL THEN
        SELECT SEQ_USER_REAL_NAME.NEXTVAL INTO :NEW.REAL_NAME_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- 5-3. 操作日志表
CREATE TABLE OPERATION_LOG (
    LOG_ID            NUMBER(19) NOT NULL,
    USER_ID           NUMBER(19),
    USER_NAME         VARCHAR2(50 CHAR),
    SHOW_ID           NUMBER(19),
    OPERATION_MODULE  VARCHAR2(50 CHAR) NOT NULL,
    OPERATION_TYPE    VARCHAR2(30 CHAR) NOT NULL,
    REQUEST_URL       VARCHAR2(500 CHAR),
    REQUEST_PARAMS    CLOB,
    RESPONSE_RESULT   CLOB,
    IP_ADDRESS        VARCHAR2(50 CHAR),
    USER_AGENT        VARCHAR2(500 CHAR),
    COST_TIME         NUMBER(10),
    STATUS            NUMBER(1) DEFAULT 1 NOT NULL,
    ERROR_MSG         VARCHAR2(500 CHAR),
    CREATE_TIME       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY         VARCHAR2(50 CHAR),
    UPDATE_BY         VARCHAR2(50 CHAR),
    CONSTRAINT PK_OPERATION_LOG PRIMARY KEY (LOG_ID),
    CONSTRAINT FK_OP_LOG_USER FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER (USER_ID),
    CONSTRAINT FK_OP_LOG_SHOW FOREIGN KEY (SHOW_ID)
        REFERENCES SHOW (SHOW_ID),
    CONSTRAINT CK_OP_LOG_STATUS CHECK (STATUS IN (0, 1))
);

CREATE INDEX IDX_OP_LOG_USER ON OPERATION_LOG (USER_ID);
CREATE INDEX IDX_OP_LOG_SHOW ON OPERATION_LOG (SHOW_ID);
CREATE INDEX IDX_OP_LOG_TIME ON OPERATION_LOG (CREATE_TIME);
CREATE INDEX IDX_OP_LOG_TYPE ON OPERATION_LOG (OPERATION_TYPE);

CREATE SEQUENCE SEQ_OPERATION_LOG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_OPERATION_LOG
BEFORE INSERT OR UPDATE ON OPERATION_LOG
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.LOG_ID IS NULL THEN
        SELECT SEQ_OPERATION_LOG.NEXTVAL INTO :NEW.LOG_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

-- 5-4. 用户会话表
CREATE TABLE USER_SESSION (
    USER_SESSION_ID  NUMBER(19) NOT NULL,
    USER_ID          NUMBER(19) NOT NULL,
    SESSION_TOKEN    VARCHAR2(128 CHAR) NOT NULL,
    LOGIN_TIME       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EXPIRE_TIME      TIMESTAMP(6) NOT NULL,
    LOGOUT_TIME      TIMESTAMP(6),
    IP_ADDRESS       VARCHAR2(50 CHAR),
    USER_AGENT       VARCHAR2(500 CHAR),
    RISK_FLAG        NUMBER(1) DEFAULT 0 NOT NULL,
    STATUS           VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATE_TIME      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY        VARCHAR2(50 CHAR),
    UPDATE_BY        VARCHAR2(50 CHAR),
    CONSTRAINT PK_USER_SESSION PRIMARY KEY (USER_SESSION_ID),
    CONSTRAINT UK_USER_SESSION_TOKEN UNIQUE (SESSION_TOKEN),
    CONSTRAINT FK_USER_SESSION_USER FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER (USER_ID),
    CONSTRAINT CK_USER_SESSION_STATUS CHECK (STATUS IN ('ACTIVE', 'EXPIRED', 'LOGOUT', 'LOCKED')),
    CONSTRAINT CK_USER_SESSION_RISK CHECK (RISK_FLAG IN (0, 1))
);

CREATE INDEX IDX_USER_SESSION_USER ON USER_SESSION (USER_ID);
CREATE INDEX IDX_USER_SESSION_EXPIRE ON USER_SESSION (EXPIRE_TIME);
CREATE INDEX IDX_USER_SESSION_STATUS ON USER_SESSION (STATUS);

CREATE SEQUENCE SEQ_USER_SESSION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_USER_SESSION
BEFORE INSERT OR UPDATE ON USER_SESSION
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.USER_SESSION_ID IS NULL THEN
        SELECT SEQ_USER_SESSION.NEXTVAL INTO :NEW.USER_SESSION_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/


/*==============================================================*/
/* 第六部分：订单模块                                              */
/*==============================================================*/

-- 6-1. 订单主表
CREATE TABLE T_ORDER
(
    ORDER_ID            NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_T_ORDER PRIMARY KEY,

    ORDER_NO            VARCHAR2(30 CHAR) NOT NULL,

    USER_ID             NUMBER(19) NOT NULL,

    SESSION_ID          NUMBER(19) NOT NULL,

    ORDER_TYPE          VARCHAR2(20 CHAR)
        DEFAULT 'NORMAL' NOT NULL,

    PARENT_ORDER_ID     NUMBER(19),

    TOTAL_AMOUNT        NUMBER(12,2)
        DEFAULT 0 NOT NULL,

    DISCOUNT_AMOUNT     NUMBER(12,2)
        DEFAULT 0 NOT NULL,

    ACTUAL_AMOUNT       NUMBER(12,2)
        DEFAULT 0 NOT NULL,

    TICKET_COUNT        NUMBER(5)
        DEFAULT 1 NOT NULL,

    ORDER_STATUS        VARCHAR2(20 CHAR)
        DEFAULT 'PENDING_PAY' NOT NULL,

    EXPIRE_TIME         TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    PAY_TIME            TIMESTAMP,

    ISSUE_TIME          TIMESTAMP,

    CANCEL_TIME         TIMESTAMP,

    SOURCE              VARCHAR2(20 CHAR)
        DEFAULT 'WEB' NOT NULL,

    IP_ADDRESS          VARCHAR2(50 CHAR),

    REMARK              VARCHAR2(500 CHAR),

    CREATE_TIME         TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    UPDATE_TIME         TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CREATE_BY           VARCHAR2(50 CHAR),

    UPDATE_BY           VARCHAR2(50 CHAR),

    CONSTRAINT UK_T_ORDER_NO
        UNIQUE(ORDER_NO),

    CONSTRAINT CHK_T_ORDER_TYPE
        CHECK
        (
            ORDER_TYPE IN
            (
                'NORMAL',
                'SPLIT',
                'MERGE',
                'EXCHANGE'
            )
        ),

    CONSTRAINT CHK_T_ORDER_STATUS
        CHECK
        (
            ORDER_STATUS IN
            (
                'PENDING_PAY',
                'PAID',
                'ISSUED',
                'PART_REFUND',
                'REFUNDED',
                'CANCELLED'
            )
        ),

    CONSTRAINT CHK_T_ORDER_TOTAL
        CHECK(TOTAL_AMOUNT>=0),

    CONSTRAINT CHK_T_ORDER_DISCOUNT
        CHECK(DISCOUNT_AMOUNT>=0),

    CONSTRAINT CHK_T_ORDER_ACTUAL
        CHECK(ACTUAL_AMOUNT>=0),

    CONSTRAINT CHK_T_ORDER_COUNT
        CHECK(TICKET_COUNT>0),

    CONSTRAINT FK_T_ORDER_USER
        FOREIGN KEY(USER_ID)
        REFERENCES SYS_USER(USER_ID),

    CONSTRAINT FK_T_ORDER_SESSION
        FOREIGN KEY(SESSION_ID)
        REFERENCES SHOW_SESSION(SESSION_ID),

    CONSTRAINT FK_T_ORDER_PARENT
        FOREIGN KEY(PARENT_ORDER_ID)
        REFERENCES T_ORDER(ORDER_ID)
);

CREATE INDEX IDX_T_ORDER_USER
ON T_ORDER(USER_ID);

CREATE INDEX IDX_T_ORDER_SESSION
ON T_ORDER(SESSION_ID);

CREATE INDEX IDX_T_ORDER_STATUS
ON T_ORDER(ORDER_STATUS);

CREATE INDEX IDX_T_ORDER_CREATE_TIME
ON T_ORDER(CREATE_TIME);

CREATE INDEX IDX_T_ORDER_USER_STATUS
ON T_ORDER(USER_ID,ORDER_STATUS);

COMMENT ON TABLE T_ORDER IS '订单主表';

COMMENT ON COLUMN T_ORDER.ORDER_ID IS '订单ID';
COMMENT ON COLUMN T_ORDER.ORDER_NO IS '订单编号';
COMMENT ON COLUMN T_ORDER.USER_ID IS '下单用户ID（关联 SYS_USER）';
COMMENT ON COLUMN T_ORDER.SESSION_ID IS '所属场次ID';
COMMENT ON COLUMN T_ORDER.ORDER_TYPE IS 'NORMAL普通 SPLIT拆单 MERGE合单 EXCHANGE改签';
COMMENT ON COLUMN T_ORDER.PARENT_ORDER_ID IS '父订单ID';
COMMENT ON COLUMN T_ORDER.TOTAL_AMOUNT IS '订单总金额';
COMMENT ON COLUMN T_ORDER.DISCOUNT_AMOUNT IS '优惠金额';
COMMENT ON COLUMN T_ORDER.ACTUAL_AMOUNT IS '实付金额';
COMMENT ON COLUMN T_ORDER.TICKET_COUNT IS '购票数量';
COMMENT ON COLUMN T_ORDER.ORDER_STATUS IS '订单状态';
COMMENT ON COLUMN T_ORDER.EXPIRE_TIME IS '订单过期时间';
COMMENT ON COLUMN T_ORDER.PAY_TIME IS '支付时间';
COMMENT ON COLUMN T_ORDER.ISSUE_TIME IS '出票时间';
COMMENT ON COLUMN T_ORDER.CANCEL_TIME IS '取消时间';
COMMENT ON COLUMN T_ORDER.SOURCE IS '下单渠道';
COMMENT ON COLUMN T_ORDER.IP_ADDRESS IS '客户端IP';
COMMENT ON COLUMN T_ORDER.REMARK IS '订单备注';
COMMENT ON COLUMN T_ORDER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN T_ORDER.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN T_ORDER.CREATE_BY IS '创建人';
COMMENT ON COLUMN T_ORDER.UPDATE_BY IS '修改人';


-- 6-2. 订单明细表
CREATE TABLE ORDER_ITEM
(
    ORDER_ITEM_ID           NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_ORDER_ITEM PRIMARY KEY,

    ORDER_ID                NUMBER(19) NOT NULL,

    SEAT_ID                 NUMBER(19) NOT NULL,

    PRICE_STRATEGY_ID       NUMBER(19) NOT NULL,

    REAL_NAME_ID            NUMBER(19),

    UNIT_PRICE              NUMBER(10,2)
        DEFAULT 0 NOT NULL,

    ITEM_STATUS             VARCHAR2(20 CHAR)
        DEFAULT 'NORMAL' NOT NULL,

    CREATE_TIME             TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    UPDATE_TIME             TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CREATE_BY               VARCHAR2(50 CHAR),

    UPDATE_BY               VARCHAR2(50 CHAR),

    CONSTRAINT CHK_ORDER_ITEM_STATUS
        CHECK
        (
            ITEM_STATUS IN
            (
                'NORMAL',
                'REFUNDING',
                'REFUNDED',
                'EXCHANGING',
                'EXCHANGED'
            )
        ),

    CONSTRAINT CHK_ORDER_ITEM_PRICE
        CHECK(UNIT_PRICE>=0),

    CONSTRAINT FK_ORDER_ITEM_ORDER
        FOREIGN KEY(ORDER_ID)
        REFERENCES T_ORDER(ORDER_ID),

    CONSTRAINT FK_ORDER_ITEM_SEAT
        FOREIGN KEY(SEAT_ID)
        REFERENCES SEAT(SEAT_ID),

    CONSTRAINT FK_ORDER_ITEM_PRICE
        FOREIGN KEY(PRICE_STRATEGY_ID)
        REFERENCES PRICE_STRATEGY(PRICE_STRATEGY_ID),

    CONSTRAINT FK_ORDER_ITEM_REALNAME
        FOREIGN KEY(REAL_NAME_ID)
        REFERENCES USER_REAL_NAME(REAL_NAME_ID)
);

CREATE INDEX IDX_ORDER_ITEM_ORDER
ON ORDER_ITEM(ORDER_ID);

CREATE INDEX IDX_ORDER_ITEM_SEAT
ON ORDER_ITEM(SEAT_ID);

CREATE INDEX IDX_ORDER_ITEM_PRICE
ON ORDER_ITEM(PRICE_STRATEGY_ID);

CREATE INDEX IDX_ORDER_ITEM_REALNAME
ON ORDER_ITEM(REAL_NAME_ID);

CREATE INDEX IDX_ORDER_ITEM_STATUS
ON ORDER_ITEM(ITEM_STATUS);

CREATE INDEX IDX_ORDER_ITEM_ORDER_STATUS
ON ORDER_ITEM(ORDER_ID,ITEM_STATUS);

COMMENT ON TABLE ORDER_ITEM IS '订单明细表';

COMMENT ON COLUMN ORDER_ITEM.ORDER_ITEM_ID IS '订单明细ID';
COMMENT ON COLUMN ORDER_ITEM.ORDER_ID IS '所属订单ID';
COMMENT ON COLUMN ORDER_ITEM.SEAT_ID IS '座位ID';
COMMENT ON COLUMN ORDER_ITEM.PRICE_STRATEGY_ID IS '票价策略ID（快照）';
COMMENT ON COLUMN ORDER_ITEM.REAL_NAME_ID IS '观演人ID';
COMMENT ON COLUMN ORDER_ITEM.UNIT_PRICE IS '下单时票价';
COMMENT ON COLUMN ORDER_ITEM.ITEM_STATUS IS 'NORMAL REFUNDING REFUNDED EXCHANGING EXCHANGED';
COMMENT ON COLUMN ORDER_ITEM.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN ORDER_ITEM.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN ORDER_ITEM.CREATE_BY IS '创建人';
COMMENT ON COLUMN ORDER_ITEM.UPDATE_BY IS '修改人';


/*==============================================================*/
/* 第七部分：座位锁与座位预订                                      */
/*==============================================================*/

-- 7-1. 座位锁表（已取消注释的外键约束）
CREATE TABLE SEAT_LOCK (
    SEAT_LOCK_ID    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    SESSION_ID      NUMBER(19) NOT NULL,
    SEAT_ID         NUMBER(19) NOT NULL,
    USER_ID         NUMBER(19) NOT NULL,
    LOCK_TOKEN      VARCHAR2(64 CHAR) NOT NULL,
    LOCK_STATUS     VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    LOCK_TIME       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EXPIRE_TIME     TIMESTAMP NOT NULL,
    RELEASE_TIME    TIMESTAMP,
    REMARK          VARCHAR2(255 CHAR),
    CREATE_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY       VARCHAR2(50 CHAR),
    UPDATE_BY       VARCHAR2(50 CHAR),

    CONSTRAINT PK_SEAT_LOCK PRIMARY KEY (SEAT_LOCK_ID),
    CONSTRAINT FK_SEAT_LOCK_SEAT FOREIGN KEY (SEAT_ID) REFERENCES SEAT(SEAT_ID),
    CONSTRAINT FK_SEAT_LOCK_SESSION FOREIGN KEY (SESSION_ID) REFERENCES SHOW_SESSION(SESSION_ID),
    CONSTRAINT FK_SEAT_LOCK_USER FOREIGN KEY (USER_ID) REFERENCES SYS_USER(USER_ID),
    CONSTRAINT UK_SEAT_LOCK_TOKEN UNIQUE (LOCK_TOKEN),
    CONSTRAINT CK_SEAT_LOCK_STATUS CHECK ( LOCK_STATUS IN ('ACTIVE', 'RELEASED', 'EXPIRED', 'CONVERTED')),
    CONSTRAINT CK_SEAT_LOCK_TIME CHECK (EXPIRE_TIME > LOCK_TIME),
    CONSTRAINT CK_SEAT_LOCK_RELEASE_TIME CHECK (RELEASE_TIME IS NULL OR RELEASE_TIME >= LOCK_TIME )
);

-- 同一场次、同一座位，只允许存在一条 ACTIVE 锁座记录
CREATE UNIQUE INDEX UK_SEAT_LOCK_ACTIVE ON SEAT_LOCK (CASE WHEN LOCK_STATUS = 'ACTIVE' THEN SESSION_ID END,CASE WHEN LOCK_STATUS = 'ACTIVE' THEN SEAT_ID END);

CREATE INDEX IDX_SEAT_LOCK_SESSION ON SEAT_LOCK(SESSION_ID);
CREATE INDEX IDX_SEAT_LOCK_USER ON SEAT_LOCK(USER_ID);
CREATE INDEX IDX_SEAT_LOCK_EXPIRE ON SEAT_LOCK(EXPIRE_TIME);


-- 7-2. 座位预订表（已取消注释的外键约束）
CREATE TABLE SEAT_RESERVATION (
    SEAT_RESERVATION_ID NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    SESSION_ID          NUMBER(19) NOT NULL,
    SEAT_ID             NUMBER(19) NOT NULL,
    ORDER_ITEM_ID       NUMBER(19),
    SEAT_LOCK_ID        NUMBER(19),
    RESERVATION_TYPE    VARCHAR2(20 CHAR) DEFAULT 'ORDER' NOT NULL,
    RESERVATION_STATUS  VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    RESERVE_TIME        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CANCEL_TIME         TIMESTAMP,
    HOLD_REASON         VARCHAR2(255 CHAR),
    REMARK              VARCHAR2(255 CHAR),
    CREATE_TIME         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY           VARCHAR2(50 CHAR),
    UPDATE_BY           VARCHAR2(50 CHAR),

    CONSTRAINT PK_SEAT_RESERVATION PRIMARY KEY (SEAT_RESERVATION_ID),
    CONSTRAINT FK_SEAT_RESERVATION_SEAT FOREIGN KEY (SEAT_ID) REFERENCES SEAT(SEAT_ID),
    CONSTRAINT FK_SEAT_RESERVATION_LOCK FOREIGN KEY (SEAT_LOCK_ID) REFERENCES SEAT_LOCK(SEAT_LOCK_ID),
    CONSTRAINT FK_SEAT_RESERVATION_SESSION FOREIGN KEY (SESSION_ID) REFERENCES SHOW_SESSION(SESSION_ID),
    CONSTRAINT FK_SEAT_RESERVATION_ORDER_ITEM FOREIGN KEY (ORDER_ITEM_ID) REFERENCES ORDER_ITEM(ORDER_ITEM_ID),

    -- 一条订单明细最多对应一条正式占座记录
    CONSTRAINT UK_SEAT_RESERVATION_ORDER_ITEM UNIQUE (ORDER_ITEM_ID),

    -- 一个锁座记录最多转成一条正式占座记录
    CONSTRAINT UK_SEAT_RESERVATION_LOCK UNIQUE (SEAT_LOCK_ID),

    CONSTRAINT CK_SEAT_RESERVATION_TYPE CHECK (RESERVATION_TYPE IN ('ORDER', 'SYSTEM', 'VIP')),
    CONSTRAINT CK_SEAT_RESERVATION_STATUS CHECK (RESERVATION_STATUS IN ('ACTIVE', 'CANCELLED', 'RELEASED')),
    CONSTRAINT CK_SEAT_RESERVATION_CANCEL CHECK (CANCEL_TIME IS NULL OR CANCEL_TIME >= RESERVE_TIME ),
    CONSTRAINT CK_SEAT_RESERVATION_ORDER_ITEM_CHECK CHECK ((RESERVATION_TYPE = 'ORDER' AND ORDER_ITEM_ID IS NOT NULL) OR (RESERVATION_TYPE IN ('SYSTEM', 'VIP') AND ORDER_ITEM_ID IS NULL))
);

-- 同一场次、同一座位，只允许存在一条 ACTIVE 正式占座记录
CREATE UNIQUE INDEX UK_SEAT_RESERVATION_ACTIVE ON SEAT_RESERVATION (CASE WHEN RESERVATION_STATUS = 'ACTIVE' THEN SESSION_ID END,CASE WHEN RESERVATION_STATUS = 'ACTIVE' THEN SEAT_ID END);

CREATE INDEX IDX_SEAT_RESERVATION_SESSION ON SEAT_RESERVATION(SESSION_ID);


-- 7-3. 选座规则表
CREATE TABLE SEAT_RULE (
    SEAT_RULE_ID            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    RULE_CODE               VARCHAR2(30 CHAR) NOT NULL,
    RULE_NAME               VARCHAR2(100 CHAR) NOT NULL,
    RULE_TYPE               VARCHAR2(30 CHAR) NOT NULL,
    MIN_SEAT_COUNT          NUMBER(3) DEFAULT 1 NOT NULL,
    MAX_SEAT_COUNT          NUMBER(3) DEFAULT 10 NOT NULL,
    ALLOW_CROSS_ROW         CHAR(1) DEFAULT 'N' NOT NULL,
    ALLOW_CROSS_SECTION     CHAR(1) DEFAULT 'N' NOT NULL,
    PRIORITY                NUMBER(5) DEFAULT 100 NOT NULL,
    RULE_STATUS             VARCHAR2(20 CHAR) DEFAULT 'ENABLED' NOT NULL,
    REMARK                  VARCHAR2(255 CHAR),
    CREATE_TIME             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY               VARCHAR2(50 CHAR),
    UPDATE_BY               VARCHAR2(50 CHAR),

    CONSTRAINT PK_SEAT_RULE PRIMARY KEY (SEAT_RULE_ID),
    CONSTRAINT UK_SEAT_RULE_CODE UNIQUE (RULE_CODE),
    CONSTRAINT CK_SEAT_RULE_TYPE CHECK ( RULE_TYPE IN ('CONTINUOUS', 'NO_SINGLE_LEFT', 'LIMIT_COUNT', 'SECTION_LIMIT')),
    CONSTRAINT CK_SEAT_RULE_CROSS_ROW CHECK (ALLOW_CROSS_ROW IN ('Y', 'N')),
    CONSTRAINT CK_SEAT_RULE_CROSS_SECTION CHECK (ALLOW_CROSS_SECTION IN ('Y', 'N')),
    CONSTRAINT CK_SEAT_RULE_STATUS CHECK (RULE_STATUS IN ('ENABLED', 'DISABLED')),
    CONSTRAINT CK_SEAT_RULE_COUNT CHECK (MIN_SEAT_COUNT <= MAX_SEAT_COUNT),
    CONSTRAINT CK_SEAT_RULE_PRIORITY CHECK (PRIORITY >= 0)
);

-- 7-4. 规则适用范围表
CREATE TABLE SEAT_RULE_SCOPE (
    RULE_SCOPE_ID   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    SEAT_RULE_ID    NUMBER(19) NOT NULL,
    SCOPE_TYPE      VARCHAR2(20 CHAR) NOT NULL,
    SEAT_MAP_ID     NUMBER(19),
    SEAT_SECTION_ID NUMBER(19),
    SCOPE_STATUS    VARCHAR2(20 CHAR) DEFAULT 'ENABLED' NOT NULL,
    CREATE_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY       VARCHAR2(50 CHAR),
    UPDATE_BY       VARCHAR2(50 CHAR),

    CONSTRAINT PK_SEAT_RULE_SCOPE PRIMARY KEY (RULE_SCOPE_ID),
    CONSTRAINT FK_SEAT_RULE_SCOPE_RULE FOREIGN KEY (SEAT_RULE_ID) REFERENCES SEAT_RULE(SEAT_RULE_ID),
    CONSTRAINT FK_SEAT_RULE_SCOPE_MAP FOREIGN KEY (SEAT_MAP_ID) REFERENCES SEAT_MAP(SEAT_MAP_ID),
    CONSTRAINT FK_SEAT_RULE_SCOPE_SECTION FOREIGN KEY (SEAT_SECTION_ID) REFERENCES SEAT_SECTION(SEAT_SECTION_ID),
    CONSTRAINT CK_SEAT_RULE_SCOPE_TYPE CHECK (SCOPE_TYPE IN ('MAP', 'SECTION')),
    CONSTRAINT CK_SEAT_RULE_SCOPE_STATUS CHECK (SCOPE_STATUS IN ('ENABLED', 'DISABLED')),

    -- MAP 范围只能填 SEAT_MAP_ID；SECTION 范围只能填 SEAT_SECTION_ID
    CONSTRAINT CK_SEAT_RULE_SCOPE_TARGET CHECK ((SCOPE_TYPE = 'MAP' AND SEAT_MAP_ID IS NOT NULL AND SEAT_SECTION_ID IS NULL) OR (SCOPE_TYPE = 'SECTION' AND SEAT_SECTION_ID IS NOT NULL AND SEAT_MAP_ID IS NULL))
);

-- 同一规则不能重复配置到同一张座位图
CREATE UNIQUE INDEX UK_SEAT_RULE_SCOPE_MAP ON SEAT_RULE_SCOPE ( CASE WHEN SCOPE_TYPE = 'MAP' THEN SEAT_RULE_ID END,CASE WHEN SCOPE_TYPE = 'MAP' THEN SEAT_MAP_ID END);

-- 同一规则不能重复配置到同一个票区
CREATE UNIQUE INDEX UK_SEAT_RULE_SCOPE_SECTION ON SEAT_RULE_SCOPE ( CASE WHEN SCOPE_TYPE = 'SECTION' THEN SEAT_RULE_ID END, CASE WHEN SCOPE_TYPE = 'SECTION' THEN SEAT_SECTION_ID END);


/*==============================================================*/
/* 第八部分：座位图常用查询索引（来自 DDL.sql）                       */
/*==============================================================*/

CREATE INDEX IDX_SEAT_MAP_VENUE ON SEAT_MAP(VENUE_ID);
CREATE INDEX IDX_SEAT_SECTION_MAP ON SEAT_SECTION(SEAT_MAP_ID);
CREATE INDEX IDX_SEAT_SECTION_ORDER ON SEAT_SECTION(SEAT_MAP_ID, DISPLAY_ORDER);
CREATE INDEX IDX_SEAT_SECTION_SELLABLE ON SEAT_SECTION(IS_SELLABLE);
CREATE INDEX IDX_SEAT_SECTION_ID ON SEAT(SEAT_SECTION_ID);
CREATE INDEX IDX_SEAT_TYPE ON SEAT(SEAT_TYPE);
CREATE INDEX IDX_SEAT_STATUS ON SEAT(SEAT_STATUS);
CREATE INDEX IDX_SEAT_RULE_SCOPE_RULE ON SEAT_RULE_SCOPE(SEAT_RULE_ID);


/*==============================================================*/
/* 第九部分：支付与电子票模块                                      */
/*==============================================================*/

-- 9-1. 支付流水表
CREATE TABLE PAYMENT
(
    PAYMENT_ID          NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_PAYMENT PRIMARY KEY,

    PAYMENT_NO          VARCHAR2(50 CHAR) NOT NULL,

    ORDER_ID            NUMBER(19) NOT NULL,

    USER_ID             NUMBER(19) NOT NULL,

    PAY_AMOUNT          NUMBER(12,2)
        DEFAULT 0 NOT NULL,

    PAY_CHANNEL         VARCHAR2(20 CHAR) NOT NULL,

    PAY_STATUS          VARCHAR2(20 CHAR)
        DEFAULT 'PENDING' NOT NULL,

    TRADE_NO            VARCHAR2(100 CHAR),

    CALLBACK_DATA       CLOB,

    CALLBACK_TIME       TIMESTAMP,

    PAY_TIME            TIMESTAMP,

    REFUND_AMOUNT       NUMBER(12,2)
        DEFAULT 0 NOT NULL,

    CREATE_TIME         TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    UPDATE_TIME         TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CREATE_BY           VARCHAR2(50 CHAR),

    UPDATE_BY           VARCHAR2(50 CHAR),

    CONSTRAINT UK_PAYMENT_NO
        UNIQUE(PAYMENT_NO),

    CONSTRAINT CHK_PAYMENT_AMOUNT
        CHECK(PAY_AMOUNT>=0),

    CONSTRAINT CHK_PAYMENT_REFUND
        CHECK
        (
            REFUND_AMOUNT>=0
            AND
            REFUND_AMOUNT<=PAY_AMOUNT
        ),

    CONSTRAINT CHK_PAYMENT_CHANNEL
        CHECK
        (
            PAY_CHANNEL IN
            (
                'ALIPAY',
                'WECHAT',
                'UNIONPAY',
                'BALANCE'
            )
        ),

    CONSTRAINT CHK_PAYMENT_STATUS
        CHECK
        (
            PAY_STATUS IN
            (
                'PENDING',
                'SUCCESS',
                'FAIL',
                'CLOSED'
            )
        ),

    CONSTRAINT FK_PAYMENT_ORDER
        FOREIGN KEY(ORDER_ID)
        REFERENCES T_ORDER(ORDER_ID),

    CONSTRAINT FK_PAYMENT_USER
        FOREIGN KEY(USER_ID)
        REFERENCES SYS_USER(USER_ID)
);

CREATE INDEX IDX_PAYMENT_ORDER
ON PAYMENT(ORDER_ID);

CREATE INDEX IDX_PAYMENT_USER
ON PAYMENT(USER_ID);

CREATE INDEX IDX_PAYMENT_STATUS
ON PAYMENT(PAY_STATUS);

CREATE INDEX IDX_PAYMENT_PAYTIME
ON PAYMENT(PAY_TIME);

CREATE INDEX IDX_PAYMENT_ORDER_STATUS
ON PAYMENT(ORDER_ID,PAY_STATUS);

COMMENT ON TABLE PAYMENT IS '支付流水表';

COMMENT ON COLUMN PAYMENT.PAYMENT_ID IS '支付流水ID';
COMMENT ON COLUMN PAYMENT.PAYMENT_NO IS '支付流水号';
COMMENT ON COLUMN PAYMENT.ORDER_ID IS '订单ID';
COMMENT ON COLUMN PAYMENT.USER_ID IS '支付用户（关联 SYS_USER）';
COMMENT ON COLUMN PAYMENT.PAY_AMOUNT IS '支付金额';
COMMENT ON COLUMN PAYMENT.PAY_CHANNEL IS '支付渠道';
COMMENT ON COLUMN PAYMENT.PAY_STATUS IS '支付状态';
COMMENT ON COLUMN PAYMENT.TRADE_NO IS '第三方交易流水';
COMMENT ON COLUMN PAYMENT.CALLBACK_DATA IS '支付回调JSON';
COMMENT ON COLUMN PAYMENT.CALLBACK_TIME IS '支付回调时间';
COMMENT ON COLUMN PAYMENT.PAY_TIME IS '支付完成时间';
COMMENT ON COLUMN PAYMENT.REFUND_AMOUNT IS '累计退款金额';
COMMENT ON COLUMN PAYMENT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN PAYMENT.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN PAYMENT.CREATE_BY IS '创建人';
COMMENT ON COLUMN PAYMENT.UPDATE_BY IS '修改人';


-- 9-2. 电子票表
CREATE TABLE E_TICKET
(
    ETICKET_ID              NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_E_TICKET PRIMARY KEY,

    ETICKET_NO              VARCHAR2(50 CHAR) NOT NULL,

    ORDER_ITEM_ID           NUMBER(19) NOT NULL,

    USER_ID                 NUMBER(19) NOT NULL,

    SESSION_ID              NUMBER(19) NOT NULL,

    QR_CODE                 VARCHAR2(255 CHAR) NOT NULL,

    ANTI_FAKE_CODE          VARCHAR2(100 CHAR) NOT NULL,

    TICKET_STATUS           VARCHAR2(20 CHAR)
        DEFAULT 'UNUSED' NOT NULL,

    CHECK_TIME              TIMESTAMP,

    CHECK_DEVICE            VARCHAR2(100 CHAR),

    CHECK_BY                VARCHAR2(50 CHAR),

    CREATE_TIME             TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    UPDATE_TIME             TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CREATE_BY               VARCHAR2(50 CHAR),

    UPDATE_BY               VARCHAR2(50 CHAR),

    CONSTRAINT UK_ETICKET_NO
        UNIQUE(ETICKET_NO),

    CONSTRAINT UK_ETICKET_ORDERITEM
        UNIQUE(ORDER_ITEM_ID),

    CONSTRAINT UK_ETICKET_QRCODE
        UNIQUE(QR_CODE),

    CONSTRAINT UK_ETICKET_ANTIFAKE
        UNIQUE(ANTI_FAKE_CODE),

    CONSTRAINT CHK_ETICKET_STATUS
        CHECK
        (
            TICKET_STATUS IN
            (
                'UNUSED',
                'USED',
                'REFUNDED',
                'EXCHANGED'
            )
        ),

    CONSTRAINT FK_ETICKET_ORDERITEM
        FOREIGN KEY(ORDER_ITEM_ID)
        REFERENCES ORDER_ITEM(ORDER_ITEM_ID),

    CONSTRAINT FK_ETICKET_USER
        FOREIGN KEY(USER_ID)
        REFERENCES SYS_USER(USER_ID),

    CONSTRAINT FK_ETICKET_SESSION
        FOREIGN KEY(SESSION_ID)
        REFERENCES SHOW_SESSION(SESSION_ID)
);

CREATE INDEX IDX_ETICKET_USER
ON E_TICKET(USER_ID);

CREATE INDEX IDX_ETICKET_SESSION
ON E_TICKET(SESSION_ID);

CREATE INDEX IDX_ETICKET_STATUS
ON E_TICKET(TICKET_STATUS);

CREATE INDEX IDX_ETICKET_CHECKTIME
ON E_TICKET(CHECK_TIME);

CREATE INDEX IDX_ETICKET_SESSION_STATUS
ON E_TICKET(SESSION_ID,TICKET_STATUS);

COMMENT ON TABLE E_TICKET IS '电子票表';

COMMENT ON COLUMN E_TICKET.ETICKET_ID IS '电子票ID';
COMMENT ON COLUMN E_TICKET.ETICKET_NO IS '电子票编号';
COMMENT ON COLUMN E_TICKET.ORDER_ITEM_ID IS '订单明细ID';
COMMENT ON COLUMN E_TICKET.USER_ID IS '持票用户（关联 SYS_USER）';
COMMENT ON COLUMN E_TICKET.SESSION_ID IS '所属场次';
COMMENT ON COLUMN E_TICKET.QR_CODE IS '二维码内容';
COMMENT ON COLUMN E_TICKET.ANTI_FAKE_CODE IS '防伪码';
COMMENT ON COLUMN E_TICKET.TICKET_STATUS IS '电子票状态';
COMMENT ON COLUMN E_TICKET.CHECK_TIME IS '核销时间';
COMMENT ON COLUMN E_TICKET.CHECK_DEVICE IS '核销设备';
COMMENT ON COLUMN E_TICKET.CHECK_BY IS '核销人员';
COMMENT ON COLUMN E_TICKET.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN E_TICKET.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN E_TICKET.CREATE_BY IS '创建人';
COMMENT ON COLUMN E_TICKET.UPDATE_BY IS '修改人';


/*==============================================================*/
/* 第十部分：退票模块                                              */
/*==============================================================*/

-- 10-1. 退票申请表
CREATE TABLE REFUND_REQUEST
(
    REFUND_ID              NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_REFUND_REQUEST PRIMARY KEY,

    REFUND_NO              VARCHAR2(30 CHAR) NOT NULL,

    ORDER_ID               NUMBER(19) NOT NULL,

    USER_ID                NUMBER(19) NOT NULL,

    REFUND_TYPE            VARCHAR2(20 CHAR)
        DEFAULT 'FULL' NOT NULL,

    REFUND_REASON          VARCHAR2(500 CHAR),

    REFUND_AMOUNT          NUMBER(12,2)
        DEFAULT 0 NOT NULL,

    ACTUAL_REFUND          NUMBER(12,2),

    FEE_RATE               NUMBER(5,4)
        DEFAULT 0 NOT NULL,

    REFUND_FEE             NUMBER(10,2)
        DEFAULT 0 NOT NULL,

    APPROVE_STATUS         VARCHAR2(20 CHAR)
        DEFAULT 'PENDING' NOT NULL,

    REVIEW_BY              VARCHAR2(50 CHAR),

    REVIEW_TIME            TIMESTAMP,

    REVIEW_REMARK          VARCHAR2(500 CHAR),

    REFUND_STATUS          VARCHAR2(20 CHAR)
        DEFAULT 'PENDING' NOT NULL,

    COMPLETE_TIME          TIMESTAMP,

    CREATE_TIME            TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    UPDATE_TIME            TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CREATE_BY              VARCHAR2(50 CHAR),

    UPDATE_BY              VARCHAR2(50 CHAR),

    CONSTRAINT UK_REFUND_NO
        UNIQUE(REFUND_NO),

    CONSTRAINT CHK_REFUND_TYPE
        CHECK
        (
            REFUND_TYPE IN
            (
                'FULL',
                'PART'
            )
        ),

    CONSTRAINT CHK_REFUND_AMOUNT
        CHECK
        (
            REFUND_AMOUNT>=0
        ),

    CONSTRAINT CHK_REFUND_FEE
        CHECK
        (
            REFUND_FEE>=0
        ),

    CONSTRAINT CHK_REFUND_RATE
        CHECK
        (
            FEE_RATE BETWEEN 0 AND 1
        ),

    CONSTRAINT CHK_APPROVE_STATUS
        CHECK
        (
            APPROVE_STATUS IN
            (
                'PENDING',
                'APPROVED',
                'REJECTED'
            )
        ),

    CONSTRAINT CHK_REFUND_STATUS
        CHECK
        (
            REFUND_STATUS IN
            (
                'PENDING',
                'PROCESSING',
                'COMPLETED',
                'FAILED'
            )
        ),

    CONSTRAINT FK_REFUND_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES T_ORDER(ORDER_ID),

    CONSTRAINT FK_REFUND_USER
        FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER(USER_ID)
);

CREATE INDEX IDX_REFUND_ORDER
ON REFUND_REQUEST(ORDER_ID);

CREATE INDEX IDX_REFUND_USER
ON REFUND_REQUEST(USER_ID);

CREATE INDEX IDX_REFUND_APPROVE
ON REFUND_REQUEST(APPROVE_STATUS);

CREATE INDEX IDX_REFUND_STATUS
ON REFUND_REQUEST(REFUND_STATUS);

CREATE INDEX IDX_REFUND_COMPLETE
ON REFUND_REQUEST(COMPLETE_TIME);

CREATE INDEX IDX_REFUND_ORDER_STATUS
ON REFUND_REQUEST(ORDER_ID,REFUND_STATUS);

COMMENT ON TABLE REFUND_REQUEST IS '退票申请表';

COMMENT ON COLUMN REFUND_REQUEST.REFUND_ID IS '退票申请ID';
COMMENT ON COLUMN REFUND_REQUEST.REFUND_NO IS '退票申请编号';
COMMENT ON COLUMN REFUND_REQUEST.ORDER_ID IS '关联订单';
COMMENT ON COLUMN REFUND_REQUEST.USER_ID IS '申请用户（关联 SYS_USER）';
COMMENT ON COLUMN REFUND_REQUEST.REFUND_TYPE IS 'FULL整单 PART部分';
COMMENT ON COLUMN REFUND_REQUEST.REFUND_REASON IS '退票原因';
COMMENT ON COLUMN REFUND_REQUEST.REFUND_AMOUNT IS '申请退款金额';
COMMENT ON COLUMN REFUND_REQUEST.ACTUAL_REFUND IS '实际退款金额';
COMMENT ON COLUMN REFUND_REQUEST.FEE_RATE IS '手续费率';
COMMENT ON COLUMN REFUND_REQUEST.REFUND_FEE IS '退票手续费';
COMMENT ON COLUMN REFUND_REQUEST.APPROVE_STATUS IS '审核状态';
COMMENT ON COLUMN REFUND_REQUEST.REVIEW_BY IS '审核人';
COMMENT ON COLUMN REFUND_REQUEST.REVIEW_TIME IS '审核时间';
COMMENT ON COLUMN REFUND_REQUEST.REVIEW_REMARK IS '审核意见';
COMMENT ON COLUMN REFUND_REQUEST.REFUND_STATUS IS '退款状态';
COMMENT ON COLUMN REFUND_REQUEST.COMPLETE_TIME IS '退款完成时间';
COMMENT ON COLUMN REFUND_REQUEST.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN REFUND_REQUEST.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN REFUND_REQUEST.CREATE_BY IS '创建人';
COMMENT ON COLUMN REFUND_REQUEST.UPDATE_BY IS '修改人';


-- 10-2. 退票明细表
CREATE TABLE REFUND_ITEM
(
    REFUND_ITEM_ID         NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_REFUND_ITEM PRIMARY KEY,

    REFUND_ID              NUMBER(19) NOT NULL,

    ORDER_ITEM_ID          NUMBER(19) NOT NULL,

    CREATE_TIME            TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    UPDATE_TIME            TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CREATE_BY              VARCHAR2(50 CHAR),

    UPDATE_BY              VARCHAR2(50 CHAR),

    CONSTRAINT UK_REFUND_ORDER_ITEM
        UNIQUE(ORDER_ITEM_ID),

    CONSTRAINT FK_REFUND_ITEM_REQUEST
        FOREIGN KEY (REFUND_ID)
        REFERENCES REFUND_REQUEST(REFUND_ID),

    CONSTRAINT FK_REFUND_ITEM_ORDER
        FOREIGN KEY (ORDER_ITEM_ID)
        REFERENCES ORDER_ITEM(ORDER_ITEM_ID)
);

CREATE INDEX IDX_REFUND_ITEM_REFUND
ON REFUND_ITEM(REFUND_ID);

CREATE INDEX IDX_REFUND_ITEM_ORDER
ON REFUND_ITEM(ORDER_ITEM_ID);

COMMENT ON TABLE REFUND_ITEM IS '退票明细表';

COMMENT ON COLUMN REFUND_ITEM.REFUND_ITEM_ID IS '退票明细ID';
COMMENT ON COLUMN REFUND_ITEM.REFUND_ID IS '退票申请ID';
COMMENT ON COLUMN REFUND_ITEM.ORDER_ITEM_ID IS '订单明细ID';
COMMENT ON COLUMN REFUND_ITEM.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN REFUND_ITEM.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN REFUND_ITEM.CREATE_BY IS '创建人';
COMMENT ON COLUMN REFUND_ITEM.UPDATE_BY IS '修改人';


/*==============================================================*/
/* 第十一部分：改签模块                                            */
/*==============================================================*/

-- 11-1. 改签申请表
CREATE TABLE EXCHANGE_REQUEST
(
    EXCHANGE_ID            NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_EXCHANGE_REQUEST PRIMARY KEY,

    EXCHANGE_NO            VARCHAR2(30 CHAR) NOT NULL,

    ORDER_ID               NUMBER(19) NOT NULL,

    USER_ID                NUMBER(19) NOT NULL,

    ORIG_SESSION_ID        NUMBER(19) NOT NULL,

    TARGET_SESSION_ID      NUMBER(19) NOT NULL,

    EXCHANGE_REASON        VARCHAR2(500 CHAR),

    EXCHANGE_FEE           NUMBER(10,2)
        DEFAULT 0 NOT NULL,

    PRICE_DIFF             NUMBER(10,2)
        DEFAULT 0 NOT NULL,

    APPROVE_STATUS         VARCHAR2(20 CHAR)
        DEFAULT 'PENDING' NOT NULL,

    REVIEW_BY              VARCHAR2(50 CHAR),

    REVIEW_TIME            TIMESTAMP,

    REVIEW_REMARK          VARCHAR2(500 CHAR),

    EXCHANGE_STATUS        VARCHAR2(20 CHAR)
        DEFAULT 'PENDING' NOT NULL,

    COMPLETE_TIME          TIMESTAMP,

    CREATE_TIME            TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    UPDATE_TIME            TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CREATE_BY              VARCHAR2(50 CHAR),

    UPDATE_BY              VARCHAR2(50 CHAR),

    CONSTRAINT UK_EXCHANGE_NO
        UNIQUE(EXCHANGE_NO),

    CONSTRAINT CHK_EXCHANGE_FEE
        CHECK(EXCHANGE_FEE>=0),

    CONSTRAINT CHK_PRICE_DIFF
        CHECK(PRICE_DIFF>=0),

    CONSTRAINT CHK_EXCHANGE_APPROVE
        CHECK
        (
            APPROVE_STATUS IN
            (
                'PENDING',
                'APPROVED',
                'REJECTED'
            )
        ),

    CONSTRAINT CHK_EXCHANGE_STATUS
        CHECK
        (
            EXCHANGE_STATUS IN
            (
                'PENDING',
                'PROCESSING',
                'COMPLETED',
                'FAILED'
            )
        ),

    CONSTRAINT FK_EXCHANGE_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES T_ORDER(ORDER_ID),

    CONSTRAINT FK_EXCHANGE_USER
        FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER(USER_ID),

    CONSTRAINT FK_EXCHANGE_ORIG_SESSION
        FOREIGN KEY (ORIG_SESSION_ID)
        REFERENCES SHOW_SESSION(SESSION_ID),

    CONSTRAINT FK_EXCHANGE_TARGET_SESSION
        FOREIGN KEY (TARGET_SESSION_ID)
        REFERENCES SHOW_SESSION(SESSION_ID)
);

CREATE INDEX IDX_EXCHANGE_ORDER
ON EXCHANGE_REQUEST(ORDER_ID);

CREATE INDEX IDX_EXCHANGE_USER
ON EXCHANGE_REQUEST(USER_ID);

CREATE INDEX IDX_EXCHANGE_ORIG_SESSION
ON EXCHANGE_REQUEST(ORIG_SESSION_ID);

CREATE INDEX IDX_EXCHANGE_TARGET_SESSION
ON EXCHANGE_REQUEST(TARGET_SESSION_ID);

CREATE INDEX IDX_EXCHANGE_STATUS
ON EXCHANGE_REQUEST(EXCHANGE_STATUS);

CREATE INDEX IDX_EXCHANGE_APPROVE
ON EXCHANGE_REQUEST(APPROVE_STATUS);

CREATE INDEX IDX_EXCHANGE_ORDER_STATUS
ON EXCHANGE_REQUEST(ORDER_ID,EXCHANGE_STATUS);

COMMENT ON TABLE EXCHANGE_REQUEST IS '改签申请表';

COMMENT ON COLUMN EXCHANGE_REQUEST.EXCHANGE_ID IS '改签申请ID';
COMMENT ON COLUMN EXCHANGE_REQUEST.EXCHANGE_NO IS '改签申请编号';
COMMENT ON COLUMN EXCHANGE_REQUEST.ORDER_ID IS '订单ID';
COMMENT ON COLUMN EXCHANGE_REQUEST.USER_ID IS '申请用户（关联 SYS_USER）';
COMMENT ON COLUMN EXCHANGE_REQUEST.ORIG_SESSION_ID IS '原场次ID';
COMMENT ON COLUMN EXCHANGE_REQUEST.TARGET_SESSION_ID IS '目标场次ID';
COMMENT ON COLUMN EXCHANGE_REQUEST.EXCHANGE_REASON IS '改签原因';
COMMENT ON COLUMN EXCHANGE_REQUEST.EXCHANGE_FEE IS '改签手续费';
COMMENT ON COLUMN EXCHANGE_REQUEST.PRICE_DIFF IS '票价差额';
COMMENT ON COLUMN EXCHANGE_REQUEST.APPROVE_STATUS IS '审核状态';
COMMENT ON COLUMN EXCHANGE_REQUEST.REVIEW_BY IS '审核人';
COMMENT ON COLUMN EXCHANGE_REQUEST.REVIEW_TIME IS '审核时间';
COMMENT ON COLUMN EXCHANGE_REQUEST.REVIEW_REMARK IS '审核意见';
COMMENT ON COLUMN EXCHANGE_REQUEST.EXCHANGE_STATUS IS '执行状态';
COMMENT ON COLUMN EXCHANGE_REQUEST.COMPLETE_TIME IS '完成时间';
COMMENT ON COLUMN EXCHANGE_REQUEST.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN EXCHANGE_REQUEST.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN EXCHANGE_REQUEST.CREATE_BY IS '创建人';
COMMENT ON COLUMN EXCHANGE_REQUEST.UPDATE_BY IS '修改人';


-- 11-2. 改签明细表
CREATE TABLE EXCHANGE_ITEM
(
    EXCHANGE_ITEM_ID         NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_EXCHANGE_ITEM PRIMARY KEY,

    EXCHANGE_ID              NUMBER(19) NOT NULL,

    ORDER_ITEM_ID            NUMBER(19) NOT NULL,

    NEW_SEAT_ID              NUMBER(19) NOT NULL,

    NEW_PRICE_STRATEGY_ID    NUMBER(19) NOT NULL,

    NEW_UNIT_PRICE           NUMBER(10,2)
        DEFAULT 0 NOT NULL,

    CREATE_TIME              TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    UPDATE_TIME              TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CREATE_BY                VARCHAR2(50 CHAR),

    UPDATE_BY                VARCHAR2(50 CHAR),

    CONSTRAINT UK_EXCHANGE_ORDER_ITEM
        UNIQUE(ORDER_ITEM_ID),

    CONSTRAINT CHK_NEW_UNIT_PRICE
        CHECK(NEW_UNIT_PRICE>=0),

    CONSTRAINT FK_EXCHANGE_ITEM_REQUEST
        FOREIGN KEY (EXCHANGE_ID)
        REFERENCES EXCHANGE_REQUEST(EXCHANGE_ID),

    CONSTRAINT FK_EXCHANGE_ITEM_ORDER
        FOREIGN KEY (ORDER_ITEM_ID)
        REFERENCES ORDER_ITEM(ORDER_ITEM_ID),

    CONSTRAINT FK_EXCHANGE_ITEM_NEW_SEAT
        FOREIGN KEY (NEW_SEAT_ID)
        REFERENCES SEAT(SEAT_ID),

    CONSTRAINT FK_EXCHANGE_ITEM_NEW_PRICE
        FOREIGN KEY (NEW_PRICE_STRATEGY_ID)
        REFERENCES PRICE_STRATEGY(PRICE_STRATEGY_ID)
);

CREATE INDEX IDX_EXCHANGE_ITEM_EXCHANGE
ON EXCHANGE_ITEM(EXCHANGE_ID);

CREATE INDEX IDX_EXCHANGE_ITEM_ORDER
ON EXCHANGE_ITEM(ORDER_ITEM_ID);

CREATE INDEX IDX_EXCHANGE_ITEM_SEAT
ON EXCHANGE_ITEM(NEW_SEAT_ID);

CREATE INDEX IDX_EXCHANGE_ITEM_PRICE
ON EXCHANGE_ITEM(NEW_PRICE_STRATEGY_ID);

COMMENT ON TABLE EXCHANGE_ITEM IS '改签明细表';

COMMENT ON COLUMN EXCHANGE_ITEM.EXCHANGE_ITEM_ID IS '改签明细ID';
COMMENT ON COLUMN EXCHANGE_ITEM.EXCHANGE_ID IS '改签申请ID';
COMMENT ON COLUMN EXCHANGE_ITEM.ORDER_ITEM_ID IS '原订单明细ID';
COMMENT ON COLUMN EXCHANGE_ITEM.NEW_SEAT_ID IS '新座位ID';
COMMENT ON COLUMN EXCHANGE_ITEM.NEW_PRICE_STRATEGY_ID IS '新票价策略ID';
COMMENT ON COLUMN EXCHANGE_ITEM.NEW_UNIT_PRICE IS '新票价';
COMMENT ON COLUMN EXCHANGE_ITEM.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN EXCHANGE_ITEM.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN EXCHANGE_ITEM.CREATE_BY IS '创建人';
COMMENT ON COLUMN EXCHANGE_ITEM.UPDATE_BY IS '修改人';


/*==============================================================*/
/* 第十二部分：退票/改签规则模块                                    */
/*==============================================================*/

-- 12-1. 退票规则表
CREATE TABLE REFUND_POLICY
(
    POLICY_ID               NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_REFUND_POLICY PRIMARY KEY,

    SHOW_ID                 NUMBER(19) NULL,

    POLICY_NAME             VARCHAR2(100 CHAR) NOT NULL,

    REFUND_DEADLINE_HOUR    NUMBER(5) NOT NULL,

    REFUND_RATE             NUMBER(5,4)
        DEFAULT 1 NOT NULL,

    SERVICE_FEE             NUMBER(10,2)
        DEFAULT 0 NOT NULL,

    PRIORITY                NUMBER(5)
        DEFAULT 1 NOT NULL,

    STATUS                  NUMBER(1)
        DEFAULT 1 NOT NULL,

    REMARK                  VARCHAR2(500),

    CREATE_TIME             TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    UPDATE_TIME             TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CREATE_BY               VARCHAR2(50),

    UPDATE_BY               VARCHAR2(50),

    CONSTRAINT CHK_REFUND_POLICY_RATE
        CHECK(REFUND_RATE BETWEEN 0 AND 1),

    CONSTRAINT CHK_REFUND_POLICY_FEE
        CHECK(SERVICE_FEE>=0),

    CONSTRAINT CHK_REFUND_POLICY_PRIORITY
        CHECK(PRIORITY>0),

    CONSTRAINT CHK_REFUND_POLICY_STATUS
        CHECK(STATUS IN (0,1)),

    CONSTRAINT FK_REFUND_POLICY_SHOW
        FOREIGN KEY(SHOW_ID)
        REFERENCES SHOW(SHOW_ID)
);

CREATE INDEX IDX_REFUND_POLICY_SHOW
ON REFUND_POLICY(SHOW_ID);

CREATE INDEX IDX_REFUND_POLICY_STATUS
ON REFUND_POLICY(STATUS);

CREATE INDEX IDX_REFUND_POLICY_PRIORITY
ON REFUND_POLICY(PRIORITY);

COMMENT ON TABLE REFUND_POLICY IS '退票规则表';

COMMENT ON COLUMN REFUND_POLICY.POLICY_ID IS '规则ID';
COMMENT ON COLUMN REFUND_POLICY.SHOW_ID IS '演出ID';
COMMENT ON COLUMN REFUND_POLICY.POLICY_NAME IS '规则名称';
COMMENT ON COLUMN REFUND_POLICY.REFUND_DEADLINE_HOUR IS '距开演允许退票小时数';
COMMENT ON COLUMN REFUND_POLICY.REFUND_RATE IS '退款比例';
COMMENT ON COLUMN REFUND_POLICY.SERVICE_FEE IS '手续费';
COMMENT ON COLUMN REFUND_POLICY.PRIORITY IS '优先级';
COMMENT ON COLUMN REFUND_POLICY.STATUS IS '状态';
COMMENT ON COLUMN REFUND_POLICY.REMARK IS '备注';
COMMENT ON COLUMN REFUND_POLICY.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN REFUND_POLICY.UPDATE_TIME IS '更新时间';


-- 12-2. 改签规则表
CREATE TABLE EXCHANGE_POLICY
(
    POLICY_ID               NUMBER(19)
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_EXCHANGE_POLICY PRIMARY KEY,

    SHOW_ID                 NUMBER(19) NULL,

    POLICY_NAME             VARCHAR2(100 CHAR) NOT NULL,

    EXCHANGE_DEADLINE_HOUR  NUMBER(5) NOT NULL,

    EXCHANGE_FEE            NUMBER(10,2)
        DEFAULT 0 NOT NULL,

    ALLOW_CROSS_SESSION     NUMBER(1)
        DEFAULT 1 NOT NULL,

    PRIORITY                NUMBER(5)
        DEFAULT 1 NOT NULL,

    STATUS                  NUMBER(1)
        DEFAULT 1 NOT NULL,

    REMARK                  VARCHAR2(500),

    CREATE_TIME             TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    UPDATE_TIME             TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CREATE_BY               VARCHAR2(50),

    UPDATE_BY               VARCHAR2(50),

    CONSTRAINT CHK_EXCHANGE_POLICY_FEE
        CHECK(EXCHANGE_FEE>=0),

    CONSTRAINT CHK_EXCHANGE_POLICY_PRIORITY
        CHECK(PRIORITY>0),

    CONSTRAINT CHK_EXCHANGE_POLICY_STATUS
        CHECK(STATUS IN (0,1)),

    CONSTRAINT CHK_EXCHANGE_POLICY_ALLOW
        CHECK(ALLOW_CROSS_SESSION IN (0,1)),

    CONSTRAINT FK_EXCHANGE_POLICY_SHOW
        FOREIGN KEY(SHOW_ID)
        REFERENCES SHOW(SHOW_ID)
);

CREATE INDEX IDX_EXCHANGE_POLICY_SHOW
ON EXCHANGE_POLICY(SHOW_ID);

CREATE INDEX IDX_EXCHANGE_POLICY_STATUS
ON EXCHANGE_POLICY(STATUS);

CREATE INDEX IDX_EXCHANGE_POLICY_PRIORITY
ON EXCHANGE_POLICY(PRIORITY);

COMMENT ON TABLE EXCHANGE_POLICY IS '改签规则表';

COMMENT ON COLUMN EXCHANGE_POLICY.POLICY_ID IS '规则ID';
COMMENT ON COLUMN EXCHANGE_POLICY.SHOW_ID IS '演出ID';
COMMENT ON COLUMN EXCHANGE_POLICY.POLICY_NAME IS '规则名称';
COMMENT ON COLUMN EXCHANGE_POLICY.EXCHANGE_DEADLINE_HOUR IS '距开演允许改签小时数';
COMMENT ON COLUMN EXCHANGE_POLICY.EXCHANGE_FEE IS '改签手续费';
COMMENT ON COLUMN EXCHANGE_POLICY.ALLOW_CROSS_SESSION IS '是否允许跨场次改签';
COMMENT ON COLUMN EXCHANGE_POLICY.PRIORITY IS '优先级';
COMMENT ON COLUMN EXCHANGE_POLICY.STATUS IS '状态';
COMMENT ON COLUMN EXCHANGE_POLICY.REMARK IS '备注';
COMMENT ON COLUMN EXCHANGE_POLICY.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN EXCHANGE_POLICY.UPDATE_TIME IS '更新时间';


/*==============================================================*/
/* 第十三部分：UPDATE_TIME 自动更新触发器                           */
/*==============================================================*/

CREATE OR REPLACE TRIGGER TRG_T_ORDER_UPDATE
BEFORE UPDATE ON T_ORDER
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_ORDER_ITEM_UPDATE
BEFORE UPDATE ON ORDER_ITEM
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_PAYMENT_UPDATE
BEFORE UPDATE ON PAYMENT
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_ETICKET_UPDATE
BEFORE UPDATE ON E_TICKET
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_REFUND_REQUEST_UPDATE
BEFORE UPDATE ON REFUND_REQUEST
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_REFUND_ITEM_UPDATE
BEFORE UPDATE ON REFUND_ITEM
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_EXCHANGE_REQUEST_UPDATE
BEFORE UPDATE ON EXCHANGE_REQUEST
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_EXCHANGE_ITEM_UPDATE
BEFORE UPDATE ON EXCHANGE_ITEM
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_REFUND_POLICY_UPDATE
BEFORE UPDATE ON REFUND_POLICY
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_EXCHANGE_POLICY_UPDATE
BEFORE UPDATE ON EXCHANGE_POLICY
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME:=CURRENT_TIMESTAMP;
END;
/

/*==============================================================*/
/* 第十四部分：座位图模块 UPDATE_TIME 触发器（补全 DDL.sql 表缺失）    */
/*==============================================================*/

CREATE OR REPLACE TRIGGER TRG_SEAT_MAP_UPDATE
BEFORE UPDATE ON SEAT_MAP
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_SECTION_UPDATE
BEFORE UPDATE ON SEAT_SECTION
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_UPDATE
BEFORE UPDATE ON SEAT
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_LOCK_UPDATE
BEFORE UPDATE ON SEAT_LOCK
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_RESERVATION_UPDATE
BEFORE UPDATE ON SEAT_RESERVATION
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_RULE_UPDATE
BEFORE UPDATE ON SEAT_RULE
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_SEAT_RULE_SCOPE_UPDATE
BEFORE UPDATE ON SEAT_RULE_SCOPE
FOR EACH ROW
BEGIN
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

/*==============================================================*/
/* 第十五部分：统一 BEFORE INSERT 触发器（强制审计字段一致性）          */
/*                                                              */
/*  说明: 以下表使用 IDENTITY 自增，其 CREATE_TIME / UPDATE_TIME       */
/*  仅定义了 DEFAULT，但没有 INSERT 触发器保护。                       */
/*  DEFAULT 可以被 SQL 显式赋值覆盖，存在数据一致性风险。               */
/*  统一添加 BEFORE INSERT 触发器，无条件写入 CURRENT_TIMESTAMP，       */
/*  确保审计时间字段不可篡改。                                        */
/*==============================================================*/

-- 座位图模块
CREATE OR REPLACE TRIGGER TRG_BI_SEAT_MAP
BEFORE INSERT ON SEAT_MAP
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SEAT_SECTION
BEFORE INSERT ON SEAT_SECTION
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SEAT
BEFORE INSERT ON SEAT
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SEAT_LOCK
BEFORE INSERT ON SEAT_LOCK
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SEAT_RESERVATION
BEFORE INSERT ON SEAT_RESERVATION
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SEAT_RULE
BEFORE INSERT ON SEAT_RULE
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_SEAT_RULE_SCOPE
BEFORE INSERT ON SEAT_RULE_SCOPE
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

-- 订单模块
CREATE OR REPLACE TRIGGER TRG_BI_T_ORDER
BEFORE INSERT ON T_ORDER
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_ORDER_ITEM
BEFORE INSERT ON ORDER_ITEM
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

-- 支付模块
CREATE OR REPLACE TRIGGER TRG_BI_PAYMENT
BEFORE INSERT ON PAYMENT
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

-- 电子票模块
CREATE OR REPLACE TRIGGER TRG_BI_E_TICKET
BEFORE INSERT ON E_TICKET
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

-- 退票模块
CREATE OR REPLACE TRIGGER TRG_BI_REFUND_REQUEST
BEFORE INSERT ON REFUND_REQUEST
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_REFUND_ITEM
BEFORE INSERT ON REFUND_ITEM
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

-- 改签模块
CREATE OR REPLACE TRIGGER TRG_BI_EXCHANGE_REQUEST
BEFORE INSERT ON EXCHANGE_REQUEST
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_EXCHANGE_ITEM
BEFORE INSERT ON EXCHANGE_ITEM
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

-- 策略模块
CREATE OR REPLACE TRIGGER TRG_BI_REFUND_POLICY
BEFORE INSERT ON REFUND_POLICY
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_BI_EXCHANGE_POLICY
BEFORE INSERT ON EXCHANGE_POLICY
FOR EACH ROW
BEGIN
    :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
    :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
END;
/

/*==============================================================*/
/* 脚本结束                                                      */
/*==============================================================*/
