CREATE TABLE SHOW (
    SHOW_ID        NUMBER(19) NOT NULL,
    SHOW_NAME      VARCHAR2(200 CHAR) NOT NULL,
    CATEGORY_ID    NUMBER(19) NOT NULL,
    DESCRIPTION    VARCHAR2(2000 CHAR),
    DURATION_MINUTES NUMBER(5),
    POSTER_URL     VARCHAR2(500 CHAR),
    STATUS         VARCHAR2(20 CHAR) DEFAULT 'DRAFT' NOT NULL,
    AUDIT_STATUS   VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    AUDIT_BY       VARCHAR2(50 CHAR),
    AUDIT_TIME     TIMESTAMP(6),
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_SHOW PRIMARY KEY (SHOW_ID),
    CONSTRAINT FK_SHOW_CATEGORY FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORY (CATEGORY_ID),
    CONSTRAINT CK_SHOW_STATUS CHECK (STATUS IN ('DRAFT', 'PUBLISHED', 'UNPUBLISHED')),
    CONSTRAINT CK_SHOW_AUDIT CHECK (AUDIT_STATUS IN ('PENDING', 'APPROVED', 'REJECTED'))
);

CREATE INDEX IDX_SHOW_CATEGORY ON SHOW (CATEGORY_ID);
CREATE INDEX IDX_SHOW_STATUS ON SHOW (STATUS);
CREATE INDEX IDX_SHOW_AUDIT ON SHOW (AUDIT_STATUS);

CREATE SEQUENCE SEQ_SHOW START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_SHOW
BEFORE INSERT OR UPDATE ON SHOW
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.SHOW_ID IS NULL THEN
        SELECT SEQ_SHOW.NEXTVAL INTO :NEW.SHOW_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE CATEGORY (
    CATEGORY_ID    NUMBER(19) NOT NULL,
    CATEGORY_NAME  VARCHAR2(50 CHAR) NOT NULL,
    PARENT_ID      NUMBER(19),
    SORT_ORDER     NUMBER(5) DEFAULT 0 NOT NULL,
    STATUS         NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT UK_CATEGORY_NAME UNIQUE (CATEGORY_NAME),
    CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENT_ID)
        REFERENCES CATEGORY (CATEGORY_ID),
    CONSTRAINT CK_CATEGORY_STATUS CHECK (STATUS IN (0, 1))
);

CREATE INDEX IDX_CATEGORY_PARENT ON CATEGORY (PARENT_ID);

CREATE SEQUENCE SEQ_CATEGORY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_CATEGORY
BEFORE INSERT OR UPDATE ON CATEGORY
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.CATEGORY_ID IS NULL THEN
        SELECT SEQ_CATEGORY.NEXTVAL INTO :NEW.CATEGORY_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE TAG (
    TAG_ID         NUMBER(19) NOT NULL,
    TAG_NAME       VARCHAR2(50 CHAR) NOT NULL,
    COLOR          VARCHAR2(20 CHAR),
    STATUS         NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_TAG PRIMARY KEY (TAG_ID),
    CONSTRAINT UK_TAG_NAME UNIQUE (TAG_NAME),
    CONSTRAINT CK_TAG_STATUS CHECK (STATUS IN (0, 1))
);

CREATE SEQUENCE SEQ_TAG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_TAG
BEFORE INSERT OR UPDATE ON TAG
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.TAG_ID IS NULL THEN
        SELECT SEQ_TAG.NEXTVAL INTO :NEW.TAG_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE SHOW_TAG (
    SHOW_TAG_ID    NUMBER(19) NOT NULL,
    SHOW_ID        NUMBER(19) NOT NULL,
    TAG_ID         NUMBER(19) NOT NULL,
    CONSTRAINT PK_SHOW_TAG PRIMARY KEY (SHOW_TAG_ID),
    CONSTRAINT UK_SHOW_TAG UNIQUE (SHOW_ID, TAG_ID),
    CONSTRAINT FK_SHOW_TAG_SHOW FOREIGN KEY (SHOW_ID)
        REFERENCES SHOW (SHOW_ID) ON DELETE CASCADE,
    CONSTRAINT FK_SHOW_TAG_TAG FOREIGN KEY (TAG_ID)
        REFERENCES TAG (TAG_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_SHOW_TAG_TAG ON SHOW_TAG (TAG_ID);

CREATE SEQUENCE SEQ_SHOW_TAG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BI_SHOW_TAG
BEFORE INSERT ON SHOW_TAG
FOR EACH ROW
BEGIN
    IF :NEW.SHOW_TAG_ID IS NULL THEN
        SELECT SEQ_SHOW_TAG.NEXTVAL INTO :NEW.SHOW_TAG_ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE VENUE (
    VENUE_ID       NUMBER(19) NOT NULL,
    VENUE_NAME     VARCHAR2(100 CHAR) NOT NULL,
    ADDRESS        VARCHAR2(200 CHAR),
    CONTACT_PHONE  VARCHAR2(20 CHAR),
    STATUS         VARCHAR2(20 CHAR) DEFAULT 'ENABLED' NOT NULL,
    REMARK         VARCHAR2(255 CHAR),
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_VENUE PRIMARY KEY (VENUE_ID),
    CONSTRAINT UK_VENUE_NAME UNIQUE (VENUE_NAME),
    CONSTRAINT CK_VENUE_STATUS CHECK (STATUS IN ('ENABLED', 'DISABLED'))
);

CREATE SEQUENCE SEQ_VENUE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_VENUE
BEFORE INSERT OR UPDATE ON VENUE
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.VENUE_ID IS NULL THEN
        SELECT SEQ_VENUE.NEXTVAL INTO :NEW.VENUE_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE SEAT_MAP (
    SEAT_MAP_ID    NUMBER(19) NOT NULL,
    VENUE_ID       NUMBER(19) NOT NULL,
    MAP_NAME       VARCHAR2(100 CHAR) NOT NULL,
    ROW_COUNT      NUMBER(5) NOT NULL,
    COL_COUNT      NUMBER(5) NOT NULL,
    STATUS         VARCHAR2(20 CHAR) DEFAULT 'ENABLED' NOT NULL,
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_SEAT_MAP PRIMARY KEY (SEAT_MAP_ID),
    CONSTRAINT FK_SEAT_MAP_VENUE FOREIGN KEY (VENUE_ID)
        REFERENCES VENUE (VENUE_ID),
    CONSTRAINT CK_SEAT_MAP_STATUS CHECK (STATUS IN ('ENABLED', 'DISABLED'))
);

CREATE INDEX IDX_SEAT_MAP_VENUE ON SEAT_MAP (VENUE_ID);

CREATE SEQUENCE SEQ_SEAT_MAP START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_SEAT_MAP
BEFORE INSERT OR UPDATE ON SEAT_MAP
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.SEAT_MAP_ID IS NULL THEN
        SELECT SEQ_SEAT_MAP.NEXTVAL INTO :NEW.SEAT_MAP_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE SEAT_SECTION (
    SEAT_SECTION_ID NUMBER(19) NOT NULL,
    SEAT_MAP_ID     NUMBER(19) NOT NULL,
    SECTION_NAME    VARCHAR2(100 CHAR) NOT NULL,
    SECTION_CODE    VARCHAR2(20 CHAR),
    ROW_START       NUMBER(5) NOT NULL,
    ROW_END         NUMBER(5) NOT NULL,
    COL_START       NUMBER(5) NOT NULL,
    COL_END         NUMBER(5) NOT NULL,
    COLOR           VARCHAR2(20 CHAR),
    PRICE_FACTOR    NUMBER(3,2) DEFAULT 1.00 NOT NULL,
    STATUS          VARCHAR2(20 CHAR) DEFAULT 'ENABLED' NOT NULL,
    CREATE_TIME     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY       VARCHAR2(50 CHAR),
    UPDATE_BY       VARCHAR2(50 CHAR),
    CONSTRAINT PK_SEAT_SECTION PRIMARY KEY (SEAT_SECTION_ID),
    CONSTRAINT FK_SEAT_SECTION_MAP FOREIGN KEY (SEAT_MAP_ID)
        REFERENCES SEAT_MAP (SEAT_MAP_ID),
    CONSTRAINT CK_SEAT_SECTION_STATUS CHECK (STATUS IN ('ENABLED', 'DISABLED')),
    CONSTRAINT CK_SEAT_SECTION_RANGE CHECK (ROW_START <= ROW_END AND COL_START <= COL_END)
);

CREATE INDEX IDX_SEAT_SECTION_MAP ON SEAT_SECTION (SEAT_MAP_ID);

CREATE SEQUENCE SEQ_SEAT_SECTION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_SEAT_SECTION
BEFORE INSERT OR UPDATE ON SEAT_SECTION
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.SEAT_SECTION_ID IS NULL THEN
        SELECT SEQ_SEAT_SECTION.NEXTVAL INTO :NEW.SEAT_SECTION_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE SESSION (
    SESSION_ID      NUMBER(19) NOT NULL,
    SHOW_ID         NUMBER(19) NOT NULL,
    SEAT_MAP_ID     NUMBER(19) NOT NULL,
    START_TIME      TIMESTAMP(6) NOT NULL,
    END_TIME        TIMESTAMP(6) NOT NULL,
    SALE_START_TIME TIMESTAMP(6) NOT NULL,
    SALE_END_TIME   TIMESTAMP(6) NOT NULL,
    SESSION_STATUS  VARCHAR2(20 CHAR) DEFAULT 'UPCOMING' NOT NULL,
    CREATE_TIME     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY       VARCHAR2(50 CHAR),
    UPDATE_BY       VARCHAR2(50 CHAR),
    CONSTRAINT PK_SESSION PRIMARY KEY (SESSION_ID),
    CONSTRAINT FK_SESSION_SHOW FOREIGN KEY (SHOW_ID)
        REFERENCES SHOW (SHOW_ID),
    CONSTRAINT FK_SESSION_SEAT_MAP FOREIGN KEY (SEAT_MAP_ID)
        REFERENCES SEAT_MAP (SEAT_MAP_ID),
    CONSTRAINT CK_SESSION_STATUS CHECK (SESSION_STATUS IN ('UPCOMING', 'PRESALE', 'ONSALE', 'SOLD_OUT', 'ENDED')),
    CONSTRAINT CK_SESSION_TIME CHECK (START_TIME < END_TIME AND SALE_START_TIME < SALE_END_TIME)
);

CREATE INDEX IDX_SESSION_SHOW ON SESSION (SHOW_ID);
CREATE INDEX IDX_SESSION_SEAT_MAP ON SESSION (SEAT_MAP_ID);
CREATE INDEX IDX_SESSION_STATUS ON SESSION (SESSION_STATUS);
CREATE INDEX IDX_SESSION_START ON SESSION (START_TIME);

CREATE SEQUENCE SEQ_SESSION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_SESSION
BEFORE INSERT OR UPDATE ON SESSION
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.SESSION_ID IS NULL THEN
        SELECT SEQ_SESSION.NEXTVAL INTO :NEW.SESSION_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE PRICE_STRATEGY (
    PRICE_STRATEGY_ID NUMBER(19) NOT NULL,
    SESSION_ID        NUMBER(19) NOT NULL,
    SEAT_SECTION_ID   NUMBER(19) NOT NULL,
    STRATEGY_NAME     VARCHAR2(100 CHAR) NOT NULL,
    PRICE_TYPE        VARCHAR2(20 CHAR) DEFAULT 'STANDARD' NOT NULL,
    PRICE             NUMBER(10,2) NOT NULL,
    SALE_START_TIME   TIMESTAMP(6) NOT NULL,
    SALE_END_TIME     TIMESTAMP(6) NOT NULL,
    PRIORITY          NUMBER(5) DEFAULT 0 NOT NULL,
    QUOTA             NUMBER(10),
    STATUS            VARCHAR2(20 CHAR) DEFAULT 'ENABLED' NOT NULL,
    CREATE_TIME       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY         VARCHAR2(50 CHAR),
    UPDATE_BY         VARCHAR2(50 CHAR),
    CONSTRAINT PK_PRICE_STRATEGY PRIMARY KEY (PRICE_STRATEGY_ID),
    CONSTRAINT FK_PRICE_SESSION FOREIGN KEY (SESSION_ID)
        REFERENCES SESSION (SESSION_ID),
    CONSTRAINT FK_PRICE_SEAT_SECTION FOREIGN KEY (SEAT_SECTION_ID)
        REFERENCES SEAT_SECTION (SEAT_SECTION_ID),
    CONSTRAINT CK_PRICE_TYPE CHECK (PRICE_TYPE IN ('EARLY_BIRD', 'PRESALE', 'STANDARD', 'VIP', 'MEMBER')),
    CONSTRAINT CK_PRICE_STATUS CHECK (STATUS IN ('ENABLED', 'DISABLED')),
    CONSTRAINT CK_PRICE_VALUE CHECK (PRICE >= 0)
);

CREATE INDEX IDX_PRICE_SESSION ON PRICE_STRATEGY (SESSION_ID);
CREATE INDEX IDX_PRICE_SECTION ON PRICE_STRATEGY (SEAT_SECTION_ID);

CREATE SEQUENCE SEQ_PRICE_STRATEGY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_PRICE_STRATEGY
BEFORE INSERT OR UPDATE ON PRICE_STRATEGY
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.PRICE_STRATEGY_ID IS NULL THEN
        SELECT SEQ_PRICE_STRATEGY.NEXTVAL INTO :NEW.PRICE_STRATEGY_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE PURCHASE_LIMIT (
    LIMIT_ID        NUMBER(19) NOT NULL,
    LIMIT_NAME      VARCHAR2(100 CHAR) NOT NULL,
    SHOW_ID         NUMBER(19),
    SESSION_ID      NUMBER(19),
    CHANNEL         VARCHAR2(20 CHAR),
    USER_TYPE       VARCHAR2(20 CHAR),
    MAX_BUY_COUNT   NUMBER(5) NOT NULL,
    LIMIT_TYPE      VARCHAR2(20 CHAR) DEFAULT 'TICKET' NOT NULL,
    START_TIME      TIMESTAMP(6),
    END_TIME        TIMESTAMP(6),
    STATUS          VARCHAR2(20 CHAR) DEFAULT 'ENABLED' NOT NULL,
    CREATE_TIME     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME     TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY       VARCHAR2(50 CHAR),
    UPDATE_BY       VARCHAR2(50 CHAR),
    CONSTRAINT PK_PURCHASE_LIMIT PRIMARY KEY (LIMIT_ID),
    CONSTRAINT FK_LIMIT_SHOW FOREIGN KEY (SHOW_ID)
        REFERENCES SHOW (SHOW_ID),
    CONSTRAINT FK_LIMIT_SESSION FOREIGN KEY (SESSION_ID)
        REFERENCES SESSION (SESSION_ID),
    CONSTRAINT CK_LIMIT_CHANNEL CHECK (CHANNEL IN ('WEB', 'APP', 'MINI_PROGRAM')),
    CONSTRAINT CK_LIMIT_USER_TYPE CHECK (USER_TYPE IN ('NORMAL', 'MEMBER', 'VIP')),
    CONSTRAINT CK_LIMIT_TYPE CHECK (LIMIT_TYPE IN ('TICKET', 'ORDER')),
    CONSTRAINT CK_LIMIT_STATUS CHECK (STATUS IN ('ENABLED', 'DISABLED'))
);

CREATE INDEX IDX_LIMIT_SHOW ON PURCHASE_LIMIT (SHOW_ID);
CREATE INDEX IDX_LIMIT_SESSION ON PURCHASE_LIMIT (SESSION_ID);

CREATE SEQUENCE SEQ_PURCHASE_LIMIT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_PURCHASE_LIMIT
BEFORE INSERT OR UPDATE ON PURCHASE_LIMIT
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.LIMIT_ID IS NULL THEN
        SELECT SEQ_PURCHASE_LIMIT.NEXTVAL INTO :NEW.LIMIT_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE MARKETING_CONTENT (
    CONTENT_ID     NUMBER(19) NOT NULL,
    SHOW_ID        NUMBER(19) NOT NULL,
    CONTENT_TYPE   VARCHAR2(20 CHAR) DEFAULT 'NOTICE' NOT NULL,
    TITLE          VARCHAR2(200 CHAR) NOT NULL,
    CONTENT_TEXT   CLOB,
    IMAGE_URL      VARCHAR2(500 CHAR),
    SORT_ORDER     NUMBER(5) DEFAULT 0 NOT NULL,
    STATUS         VARCHAR2(20 CHAR) DEFAULT 'ENABLED' NOT NULL,
    PUBLISH_TIME   TIMESTAMP(6),
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_MARKETING_CONTENT PRIMARY KEY (CONTENT_ID),
    CONSTRAINT FK_MARKETING_SHOW FOREIGN KEY (SHOW_ID)
        REFERENCES SHOW (SHOW_ID),
    CONSTRAINT CK_MARKETING_TYPE CHECK (CONTENT_TYPE IN ('NOTICE', 'AD', 'PROMOTION')),
    CONSTRAINT CK_MARKETING_STATUS CHECK (STATUS IN ('ENABLED', 'DISABLED'))
);

CREATE INDEX IDX_MARKETING_SHOW ON MARKETING_CONTENT (SHOW_ID);
CREATE INDEX IDX_MARKETING_STATUS ON MARKETING_CONTENT (STATUS);

CREATE SEQUENCE SEQ_MARKETING_CONTENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_MARKETING_CONTENT
BEFORE INSERT OR UPDATE ON MARKETING_CONTENT
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.CONTENT_ID IS NULL THEN
        SELECT SEQ_MARKETING_CONTENT.NEXTVAL INTO :NEW.CONTENT_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/