CREATE TABLE ORG_STRUCTURE (
    ORG_ID       NUMBER(19) NOT NULL,
    PARENT_ID    NUMBER(19),
    ORG_CODE     VARCHAR2(50 CHAR) NOT NULL,
    ORG_NAME     VARCHAR2(100 CHAR) NOT NULL,
    ORG_TYPE     VARCHAR2(20 CHAR) DEFAULT 'DEPT' NOT NULL,
    SORT_ORDER   NUMBER(5) DEFAULT 0 NOT NULL,
    STATUS       NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY    VARCHAR2(50 CHAR),
    UPDATE_BY    VARCHAR2(50 CHAR),
    CONSTRAINT PK_ORG_STRUCTURE PRIMARY KEY (ORG_ID),
    CONSTRAINT UK_ORG_STRUCTURE_CODE UNIQUE (ORG_CODE),
    CONSTRAINT FK_ORG_STRUCTURE_PARENT FOREIGN KEY (PARENT_ID)
        REFERENCES ORG_STRUCTURE (ORG_ID),
    CONSTRAINT CK_ORG_STRUCTURE_TYPE CHECK (ORG_TYPE IN ('COMPANY', 'DEPT', 'TEAM', 'OTHER')),
    CONSTRAINT CK_ORG_STRUCTURE_STATUS CHECK (STATUS IN (0, 1))
);

CREATE INDEX IDX_ORG_PARENT ON ORG_STRUCTURE (PARENT_ID);

CREATE SEQUENCE SEQ_ORG_STRUCTURE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_ORG_STRUCTURE
BEFORE INSERT OR UPDATE ON ORG_STRUCTURE
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.ORG_ID IS NULL THEN
        SELECT SEQ_ORG_STRUCTURE.NEXTVAL INTO :NEW.ORG_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE SYS_USER (
    USER_ID        NUMBER(19) NOT NULL,
    USER_NAME      VARCHAR2(50 CHAR) NOT NULL,
    PASSWORD_HASH  VARCHAR2(255 CHAR) NOT NULL,
    NICKNAME       VARCHAR2(50 CHAR),
    PHONE          VARCHAR2(20 CHAR) NOT NULL,
    EMAIL          VARCHAR2(100 CHAR),
    ORG_ID         NUMBER(19),
    USER_TYPE      VARCHAR2(20 CHAR) DEFAULT 'NORMAL' NOT NULL,
    STATUS         NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_SYS_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UK_SYS_USER_NAME UNIQUE (USER_NAME),
    CONSTRAINT UK_SYS_USER_PHONE UNIQUE (PHONE),
    CONSTRAINT UK_SYS_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT FK_SYS_USER_ORG FOREIGN KEY (ORG_ID)
        REFERENCES ORG_STRUCTURE (ORG_ID),
    CONSTRAINT CK_SYS_USER_TYPE CHECK (USER_TYPE IN ('NORMAL', 'MEMBER', 'VIP')),
    CONSTRAINT CK_SYS_USER_STATUS CHECK (STATUS IN (0, 1, 2))
);

CREATE INDEX IDX_SYS_USER_ORG ON SYS_USER (ORG_ID);
CREATE INDEX IDX_SYS_USER_TYPE ON SYS_USER (USER_TYPE);

CREATE SEQUENCE SEQ_SYS_USER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_SYS_USER
BEFORE INSERT OR UPDATE ON SYS_USER
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.USER_ID IS NULL THEN
        SELECT SEQ_SYS_USER.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE ROLE (
    ROLE_ID      NUMBER(19) NOT NULL,
    ROLE_CODE    VARCHAR2(50 CHAR) NOT NULL,
    ROLE_NAME    VARCHAR2(50 CHAR) NOT NULL,
    ROLE_DESC    VARCHAR2(200 CHAR),
    STATUS       NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY    VARCHAR2(50 CHAR),
    UPDATE_BY    VARCHAR2(50 CHAR),
    CONSTRAINT PK_ROLE PRIMARY KEY (ROLE_ID),
    CONSTRAINT UK_ROLE_CODE UNIQUE (ROLE_CODE),
    CONSTRAINT UK_ROLE_NAME UNIQUE (ROLE_NAME),
    CONSTRAINT CK_ROLE_STATUS CHECK (STATUS IN (0, 1))
);

CREATE SEQUENCE SEQ_ROLE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_ROLE
BEFORE INSERT OR UPDATE ON ROLE
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.ROLE_ID IS NULL THEN
        SELECT SEQ_ROLE.NEXTVAL INTO :NEW.ROLE_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE PERMISSION (
    PERMISSION_ID  NUMBER(19) NOT NULL,
    PERM_CODE      VARCHAR2(100 CHAR) NOT NULL,
    PERM_NAME      VARCHAR2(50 CHAR) NOT NULL,
    RESOURCE_TYPE  VARCHAR2(20 CHAR) NOT NULL,
    PARENT_ID      NUMBER(19),
    SORT_ORDER     NUMBER(5) DEFAULT 0 NOT NULL,
    STATUS         NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY      VARCHAR2(50 CHAR),
    UPDATE_BY      VARCHAR2(50 CHAR),
    CONSTRAINT PK_PERMISSION PRIMARY KEY (PERMISSION_ID),
    CONSTRAINT UK_PERMISSION_CODE UNIQUE (PERM_CODE),
    CONSTRAINT FK_PERMISSION_PARENT FOREIGN KEY (PARENT_ID)
        REFERENCES PERMISSION (PERMISSION_ID),
    CONSTRAINT CK_PERMISSION_TYPE CHECK (RESOURCE_TYPE IN ('MENU', 'BUTTON', 'API', 'DATA')),
    CONSTRAINT CK_PERMISSION_STATUS CHECK (STATUS IN (0, 1))
);

CREATE INDEX IDX_PERMISSION_PARENT ON PERMISSION (PARENT_ID);

CREATE SEQUENCE SEQ_PERMISSION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_PERMISSION
BEFORE INSERT OR UPDATE ON PERMISSION
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.PERMISSION_ID IS NULL THEN
        SELECT SEQ_PERMISSION.NEXTVAL INTO :NEW.PERMISSION_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE USER_ROLE (
    USER_ROLE_ID  NUMBER(19) NOT NULL,
    USER_ID       NUMBER(19) NOT NULL,
    ROLE_ID       NUMBER(19) NOT NULL,
    CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ROLE_ID),
    CONSTRAINT UK_USER_ROLE UNIQUE (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER (USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE (ROLE_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_USER_ROLE_ROLE ON USER_ROLE (ROLE_ID);

CREATE SEQUENCE SEQ_USER_ROLE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BI_USER_ROLE
BEFORE INSERT ON USER_ROLE
FOR EACH ROW
BEGIN
    IF :NEW.USER_ROLE_ID IS NULL THEN
        SELECT SEQ_USER_ROLE.NEXTVAL INTO :NEW.USER_ROLE_ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE ROLE_PERMISSION (
    ROLE_PERM_ID   NUMBER(19) NOT NULL,
    ROLE_ID        NUMBER(19) NOT NULL,
    PERMISSION_ID  NUMBER(19) NOT NULL,
    CONSTRAINT PK_ROLE_PERMISSION PRIMARY KEY (ROLE_PERM_ID),
    CONSTRAINT UK_ROLE_PERMISSION UNIQUE (ROLE_ID, PERMISSION_ID),
    CONSTRAINT FK_RP_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES ROLE (ROLE_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RP_PERMISSION FOREIGN KEY (PERMISSION_ID)
        REFERENCES PERMISSION (PERMISSION_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_RP_PERMISSION ON ROLE_PERMISSION (PERMISSION_ID);

CREATE SEQUENCE SEQ_ROLE_PERMISSION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BI_ROLE_PERMISSION
BEFORE INSERT ON ROLE_PERMISSION
FOR EACH ROW
BEGIN
    IF :NEW.ROLE_PERM_ID IS NULL THEN
        SELECT SEQ_ROLE_PERMISSION.NEXTVAL INTO :NEW.ROLE_PERM_ID FROM DUAL;
    END IF;
END;
/

CREATE TABLE USER_BLACKLIST (
    BLACKLIST_ID  NUMBER(19) NOT NULL,
    USER_ID       NUMBER(19) NOT NULL,
    SHOW_ID       NUMBER(19),
    RISK_TYPE     VARCHAR2(30 CHAR) NOT NULL,
    RISK_SCORE    NUMBER(5) DEFAULT 0 NOT NULL,
    START_TIME    TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    END_TIME      TIMESTAMP(6),
    IS_PERMANENT  NUMBER(1) DEFAULT 0 NOT NULL,
    REASON        VARCHAR2(200 CHAR),
    STATUS        NUMBER(1) DEFAULT 1 NOT NULL,
    CREATE_TIME   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY     VARCHAR2(50 CHAR),
    UPDATE_BY     VARCHAR2(50 CHAR),
    CONSTRAINT PK_USER_BLACKLIST PRIMARY KEY (BLACKLIST_ID),
    CONSTRAINT FK_BLACKLIST_USER FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER (USER_ID),
    CONSTRAINT CK_BLACKLIST_RISK_SCORE CHECK (RISK_SCORE BETWEEN 0 AND 100),
    CONSTRAINT CK_BLACKLIST_PERMANENT CHECK (IS_PERMANENT IN (0, 1)),
    CONSTRAINT CK_BLACKLIST_STATUS CHECK (STATUS IN (0, 1)),
    CONSTRAINT CK_BLACKLIST_TIME CHECK (END_TIME IS NULL OR END_TIME >= START_TIME)
);

CREATE INDEX IDX_BLACKLIST_USER ON USER_BLACKLIST (USER_ID);
CREATE INDEX IDX_BLACKLIST_SHOW ON USER_BLACKLIST (SHOW_ID);
CREATE INDEX IDX_BLACKLIST_STATUS ON USER_BLACKLIST (STATUS);

CREATE SEQUENCE SEQ_USER_BLACKLIST START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_USER_BLACKLIST
BEFORE INSERT OR UPDATE ON USER_BLACKLIST
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.BLACKLIST_ID IS NULL THEN
        SELECT SEQ_USER_BLACKLIST.NEXTVAL INTO :NEW.BLACKLIST_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE USER_REAL_NAME (
    REAL_NAME_ID  NUMBER(19) NOT NULL,
    USER_ID       NUMBER(19) NOT NULL,
    REAL_NAME     VARCHAR2(50 CHAR) NOT NULL,
    ID_CARD_NO    VARCHAR2(255 CHAR) NOT NULL,
    IS_DEFAULT    NUMBER(1) DEFAULT 0 NOT NULL,
    IS_VERIFIED   NUMBER(1) DEFAULT 0 NOT NULL,
    CREATE_TIME   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME   TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY     VARCHAR2(50 CHAR),
    UPDATE_BY     VARCHAR2(50 CHAR),
    CONSTRAINT PK_USER_REAL_NAME PRIMARY KEY (REAL_NAME_ID),
    CONSTRAINT FK_REAL_NAME_USER FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER (USER_ID),
    CONSTRAINT CK_REAL_NAME_DEFAULT CHECK (IS_DEFAULT IN (0, 1)),
    CONSTRAINT CK_REAL_NAME_VERIFIED CHECK (IS_VERIFIED IN (0, 1))
);

CREATE INDEX IDX_REAL_NAME_USER ON USER_REAL_NAME (USER_ID);
CREATE UNIQUE INDEX UK_REAL_NAME_DEFAULT
    ON USER_REAL_NAME (CASE WHEN IS_DEFAULT = 1 THEN USER_ID END);

CREATE SEQUENCE SEQ_USER_REAL_NAME START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_USER_REAL_NAME
BEFORE INSERT OR UPDATE ON USER_REAL_NAME
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.REAL_NAME_ID IS NULL THEN
        SELECT SEQ_USER_REAL_NAME.NEXTVAL INTO :NEW.REAL_NAME_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE OPERATION_LOG (
    LOG_ID            NUMBER(19) NOT NULL,
    USER_ID           NUMBER(19),
    USER_NAME         VARCHAR2(50 CHAR),
    SHOW_ID           NUMBER(19),
    OPERATION_MODULE  VARCHAR2(50 CHAR) NOT NULL,
    OPERATION_TYPE    VARCHAR2(30 CHAR) NOT NULL,
    REQUEST_URL       VARCHAR2(500 CHAR),
    REQUEST_PARAMS    CLOB,
    RESPONSE_RESULT   CLOB,
    IP_ADDRESS        VARCHAR2(50 CHAR),
    USER_AGENT        VARCHAR2(500 CHAR),
    COST_TIME         NUMBER(10),
    STATUS            NUMBER(1) DEFAULT 1 NOT NULL,
    ERROR_MSG         VARCHAR2(500 CHAR),
    CREATE_TIME       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY         VARCHAR2(50 CHAR),
    UPDATE_BY         VARCHAR2(50 CHAR),
    CONSTRAINT PK_OPERATION_LOG PRIMARY KEY (LOG_ID),
    CONSTRAINT FK_OP_LOG_USER FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER (USER_ID),
    CONSTRAINT CK_OP_LOG_STATUS CHECK (STATUS IN (0, 1))
);

CREATE INDEX IDX_OP_LOG_USER ON OPERATION_LOG (USER_ID);
CREATE INDEX IDX_OP_LOG_SHOW ON OPERATION_LOG (SHOW_ID);
CREATE INDEX IDX_OP_LOG_TIME ON OPERATION_LOG (CREATE_TIME);
CREATE INDEX IDX_OP_LOG_TYPE ON OPERATION_LOG (OPERATION_TYPE);

CREATE SEQUENCE SEQ_OPERATION_LOG START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_OPERATION_LOG
BEFORE INSERT OR UPDATE ON OPERATION_LOG
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.LOG_ID IS NULL THEN
        SELECT SEQ_OPERATION_LOG.NEXTVAL INTO :NEW.LOG_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

CREATE TABLE USER_SESSION (
    USER_SESSION_ID  NUMBER(19) NOT NULL,
    USER_ID          NUMBER(19) NOT NULL,
    SESSION_TOKEN    VARCHAR2(128 CHAR) NOT NULL,
    LOGIN_TIME       TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EXPIRE_TIME      TIMESTAMP(6) NOT NULL,
    LOGOUT_TIME      TIMESTAMP(6),
    IP_ADDRESS       VARCHAR2(50 CHAR),
    USER_AGENT       VARCHAR2(500 CHAR),
    RISK_FLAG        NUMBER(1) DEFAULT 0 NOT NULL,
    STATUS           VARCHAR2(20 CHAR) DEFAULT 'ACTIVE' NOT NULL,
    CREATE_TIME      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_TIME      TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATE_BY        VARCHAR2(50 CHAR),
    UPDATE_BY        VARCHAR2(50 CHAR),
    CONSTRAINT PK_USER_SESSION PRIMARY KEY (USER_SESSION_ID),
    CONSTRAINT UK_USER_SESSION_TOKEN UNIQUE (SESSION_TOKEN),
    CONSTRAINT FK_USER_SESSION_USER FOREIGN KEY (USER_ID)
        REFERENCES SYS_USER (USER_ID),
    CONSTRAINT CK_USER_SESSION_STATUS CHECK (STATUS IN ('ACTIVE', 'EXPIRED', 'LOGOUT', 'LOCKED')),
    CONSTRAINT CK_USER_SESSION_RISK CHECK (RISK_FLAG IN (0, 1))
);

CREATE INDEX IDX_USER_SESSION_USER ON USER_SESSION (USER_ID);
CREATE INDEX IDX_USER_SESSION_EXPIRE ON USER_SESSION (EXPIRE_TIME);
CREATE INDEX IDX_USER_SESSION_STATUS ON USER_SESSION (STATUS);

CREATE SEQUENCE SEQ_USER_SESSION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_BIU_USER_SESSION
BEFORE INSERT OR UPDATE ON USER_SESSION
FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.USER_SESSION_ID IS NULL THEN
        SELECT SEQ_USER_SESSION.NEXTVAL INTO :NEW.USER_SESSION_ID FROM DUAL;
    END IF;

    IF INSERTING THEN
        IF :NEW.CREATE_TIME IS NULL THEN
            :NEW.CREATE_TIME := CURRENT_TIMESTAMP;
        END IF;
        IF :NEW.UPDATE_TIME IS NULL THEN
            :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
        END IF;
    ELSIF UPDATING THEN
        :NEW.UPDATE_TIME := CURRENT_TIMESTAMP;
    END IF;
END;
/

ALTER TABLE USER_BLACKLIST ADD CONSTRAINT FK_BLACKLIST_SHOW
    FOREIGN KEY (SHOW_ID) REFERENCES SHOW (SHOW_ID);

ALTER TABLE OPERATION_LOG ADD CONSTRAINT FK_OP_LOG_SHOW
    FOREIGN KEY (SHOW_ID) REFERENCES SHOW (SHOW_ID);
