// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ShowtimeBackend.Data;

#nullable disable

namespace ShowtimeBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726161846_InitialaVerify")]
    partial class InitialaVerify
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("APP_OWNER")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CATEGORY_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CATEGORY_NAME");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("ParentId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PARENT_ID");

                    b.Property<short?>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(5)")
                        .HasDefaultValue((short)0)
                        .HasColumnName("SORT_ORDER");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("STATUS");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CategoryId");

                    b.HasIndex("ParentId");

                    b.ToTable("CATEGORY", "APP_OWNER");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.MarketingContent", b =>
                {
                    b.Property<long>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CONTENT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ContentId"));

                    b.Property<string>("ContentText")
                        .HasColumnType("CLOB")
                        .HasColumnName("CONTENT_TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasDefaultValue("NOTICE")
                        .HasColumnName("CONTENT_TYPE");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500 CHAR)")
                        .HasColumnName("IMAGE_URL");

                    b.Property<DateTime?>("PublishTime")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("PUBLISH_TIME");

                    b.Property<long>("ShowId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SHOW_ID");

                    b.Property<short>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(5)")
                        .HasDefaultValue((short)0)
                        .HasColumnName("SORT_ORDER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasDefaultValue("ENABLED")
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200 CHAR)")
                        .HasColumnName("TITLE");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ContentId");

                    b.HasIndex("ShowId");

                    b.ToTable("MARKETING_CONTENT", "APP_OWNER");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.PriceStrategy", b =>
                {
                    b.Property<long>("PriceStrategyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PRICE_STRATEGY_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PriceStrategyId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("NUMBER(10,2)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("PRICE");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasDefaultValue("STANDARD")
                        .HasColumnName("PRICE_TYPE");

                    b.Property<short>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(5)")
                        .HasDefaultValue((short)0)
                        .HasColumnName("PRIORITY");

                    b.Property<int?>("Quota")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUOTA");

                    b.Property<DateTime>("SaleEndTime")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("SALE_END_TIME");

                    b.Property<DateTime>("SaleStartTime")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("SALE_START_TIME");

                    b.Property<long>("SeatSectionId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SEAT_SECTION_ID");

                    b.Property<long>("SessionId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SESSION_ID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasDefaultValue("ENABLED")
                        .HasColumnName("STATUS");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100 CHAR)")
                        .HasColumnName("STRATEGY_NAME");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PriceStrategyId");

                    b.HasIndex("SessionId");

                    b.ToTable("PRICE_STRATEGY", "APP_OWNER");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.PurchaseLimit", b =>
                {
                    b.Property<long>("LimitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LIMIT_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LimitId"));

                    b.Property<string>("Channel")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasColumnName("CHANNEL");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("END_TIME");

                    b.Property<string>("LimitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100 CHAR)")
                        .HasColumnName("LIMIT_NAME");

                    b.Property<string>("LimitType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasDefaultValue("TICKET")
                        .HasColumnName("LIMIT_TYPE");

                    b.Property<short>("MaxBuyCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(5)")
                        .HasDefaultValue((short)1)
                        .HasColumnName("MAX_BUY_COUNT");

                    b.Property<long?>("SessionId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SESSION_ID");

                    b.Property<long?>("ShowId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SHOW_ID");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("START_TIME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasDefaultValue("ENABLED")
                        .HasColumnName("STATUS");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserType")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasColumnName("USER_TYPE");

                    b.HasKey("LimitId");

                    b.HasIndex("SessionId");

                    b.HasIndex("ShowId");

                    b.ToTable("PURCHASE_LIMIT", "APP_OWNER");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.Show", b =>
                {
                    b.Property<long>("ShowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SHOW_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShowId"));

                    b.Property<string>("AuditBy")
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("AUDIT_BY");

                    b.Property<string>("AuditStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("AUDIT_STATUS");

                    b.Property<DateTime?>("AuditTime")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("AUDIT_TIME");

                    b.Property<long>("CategoryId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("VARCHAR2(2000 CHAR)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<short?>("DurationMinutes")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("DURATION_MINUTES");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(500)
                        .HasColumnType("VARCHAR2(500 CHAR)")
                        .HasColumnName("POSTER_URL");

                    b.Property<string>("ShowName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200 CHAR)")
                        .HasColumnName("SHOW_NAME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("STATUS");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ShowId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SHOW", "APP_OWNER");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.ShowSession", b =>
                {
                    b.Property<long>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SESSION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SessionId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("END_TIME");

                    b.Property<DateTime>("SaleEndTime")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("SALE_END_TIME");

                    b.Property<DateTime>("SaleStartTime")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("SALE_START_TIME");

                    b.Property<long>("SeatMapId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SEAT_MAP_ID");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasDefaultValue("UPCOMING")
                        .HasColumnName("SESSION_STATUS");

                    b.Property<long>("ShowId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SHOW_ID");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("START_TIME");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("SessionId");

                    b.HasIndex("ShowId");

                    b.ToTable("SHOW_SESSION", "APP_OWNER");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.ShowTag", b =>
                {
                    b.Property<long>("ShowTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SHOW_TAG_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShowTagId"));

                    b.Property<long>("ShowId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SHOW_ID");

                    b.Property<long>("TagId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("TAG_ID");

                    b.HasKey("ShowTagId")
                        .HasName("PK_SHOW_TAG");

                    b.HasIndex("TagId");

                    b.HasIndex("ShowId", "TagId")
                        .IsUnique()
                        .HasDatabaseName("UK_SHOW_TAG");

                    b.ToTable("SHOW_TAG", "APP_OWNER");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.Tag", b =>
                {
                    b.Property<long>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("TAG_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TagId"));

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasColumnName("COLOR");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("STATUS");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("TAG_NAME");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("TagId");

                    b.ToTable("TAG", "APP_OWNER");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.Venue", b =>
                {
                    b.Property<long>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("VENUE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VenueId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR2(200 CHAR)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasColumnName("CONTACT_PHONE");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Remark")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR2(255 CHAR)")
                        .HasColumnName("REMARK");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasDefaultValue("ENABLED")
                        .HasColumnName("STATUS");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("VenueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR2(100 CHAR)")
                        .HasColumnName("VENUE_NAME");

                    b.HasKey("VenueId");

                    b.ToTable("VENUE", "APP_OWNER");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.OperationLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("LOG_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<int?>("CostTime")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COST_TIME");

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorMsg")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500 CHAR)")
                        .HasColumnName("ERROR_MSG");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("IP_ADDRESS");

                    b.Property<string>("OperationModule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("OPERATION_MODULE");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30 CHAR)")
                        .HasColumnName("OPERATION_TYPE");

                    b.Property<string>("RequestParams")
                        .IsUnicode(false)
                        .HasColumnType("CLOB")
                        .HasColumnName("REQUEST_PARAMS");

                    b.Property<string>("RequestUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500 CHAR)")
                        .HasColumnName("REQUEST_URL");

                    b.Property<string>("ResponseResult")
                        .IsUnicode(false)
                        .HasColumnType("CLOB")
                        .HasColumnName("RESPONSE_RESULT");

                    b.Property<long?>("ShowId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SHOW_ID");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("STATUS");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500 CHAR)")
                        .HasColumnName("USER_AGENT");

                    b.Property<long?>("UserId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("LogId")
                        .HasName("PK_OPERATION_LOG");

                    b.HasIndex("CreateTime")
                        .HasDatabaseName("IDX_OP_LOG_TIME");

                    b.HasIndex("OperationType")
                        .HasDatabaseName("IDX_OP_LOG_TYPE");

                    b.HasIndex("ShowId")
                        .HasDatabaseName("IDX_OP_LOG_SHOW");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IDX_OP_LOG_USER");

                    b.ToTable("OPERATION_LOG", "APP_OWNER", t =>
                        {
                            t.HasCheckConstraint("CK_OP_LOG_STATUS", "STATUS IN (0, 1)");
                        });
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.OrgStructure", b =>
                {
                    b.Property<long>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ORG_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrgId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("OrgCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("ORG_CODE");

                    b.Property<string>("OrgName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100 CHAR)")
                        .HasColumnName("ORG_NAME");

                    b.Property<string>("OrgType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasDefaultValue("DEPT")
                        .HasColumnName("ORG_TYPE");

                    b.Property<long?>("ParentId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PARENT_ID");

                    b.Property<short>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(5)")
                        .HasDefaultValue((short)0)
                        .HasColumnName("SORT_ORDER");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("STATUS");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("OrgId")
                        .HasName("PK_ORG_STRUCTURE");

                    b.HasIndex("OrgCode")
                        .IsUnique()
                        .HasDatabaseName("UK_ORG_STRUCTURE_CODE");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IDX_ORG_PARENT");

                    b.ToTable("ORG_STRUCTURE", "APP_OWNER", t =>
                        {
                            t.HasCheckConstraint("CK_ORG_STRUCTURE_STATUS", "STATUS IN (0, 1)");

                            t.HasCheckConstraint("CK_ORG_STRUCTURE_TYPE", "ORG_TYPE IN ('COMPANY', 'DEPT', 'TEAM', 'OTHER')");
                        });
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.Permission", b =>
                {
                    b.Property<long>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PERMISSION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PermissionId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long?>("ParentId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PARENT_ID");

                    b.Property<string>("PermCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100 CHAR)")
                        .HasColumnName("PERM_CODE");

                    b.Property<string>("PermName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("PERM_NAME");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasColumnName("RESOURCE_TYPE");

                    b.Property<short>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(5)")
                        .HasDefaultValue((short)0)
                        .HasColumnName("SORT_ORDER");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("STATUS");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("PermissionId")
                        .HasName("PK_PERMISSION");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IDX_PERMISSION_PARENT");

                    b.HasIndex("PermCode")
                        .IsUnique()
                        .HasDatabaseName("UK_PERMISSION_CODE");

                    b.ToTable("PERMISSION", "APP_OWNER", t =>
                        {
                            t.HasCheckConstraint("CK_PERMISSION_STATUS", "STATUS IN (0, 1)");

                            t.HasCheckConstraint("CK_PERMISSION_TYPE", "RESOURCE_TYPE IN ('MENU', 'BUTTON', 'API', 'DATA')");
                        });
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.Role", b =>
                {
                    b.Property<long>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ROLE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoleId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("ROLE_CODE");

                    b.Property<string>("RoleDesc")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(200 CHAR)")
                        .HasColumnName("ROLE_DESC");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("ROLE_NAME");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("STATUS");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("RoleId")
                        .HasName("PK_ROLE");

                    b.HasIndex("RoleCode")
                        .IsUnique()
                        .HasDatabaseName("UK_ROLE_CODE");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("UK_ROLE_NAME");

                    b.ToTable("ROLE", "APP_OWNER", t =>
                        {
                            t.HasCheckConstraint("CK_ROLE_STATUS", "STATUS IN (0, 1)");
                        });
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.RolePermission", b =>
                {
                    b.Property<long>("RolePermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ROLE_PERM_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RolePermId"));

                    b.Property<long>("PermissionId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("PERMISSION_ID");

                    b.Property<long>("RoleId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ROLE_ID");

                    b.HasKey("RolePermId")
                        .HasName("PK_ROLE_PERMISSION");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("IDX_RP_PERMISSION");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("UK_ROLE_PERMISSION");

                    b.ToTable("ROLE_PERMISSION", "APP_OWNER");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.SysUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USER_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(100 CHAR)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("NICKNAME");

                    b.Property<long?>("OrgId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ORG_ID");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255 CHAR)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasColumnName("PHONE");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("STATUS");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("USER_NAME");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasDefaultValue("NORMAL")
                        .HasColumnName("USER_TYPE");

                    b.HasKey("UserId")
                        .HasName("PK_SYS_USER");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UK_SYS_USER_EMAIL")
                        .HasFilter("\"EMAIL\" IS NOT NULL");

                    b.HasIndex("OrgId")
                        .HasDatabaseName("IDX_SYS_USER_ORG");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("UK_SYS_USER_PHONE");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UK_SYS_USER_NAME");

                    b.HasIndex("UserType")
                        .HasDatabaseName("IDX_SYS_USER_TYPE");

                    b.ToTable("SYS_USER", "APP_OWNER", t =>
                        {
                            t.HasCheckConstraint("CK_SYS_USER_STATUS", "STATUS IN (0, 1, 2)");

                            t.HasCheckConstraint("CK_SYS_USER_TYPE", "USER_TYPE IN ('NORMAL', 'MEMBER', 'VIP')");
                        });
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.UserBlacklist", b =>
                {
                    b.Property<long>("BlacklistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("BLACKLIST_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BlacklistId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("END_TIME");

                    b.Property<bool>("IsPermanent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_PERMANENT");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(200 CHAR)")
                        .HasColumnName("REASON");

                    b.Property<short>("RiskScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(5)")
                        .HasDefaultValue((short)0)
                        .HasColumnName("RISK_SCORE");

                    b.Property<string>("RiskType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(30 CHAR)")
                        .HasColumnName("RISK_TYPE");

                    b.Property<long?>("ShowId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("SHOW_ID");

                    b.Property<DateTime>("StartTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("START_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("STATUS");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("UserId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USER_ID");

                    b.HasKey("BlacklistId")
                        .HasName("PK_USER_BLACKLIST");

                    b.HasIndex("ShowId")
                        .HasDatabaseName("IDX_BLACKLIST_SHOW");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_BLACKLIST_STATUS");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IDX_BLACKLIST_USER");

                    b.ToTable("USER_BLACKLIST", "APP_OWNER", t =>
                        {
                            t.HasCheckConstraint("CK_BLACKLIST_PERMANENT", "IS_PERMANENT IN (0, 1)");

                            t.HasCheckConstraint("CK_BLACKLIST_RISK_SCORE", "RISK_SCORE BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_BLACKLIST_STATUS", "STATUS IN (0, 1)");

                            t.HasCheckConstraint("CK_BLACKLIST_TIME", "END_TIME IS NULL OR END_TIME >= START_TIME");
                        });
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.UserRealName", b =>
                {
                    b.Property<long>("RealNameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("REAL_NAME_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RealNameId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IdCardNo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(255 CHAR)")
                        .HasColumnName("ID_CARD_NO");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_DEFAULT");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_VERIFIED");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("REAL_NAME");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("UserId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USER_ID");

                    b.HasKey("RealNameId")
                        .HasName("PK_USER_REAL_NAME");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IDX_REAL_NAME_USER");

                    b.ToTable("USER_REAL_NAME", "APP_OWNER", t =>
                        {
                            t.HasCheckConstraint("CK_REAL_NAME_DEFAULT", "IS_DEFAULT IN (0, 1)");

                            t.HasCheckConstraint("CK_REAL_NAME_VERIFIED", "IS_VERIFIED IN (0, 1)");
                        });
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.UserRole", b =>
                {
                    b.Property<long>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USER_ROLE_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserRoleId"));

                    b.Property<long>("RoleId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ROLE_ID");

                    b.Property<long>("UserId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USER_ID");

                    b.HasKey("UserRoleId")
                        .HasName("PK_USER_ROLE");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IDX_USER_ROLE_ROLE");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UK_USER_ROLE");

                    b.ToTable("USER_ROLE", "APP_OWNER");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.UserSession", b =>
                {
                    b.Property<long>("UserSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USER_SESSION_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserSessionId"));

                    b.Property<string>("CreateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("CREATE_BY");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("CREATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("EXPIRE_TIME");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("IP_ADDRESS");

                    b.Property<DateTime>("LoginTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("LOGIN_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("LOGOUT_TIME");

                    b.Property<bool>("RiskFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("RISK_FLAG");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(128 CHAR)")
                        .HasColumnName("SESSION_TOKEN");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(20 CHAR)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("STATUS");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(50 CHAR)")
                        .HasColumnName("UPDATE_BY");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIMESTAMP(6)")
                        .HasColumnName("UPDATE_TIME")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("VARCHAR2(500 CHAR)")
                        .HasColumnName("USER_AGENT");

                    b.Property<long>("UserId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("USER_ID");

                    b.HasKey("UserSessionId")
                        .HasName("PK_USER_SESSION");

                    b.HasIndex("ExpireTime")
                        .HasDatabaseName("IDX_USER_SESSION_EXPIRE");

                    b.HasIndex("SessionToken")
                        .IsUnique()
                        .HasDatabaseName("UK_USER_SESSION_TOKEN");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_USER_SESSION_STATUS");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IDX_USER_SESSION_USER");

                    b.ToTable("USER_SESSION", "APP_OWNER", t =>
                        {
                            t.HasCheckConstraint("CK_USER_SESSION_RISK", "RISK_FLAG IN (0, 1)");

                            t.HasCheckConstraint("CK_USER_SESSION_STATUS", "STATUS IN ('ACTIVE', 'EXPIRED', 'LOGOUT', 'LOCKED')");
                        });
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.Category", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.ShowSessions.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.MarketingContent", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.ShowSessions.Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.PriceStrategy", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.ShowSessions.ShowSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.PurchaseLimit", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.ShowSessions.ShowSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ShowtimeBackend.Entities.ShowSessions.Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Session");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.Show", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.ShowSessions.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.ShowSession", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.ShowSessions.Show", "Show")
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Show");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.ShowTag", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.ShowSessions.Show", "Show")
                        .WithMany("ShowTags")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SHOW_TAG_SHOW");

                    b.HasOne("ShowtimeBackend.Entities.ShowSessions.Tag", "Tag")
                        .WithMany("ShowTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SHOW_TAG_TAG");

                    b.Navigation("Show");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.OperationLog", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.UserPermission.SysUser", "User")
                        .WithMany("OperationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_OP_LOG_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.OrgStructure", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.UserPermission.OrgStructure", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_ORG_STRUCTURE_PARENT");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.Permission", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.UserPermission.Permission", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_PERMISSION_PARENT");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.RolePermission", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.UserPermission.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RP_PERMISSION");

                    b.HasOne("ShowtimeBackend.Entities.UserPermission.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RP_ROLE");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.SysUser", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.UserPermission.OrgStructure", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_SYS_USER_ORG");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.UserBlacklist", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.UserPermission.SysUser", "User")
                        .WithMany("BlacklistEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_BLACKLIST_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.UserRealName", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.UserPermission.SysUser", "User")
                        .WithMany("RealNames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_REAL_NAME_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.UserRole", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.UserPermission.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USER_ROLE_ROLE");

                    b.HasOne("ShowtimeBackend.Entities.UserPermission.SysUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_USER_ROLE_USER");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.UserSession", b =>
                {
                    b.HasOne("ShowtimeBackend.Entities.UserPermission.SysUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_USER_SESSION_USER");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.Show", b =>
                {
                    b.Navigation("ShowTags");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.ShowSessions.Tag", b =>
                {
                    b.Navigation("ShowTags");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.OrgStructure", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.Permission", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ShowtimeBackend.Entities.UserPermission.SysUser", b =>
                {
                    b.Navigation("BlacklistEntries");

                    b.Navigation("OperationLogs");

                    b.Navigation("RealNames");

                    b.Navigation("Sessions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
