/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfRegisterResponse"];
                        "application/json": components["schemas"]["ApiResponseOfRegisterResponse"];
                        "text/json": components["schemas"]["ApiResponseOfRegisterResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfRegisterResponse"];
                        "application/json": components["schemas"]["ApiResponseOfRegisterResponse"];
                        "text/json": components["schemas"]["ApiResponseOfRegisterResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfRegisterResponse"];
                        "application/json": components["schemas"]["ApiResponseOfRegisterResponse"];
                        "text/json": components["schemas"]["ApiResponseOfRegisterResponse"];
                    };
                };
                /** @description Service Unavailable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfRegisterResponse"];
                        "application/json": components["schemas"]["ApiResponseOfRegisterResponse"];
                        "text/json": components["schemas"]["ApiResponseOfRegisterResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfLoginResponse"];
                        "application/json": components["schemas"]["ApiResponseOfLoginResponse"];
                        "text/json": components["schemas"]["ApiResponseOfLoginResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfLoginResponse"];
                        "application/json": components["schemas"]["ApiResponseOfLoginResponse"];
                        "text/json": components["schemas"]["ApiResponseOfLoginResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfLoginResponse"];
                        "application/json": components["schemas"]["ApiResponseOfLoginResponse"];
                        "text/json": components["schemas"]["ApiResponseOfLoginResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfLoginResponse"];
                        "application/json": components["schemas"]["ApiResponseOfLoginResponse"];
                        "text/json": components["schemas"]["ApiResponseOfLoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/shows/{showId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    showId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfShowSessionDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfShowSessionDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfShowSessionDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/sessions/{sessionId}/pricing-strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfPricingStrategyDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfPricingStrategyDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfPricingStrategyDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/shows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    PageIndex?: number | string;
                    PageSize?: number | string;
                    Keyword?: string;
                    CategoryId?: number | string;
                    Status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfPagedResponseOfShowDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/client/shows/{showId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    showId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfShowDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfShowDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponseOfShowDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/shows/{showId}/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    showId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIEnumerableOfShowSessionDto"];
                        "application/json": components["schemas"]["ApiResponseOfIEnumerableOfShowSessionDto"];
                        "text/json": components["schemas"]["ApiResponseOfIEnumerableOfShowSessionDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    showId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateShowSessionRequest"];
                    "text/json": components["schemas"]["CreateShowSessionRequest"];
                    "application/*+json": components["schemas"]["CreateShowSessionRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfShowSessionDto"];
                        "application/json": components["schemas"]["ApiResponseOfShowSessionDto"];
                        "text/json": components["schemas"]["ApiResponseOfShowSessionDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfShowSessionDto"];
                        "application/json": components["schemas"]["ApiResponseOfShowSessionDto"];
                        "text/json": components["schemas"]["ApiResponseOfShowSessionDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfShowSessionDto"];
                        "application/json": components["schemas"]["ApiResponseOfShowSessionDto"];
                        "text/json": components["schemas"]["ApiResponseOfShowSessionDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sessions/{sessionId}/pricing-strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePriceStrategyRequest"][];
                    "text/json": components["schemas"]["CreatePriceStrategyRequest"][];
                    "application/*+json": components["schemas"]["CreatePriceStrategyRequest"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/sessions/{sessionId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateSessionStatusRequest"];
                    "text/json": components["schemas"]["UpdateSessionStatusRequest"];
                    "application/*+json": components["schemas"]["UpdateSessionStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/shows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    PageIndex?: number | string;
                    PageSize?: number | string;
                    Keyword?: string;
                    CategoryId?: number | string;
                    Status?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPagedResponseOfShowDto"];
                        "application/json": components["schemas"]["ApiResponseOfPagedResponseOfShowDto"];
                        "text/json": components["schemas"]["ApiResponseOfPagedResponseOfShowDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateShowRequest"];
                    "text/json": components["schemas"]["CreateShowRequest"];
                    "application/*+json": components["schemas"]["CreateShowRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfShowDto"];
                        "application/json": components["schemas"]["ApiResponseOfShowDto"];
                        "text/json": components["schemas"]["ApiResponseOfShowDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfShowDto"];
                        "application/json": components["schemas"]["ApiResponseOfShowDto"];
                        "text/json": components["schemas"]["ApiResponseOfShowDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/shows/{showId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    showId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfShowDto"];
                        "application/json": components["schemas"]["ApiResponseOfShowDto"];
                        "text/json": components["schemas"]["ApiResponseOfShowDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfShowDto"];
                        "application/json": components["schemas"]["ApiResponseOfShowDto"];
                        "text/json": components["schemas"]["ApiResponseOfShowDto"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    showId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateShowRequest"];
                    "text/json": components["schemas"]["UpdateShowRequest"];
                    "application/*+json": components["schemas"]["UpdateShowRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    showId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfObject"];
                        "application/json": components["schemas"]["ApiResponseOfObject"];
                        "text/json": components["schemas"]["ApiResponseOfObject"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/seat-locks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SeatLockBatchRequest"];
                    "text/json": components["schemas"]["SeatLockBatchRequest"];
                    "application/*+json": components["schemas"]["SeatLockBatchRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatLockBatchResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatLockBatchResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatLockBatchResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatLockBatchResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatLockBatchResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatLockBatchResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatLockBatchResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatLockBatchResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatLockBatchResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatLockBatchResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatLockBatchResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatLockBatchResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/seat-locks/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SeatLockReleaseRequest"];
                    "text/json": components["schemas"]["SeatLockReleaseRequest"];
                    "application/*+json": components["schemas"]["SeatLockReleaseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatLockReleaseResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatLockReleaseResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatLockReleaseResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatLockReleaseResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatLockReleaseResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatLockReleaseResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatLockReleaseResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatLockReleaseResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatLockReleaseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seat-maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    VenueId?: number | string;
                    MapStatus?: string;
                    Keyword?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPagedResponseOfSeatMapResponse"];
                        "application/json": components["schemas"]["ApiResponseOfPagedResponseOfSeatMapResponse"];
                        "text/json": components["schemas"]["ApiResponseOfPagedResponseOfSeatMapResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SeatMapRequest"];
                    "text/json": components["schemas"]["SeatMapRequest"];
                    "application/*+json": components["schemas"]["SeatMapRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatMapResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatMapResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatMapResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seat-maps/{seatMapId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatMapId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatMapResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatMapResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatMapResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatMapId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SeatMapRequest"];
                    "text/json": components["schemas"]["SeatMapRequest"];
                    "application/*+json": components["schemas"]["SeatMapRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatMapResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatMapResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatMapResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatMapId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seat-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    RuleType?: string;
                    RuleStatus?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPagedResponseOfSeatRuleResponse"];
                        "application/json": components["schemas"]["ApiResponseOfPagedResponseOfSeatRuleResponse"];
                        "text/json": components["schemas"]["ApiResponseOfPagedResponseOfSeatRuleResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SeatRuleRequest"];
                    "text/json": components["schemas"]["SeatRuleRequest"];
                    "application/*+json": components["schemas"]["SeatRuleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatRuleResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatRuleResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatRuleResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seat-rules/{seatRuleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatRuleId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatRuleResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatRuleResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatRuleResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatRuleId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SeatRuleRequest"];
                    "text/json": components["schemas"]["SeatRuleRequest"];
                    "application/*+json": components["schemas"]["SeatRuleRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatRuleResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatRuleResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatRuleResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatRuleId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seat-rules/{seatRuleId}/scopes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatRuleId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIReadOnlyListOfSeatRuleScopeResponse"];
                        "application/json": components["schemas"]["ApiResponseOfIReadOnlyListOfSeatRuleScopeResponse"];
                        "text/json": components["schemas"]["ApiResponseOfIReadOnlyListOfSeatRuleScopeResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatRuleId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SeatRuleScopeRequest"];
                    "text/json": components["schemas"]["SeatRuleScopeRequest"];
                    "application/*+json": components["schemas"]["SeatRuleScopeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatRuleScopeResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatRuleScopeResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatRuleScopeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seat-rule-scopes/{ruleScopeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    ruleScopeId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seat-sections/{seatSectionId}/seats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    SeatType?: string;
                    SeatStatus?: string;
                    IsSellable?: boolean;
                    RowCode?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path: {
                    seatSectionId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPagedResponseOfSeatResponse"];
                        "application/json": components["schemas"]["ApiResponseOfPagedResponseOfSeatResponse"];
                        "text/json": components["schemas"]["ApiResponseOfPagedResponseOfSeatResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatSectionId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SeatRequest"];
                    "text/json": components["schemas"]["SeatRequest"];
                    "application/*+json": components["schemas"]["SeatRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seats/{seatId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SeatRequest"];
                    "text/json": components["schemas"]["SeatRequest"];
                    "application/*+json": components["schemas"]["SeatRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seat-maps/{seatMapId}/sections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    SectionType?: string;
                    IsSellable?: boolean;
                    Page?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path: {
                    seatMapId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPagedResponseOfSeatSectionResponse"];
                        "application/json": components["schemas"]["ApiResponseOfPagedResponseOfSeatSectionResponse"];
                        "text/json": components["schemas"]["ApiResponseOfPagedResponseOfSeatSectionResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatMapId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SeatSectionRequest"];
                    "text/json": components["schemas"]["SeatSectionRequest"];
                    "application/*+json": components["schemas"]["SeatSectionRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatSectionResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatSectionResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatSectionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/seat-sections/{seatSectionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatSectionId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatSectionResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatSectionResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatSectionResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatSectionId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SeatSectionRequest"];
                    "text/json": components["schemas"]["SeatSectionRequest"];
                    "application/*+json": components["schemas"]["SeatSectionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSeatSectionResponse"];
                        "application/json": components["schemas"]["ApiResponseOfSeatSectionResponse"];
                        "text/json": components["schemas"]["ApiResponseOfSeatSectionResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    seatSectionId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/seat-map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    sessionId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSessionSeatMapDto"];
                        "application/json": components["schemas"]["ApiResponseOfSessionSeatMapDto"];
                        "text/json": components["schemas"]["ApiResponseOfSessionSeatMapDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfSessionSeatMapDto"];
                        "application/json": components["schemas"]["ApiResponseOfSessionSeatMapDto"];
                        "text/json": components["schemas"]["ApiResponseOfSessionSeatMapDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Status?: string;
                    Page?: number | string;
                    PageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPagedOrderResponse"];
                        "application/json": components["schemas"]["ApiResponseOfPagedOrderResponse"];
                        "text/json": components["schemas"]["ApiResponseOfPagedOrderResponse"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateOrderRequest"];
                    "text/json": components["schemas"]["CreateOrderRequest"];
                    "application/*+json": components["schemas"]["CreateOrderRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfOrderResponse"];
                        "application/json": components["schemas"]["ApiResponseOfOrderResponse"];
                        "text/json": components["schemas"]["ApiResponseOfOrderResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfOrderResponse"];
                        "application/json": components["schemas"]["ApiResponseOfOrderResponse"];
                        "text/json": components["schemas"]["ApiResponseOfOrderResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfOrderResponse"];
                        "application/json": components["schemas"]["ApiResponseOfOrderResponse"];
                        "text/json": components["schemas"]["ApiResponseOfOrderResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/orders/{orderId}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfIReadOnlyListOfPaymentResponse"];
                        "application/json": components["schemas"]["ApiResponseOfIReadOnlyListOfPaymentResponse"];
                        "text/json": components["schemas"]["ApiResponseOfIReadOnlyListOfPaymentResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{orderId}/payments/mock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    orderId: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MockPaymentRequest"];
                    "text/json": components["schemas"]["MockPaymentRequest"];
                    "application/*+json": components["schemas"]["MockPaymentRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApiResponseOfPaymentResponse"];
                        "application/json": components["schemas"]["ApiResponseOfPaymentResponse"];
                        "text/json": components["schemas"]["ApiResponseOfPaymentResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponseOfIEnumerableOfPricingStrategyDto: {
            success: boolean;
            data: null | components["schemas"]["PricingStrategyDto"][];
            code: null | string;
            message: string;
        };
        ApiResponseOfIEnumerableOfShowSessionDto: {
            success: boolean;
            data: null | components["schemas"]["ShowSessionDto"][];
            code: null | string;
            message: string;
        };
        ApiResponseOfIReadOnlyListOfPaymentResponse: {
            success: boolean;
            data: null | components["schemas"]["PaymentResponse"][];
            code: null | string;
            message: string;
        };
        ApiResponseOfIReadOnlyListOfSeatRuleScopeResponse: {
            success: boolean;
            data: null | components["schemas"]["SeatRuleScopeResponse"][];
            code: null | string;
            message: string;
        };
        ApiResponseOfLoginResponse: {
            success: boolean;
            data: null | components["schemas"]["LoginResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfObject: {
            success: boolean;
            data: unknown;
            code: null | string;
            message: string;
        };
        ApiResponseOfOrderResponse: {
            success: boolean;
            data: null | components["schemas"]["OrderResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfPagedOrderResponse: {
            success: boolean;
            data: null | components["schemas"]["PagedOrderResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfPagedResponseOfSeatMapResponse: {
            success: boolean;
            data: null | components["schemas"]["PagedResponseOfSeatMapResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfPagedResponseOfSeatResponse: {
            success: boolean;
            data: null | components["schemas"]["PagedResponseOfSeatResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfPagedResponseOfSeatRuleResponse: {
            success: boolean;
            data: null | components["schemas"]["PagedResponseOfSeatRuleResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfPagedResponseOfSeatSectionResponse: {
            success: boolean;
            data: null | components["schemas"]["PagedResponseOfSeatSectionResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfPagedResponseOfShowDto: {
            success: boolean;
            data: null | components["schemas"]["PagedResponseOfShowDto"];
            code: null | string;
            message: string;
        };
        ApiResponseOfPaymentResponse: {
            success: boolean;
            data: null | components["schemas"]["PaymentResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfRegisterResponse: {
            success: boolean;
            data: null | components["schemas"]["RegisterResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfSeatLockBatchResponse: {
            success: boolean;
            data: null | components["schemas"]["SeatLockBatchResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfSeatLockReleaseResponse: {
            success: boolean;
            data: null | components["schemas"]["SeatLockReleaseResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfSeatMapResponse: {
            success: boolean;
            data: null | components["schemas"]["SeatMapResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfSeatResponse: {
            success: boolean;
            data: null | components["schemas"]["SeatResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfSeatRuleResponse: {
            success: boolean;
            data: null | components["schemas"]["SeatRuleResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfSeatRuleScopeResponse: {
            success: boolean;
            data: null | components["schemas"]["SeatRuleScopeResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfSeatSectionResponse: {
            success: boolean;
            data: null | components["schemas"]["SeatSectionResponse"];
            code: null | string;
            message: string;
        };
        ApiResponseOfSessionSeatMapDto: {
            success: boolean;
            data: null | components["schemas"]["SessionSeatMapDto"];
            code: null | string;
            message: string;
        };
        ApiResponseOfShowDto: {
            success: boolean;
            data: null | components["schemas"]["ShowDto"];
            code: null | string;
            message: string;
        };
        ApiResponseOfShowSessionDto: {
            success: boolean;
            data: null | components["schemas"]["ShowSessionDto"];
            code: null | string;
            message: string;
        };
        CreateOrderItemRequest: {
            /** Format: int64 */
            seatId: number | string;
            /** Format: int64 */
            priceStrategyId: number | string;
            /** Format: int64 */
            realNameId: null | number | string;
            lockToken: string;
        };
        CreateOrderRequest: {
            /** Format: int64 */
            sessionId: number | string;
            items: components["schemas"]["CreateOrderItemRequest"][];
            remark: null | string;
        };
        CreatePriceStrategyRequest: {
            /** Format: int64 */
            seatSectionId: number | string;
            strategyName: null | string;
            priceType: string;
            /** Format: double */
            price: number | string;
            /** Format: date-time */
            saleStartTime: null | string;
            /** Format: date-time */
            saleEndTime: null | string;
            /**
             * Format: int32
             * @default 0
             */
            priority: number | string;
            /** Format: int64 */
            quota?: null | number | string;
        };
        CreateShowRequest: {
            showName: string;
            /** Format: int64 */
            categoryId: number | string;
            description: null | string;
            /** Format: int32 */
            durationMinutes: null | number | string;
            posterUrl: null | string;
        };
        CreateShowSessionRequest: {
            /** Format: int64 */
            sessionId: number | string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            /** Format: date-time */
            saleStartTime: string;
            /** Format: date-time */
            saleEndTime: string;
            /** Format: int64 */
            seatMapId: number | string;
        };
        ETicketSummaryResponse: {
            /** Format: int64 */
            eTicketId: number | string;
            eTicketNo: string;
            /** Format: int64 */
            orderItemId: number | string;
            ticketStatus: string;
        };
        LoginRequest: {
            account: string;
            password: string;
        };
        LoginResponse: {
            accessToken: string;
            tokenType: string;
            /** Format: int64 */
            expiresIn: number | string;
            /** Format: date-time */
            expiresAtUtc: string;
            user: components["schemas"]["UserResponse"];
        };
        MockPaymentRequest: {
            payChannel: string;
            result: string;
        };
        OrderItemResponse: {
            /** Format: int64 */
            orderItemId: number | string;
            /** Format: int64 */
            seatId: number | string;
            /** Format: int64 */
            priceStrategyId: number | string;
            /** Format: int64 */
            realNameId: null | number | string;
            /** Format: double */
            unitPrice: number | string;
            itemStatus: string;
        };
        OrderResponse: {
            /** Format: int64 */
            orderId: number | string;
            orderNo: string;
            /** Format: int64 */
            sessionId: number | string;
            /** Format: double */
            totalAmount: number | string;
            /** Format: double */
            discountAmount: number | string;
            /** Format: int32 */
            ticketCount: number | string;
            orderStatus: string;
            /** Format: date-time */
            expireTime: string;
            /** Format: date-time */
            payTime: null | string;
            /** Format: date-time */
            cancelTime: null | string;
            source: string;
            remark: null | string;
            items: components["schemas"]["OrderItemResponse"][];
            payments: components["schemas"]["PaymentResponse"][];
            tickets: components["schemas"]["ETicketSummaryResponse"][];
        };
        OrderSummaryResponse: {
            /** Format: int64 */
            orderId: number | string;
            orderNo: string;
            /** Format: int64 */
            sessionId: number | string;
            /** Format: double */
            totalAmount: number | string;
            /** Format: double */
            discountAmount: number | string;
            /** Format: int32 */
            ticketCount: number | string;
            orderStatus: string;
            /** Format: date-time */
            expireTime: string;
            /** Format: date-time */
            createTime: string;
        };
        PagedOrderResponse: {
            items: components["schemas"]["OrderSummaryResponse"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
        };
        PagedResponseOfSeatMapResponse: {
            items: components["schemas"]["SeatMapResponse"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
        };
        PagedResponseOfSeatResponse: {
            items: components["schemas"]["SeatResponse"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
        };
        PagedResponseOfSeatRuleResponse: {
            items: components["schemas"]["SeatRuleResponse"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
        };
        PagedResponseOfSeatSectionResponse: {
            items: components["schemas"]["SeatSectionResponse"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
        };
        PagedResponseOfShowDto: {
            items: components["schemas"]["ShowDto"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
        };
        PaymentResponse: {
            /** Format: int64 */
            paymentId: number | string;
            paymentNo: string;
            /** Format: int64 */
            orderId: number | string;
            /** Format: double */
            payAmount: number | string;
            payChannel: string;
            payStatus: string;
            tradeNo: null | string;
            /** Format: date-time */
            callbackTime: null | string;
            /** Format: date-time */
            payTime: null | string;
        };
        PricingStrategyDto: {
            /** Format: int64 */
            priceStrategyId: number | string;
            /** Format: int64 */
            seatSectionId: number | string;
            priceType: string;
            /** Format: double */
            price: number | string;
            status: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        RegisterRequest: {
            userName: string;
            password: string;
            phone: string;
            nickname?: null | string;
            email?: null | string;
        };
        RegisterResponse: {
            user: components["schemas"]["UserResponse"];
        };
        SeatLockBatchRequest: {
            seatIds: (number | string)[];
        };
        SeatLockBatchResponse: {
            /** Format: int64 */
            sessionId: number | string;
            /** Format: date-time */
            expireTime: string;
            locks: components["schemas"]["SeatLockItemResponse"][];
        };
        SeatLockItemResponse: {
            /** Format: int64 */
            seatId: number | string;
            lockToken: string;
            /** Format: date-time */
            expireTime: string;
        };
        SeatLockReleaseRequest: {
            lockTokens: string[];
        };
        SeatLockReleaseResponse: {
            /** Format: int64 */
            sessionId: number | string;
            /** Format: int32 */
            releasedCount: number | string;
        };
        SeatMapRequest: {
            /** Format: int64 */
            venueId: number | string;
            mapCode: string;
            mapName: string;
            mapVersion: string;
            isDefault: boolean;
            /** Format: double */
            mapWidth: null | number | string;
            /** Format: double */
            mapHeight: null | number | string;
            mapStatus: string;
            remark: null | string;
        };
        SeatMapResponse: {
            /** Format: int64 */
            seatMapId: number | string;
            /** Format: int64 */
            venueId: number | string;
            venueName: string;
            mapCode: string;
            mapName: string;
            mapVersion: string;
            isDefault: boolean;
            /** Format: double */
            mapWidth: null | number | string;
            /** Format: double */
            mapHeight: null | number | string;
            mapStatus: string;
            remark: null | string;
        };
        SeatRequest: {
            rowCode: string;
            seatNo: string;
            /** Format: int32 */
            rowIndex: number | string;
            /** Format: int32 */
            colIndex: number | string;
            /** Format: double */
            xCoord: number | string;
            /** Format: double */
            yCoord: number | string;
            seatType: string;
            seatStatus: string;
            isAisleSide: boolean;
            isSellable: boolean;
            remark: null | string;
        };
        SeatResponse: {
            /** Format: int64 */
            seatId: number | string;
            /** Format: int64 */
            seatSectionId: number | string;
            rowCode: string;
            seatNo: string;
            /** Format: int32 */
            rowIndex: number | string;
            /** Format: int32 */
            colIndex: number | string;
            /** Format: double */
            xCoord: number | string;
            /** Format: double */
            yCoord: number | string;
            seatType: string;
            seatStatus: string;
            isAisleSide: boolean;
            isSellable: boolean;
            remark: null | string;
        };
        SeatRuleRequest: {
            ruleCode: string;
            ruleName: string;
            ruleType: string;
            /** Format: int32 */
            minSeatCount: number | string;
            /** Format: int32 */
            maxSeatCount: number | string;
            allowCrossRow: boolean;
            allowCrossSection: boolean;
            /** Format: int32 */
            priority: number | string;
            ruleStatus: string;
            remark: null | string;
        };
        SeatRuleResponse: {
            /** Format: int64 */
            seatRuleId: number | string;
            ruleCode: string;
            ruleName: string;
            ruleType: string;
            /** Format: int32 */
            minSeatCount: number | string;
            /** Format: int32 */
            maxSeatCount: number | string;
            allowCrossRow: boolean;
            allowCrossSection: boolean;
            /** Format: int32 */
            priority: number | string;
            ruleStatus: string;
            remark: null | string;
        };
        SeatRuleScopeRequest: {
            scopeType: string;
            /** Format: int64 */
            seatMapId: null | number | string;
            /** Format: int64 */
            seatSectionId: null | number | string;
            scopeStatus: string;
        };
        SeatRuleScopeResponse: {
            /** Format: int64 */
            ruleScopeId: number | string;
            /** Format: int64 */
            seatRuleId: number | string;
            scopeType: string;
            /** Format: int64 */
            seatMapId: null | number | string;
            /** Format: int64 */
            seatSectionId: null | number | string;
            scopeStatus: string;
        };
        SeatSectionRequest: {
            sectionCode: string;
            sectionName: string;
            sectionType: string;
            sectionColor: null | string;
            floorNo: null | string;
            isSellable: boolean;
            /** Format: int32 */
            displayOrder: number | string;
            remark: null | string;
        };
        SeatSectionResponse: {
            /** Format: int64 */
            seatSectionId: number | string;
            /** Format: int64 */
            seatMapId: number | string;
            sectionCode: string;
            sectionName: string;
            sectionType: string;
            sectionColor: null | string;
            floorNo: null | string;
            isSellable: boolean;
            /** Format: int32 */
            displayOrder: number | string;
            remark: null | string;
        };
        SessionSeatMapDto: {
            /** Format: int64 */
            sessionId: number | string;
            /** Format: int64 */
            showId: number | string;
            /** Format: int64 */
            seatMapId: number | string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            /** Format: date-time */
            saleStartTime: string;
            /** Format: date-time */
            saleEndTime: string;
            sessionStatus: string;
            seatMap: components["schemas"]["SessionSeatMapMapDto"];
        };
        SessionSeatMapMapDto: {
            /** Format: int64 */
            seatMapId: number | string;
            /** Format: int64 */
            venueId: number | string;
            mapCode: string;
            mapName: string;
            mapVersion: string;
            isDefault: boolean;
            /** Format: double */
            mapWidth: null | number | string;
            /** Format: double */
            mapHeight: null | number | string;
            mapStatus: string;
            sections: components["schemas"]["SessionSeatMapSectionDto"][];
        };
        SessionSeatMapSeatDto: {
            /** Format: int64 */
            seatId: number | string;
            /** Format: int64 */
            seatSectionId: number | string;
            rowCode: string;
            seatNo: string;
            /** Format: int32 */
            rowIndex: number | string;
            /** Format: int32 */
            colIndex: number | string;
            /** Format: double */
            xCoord: number | string;
            /** Format: double */
            yCoord: number | string;
            seatType: string;
            seatStatus: string;
            isAisleSide: boolean;
            isSellable: boolean;
            availabilityStatus: string;
        };
        SessionSeatMapSectionDto: {
            /** Format: int64 */
            seatSectionId: number | string;
            /** Format: int64 */
            seatMapId: number | string;
            sectionCode: string;
            sectionName: string;
            sectionType: string;
            sectionColor: null | string;
            floorNo: null | string;
            isSellable: boolean;
            /** Format: int32 */
            displayOrder: number | string;
            seats: components["schemas"]["SessionSeatMapSeatDto"][];
        };
        ShowDto: {
            /** Format: int64 */
            showId: number | string;
            showName: string;
            /** Format: int64 */
            categoryId: number | string;
            description: null | string;
            /** Format: int32 */
            durationMinutes: null | number | string;
            posterUrl: null | string;
            status: string;
            auditStatus: string;
            /** Format: date-time */
            createTime: string;
        };
        ShowSessionDto: {
            /** Format: int64 */
            showId: number | string;
            /** Format: int64 */
            sessionId: number | string;
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            /** Format: date-time */
            saleStartTime: string;
            sessionStatus: string;
            /** Format: int64 */
            seatMapId: number | string;
        };
        UpdateSessionStatusRequest: {
            status: string;
        };
        UpdateShowRequest: {
            showName: string;
            /** Format: int64 */
            categoryId: number | string;
            description: null | string;
            /** Format: int32 */
            durationMinutes: null | number | string;
            posterUrl: null | string;
            status: string;
        };
        UserResponse: {
            /** Format: int64 */
            userId: number | string;
            userName: string;
            nickname: null | string;
            phone: string;
            email: null | string;
            roles: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
